# -*- coding: utf-8 -*-
"""ErrorVersionCodesV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tp1toIYnfZYp8_zZ5OkjiQaUVqcMhIO
"""

# Below is same double link, but with the error variables needing to be edited in only one place

!pip install pypdf -q
from pypdf import PdfWriter, PdfReader

# Version replacing c with tau for double-link figure generation

# @title
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

plt.rcParams.update({
    'font.size': 13,
    'axes.labelsize': 16,
    'axes.titlesize': 17,
    'xtick.labelsize': 13,
    'ytick.labelsize': 13,
    'legend.fontsize': 14,
    'figure.titlesize': 18,
    'lines.linewidth': 2.4,
    'lines.markersize': 7
})

os.makedirs("figures_for_paper", exist_ok=True)

SEED = 42
np.random.seed(SEED)

n_samples = 200000

F_INIT = 0.90
P_GATE = 1.00
P_MEAS = 1.00

lambda_vals_physical = [10.0, 3.0, 100.0]
tau_vals_physical = [0.1, 1.0, 100.0]

PROTOCOL_LABELS = {
    'discard': 'Discard-Swap',
    'dt_aa': 'D-ASAP-S-ASAP',
    'dt_al': 'D-ASAP-S-ALAP',
    'dt_ll': 'D-ALAP-S-ALAP',
    'st_aa': 'S-ASAP-D-ASAP',
    'st_al': 'S-ASAP-D-ALAP',
    'st_ll': 'S-ALAP-D-ALAP'
}

all_dataframes = []

def raw_fidelity(t_gen, t_total, tau):
    A = 1/4
    B = F_INIT - A
    return np.clip(A + B * np.exp(-2 * (t_total - t_gen) / tau), 0, 1)

def compute_fidelity(F_init, t_idle, tau):
    A = 1/4
    B = F_init - A
    return np.clip(A + B * np.exp(-2 * t_idle / tau), 0, 1)

def isotropic_purification_pairwise(F1, F2, p_gate=1.0, p_meas=1.0):

    e1 = (1 - F1) / 3
    e2 = (1 - F2) / 3

    if p_gate == 1.0 and p_meas == 1.0:
        num = F1 * F2 + (1/9) * (1 - F1) * (1 - F2)
        denom = (F1 * F2 + (1/3) * F1 * (1 - F2) + (1/3) * F2 * (1 - F1) +
                 (5/9) * (1 - F1) * (1 - F2))
        F_out = np.clip(num / denom, 0, 1)
        p_success = denom
    else:
        eta = p_meas
        p = p_gate

        p_success = (p**2 * (eta**2 + (1 - eta)**2) *
                     (F1*F2 + F1*e2 + e1*F2 + 5*e1*e2) +
                     2 * p**2 * eta * (1 - eta) *
                     (2*F1*e2 + 2*e1*F2 + 4*e1*e2) +
                     (1 - p**2) / 2)

        numerator = ((eta**2 + (1 - eta)**2) * (F1*F2 + e1*e2) +
                     2 * eta * (1 - eta) * (F1*e2 + e1*e2) +
                     (1 - p**2) / (8 * p**2))

        denominator = ((eta**2 + (1 - eta)**2) *
                       (F1*F2 + F1*e2 + e1*F2 + 5*e1*e2) +
                       2 * eta * (1 - eta) *
                       (2*F1*e2 + 2*e1*F2 + 4*e1*e2) +
                       (1 - p**2) / (2 * p**2))

        F_out = np.clip(numerator / denominator, 0, 1)

    return F_out, p_success

def swapped_fidelity(F1, F2, p_gate=1.0, p_meas=1.0):
    if p_gate == 1.0 and p_meas == 1.0:
        return np.clip(F1 * F2 + (1 - F1) * (1 - F2) / 3, 0, 1)
    else:
        eta = p_meas
        p = p_gate
        e1 = (1 - F1) / 3
        e2 = (1 - F2) / 3

        F_swap = ((1 - p) / 4 +
                  p * (eta**2 * (F1*F2 + 3*e1*e2) +
                       (1 - eta**2) * (F1*e2 + e1*F2 + 2*e1*e2)))

        return np.clip(F_swap, 0, 1)

def coherent_information_vectorized(F):
    λ1 = F
    λ_rest = (1 - F) / 3
    eigs = np.stack([λ1, λ_rest, λ_rest, λ_rest], axis=-1)
    S = -np.sum(eigs * np.log2(eigs + 1e-12), axis=-1)
    return np.maximum(0, 1 - S)

def state_availability(t1a, t1b, t2a, t2b, T):
    available = np.zeros(len(t1a), dtype=int)
    available += (t1a < T).astype(int) + (t1b < T).astype(int) + (t2a < T).astype(int) + (t2b < T).astype(int)
    return available

def sample_link_arrivals(n_samples, lam):
    s = np.random.exponential(scale=1.0 / lam, size=(2, 2, n_samples))
    s.sort(axis=1)
    return {'t_l1_1': s[0, 0], 't_l1_2': s[0, 1],
            't_l2_1': s[1, 0], 't_l2_2': s[1, 1]}


def _weighted_summary(valid, weight, F_final, n_samples):
    w = np.where(valid, weight, 0.0)
    total = w.sum()
    if total <= 0:
        return 0.0, 0.0, 0.0, 0.0
    F_mean = float((w * F_final).sum() / total)
    P_succ = float(w.mean())
    mean_Ic = float(coherent_information_vectorized(F_mean) * P_succ)
    return mean_Ic, 0.0, F_mean, P_succ


def discard_oldest(n_samples, lam, tau, T, samples, p_gate=1.0, p_meas=1.0):
    a1, a2 = samples['t_l1_1'], samples['t_l1_2']
    b1, b2 = samples['t_l2_1'], samples['t_l2_2']
    valid = (a1 < T) & (b1 < T)
    a_new = np.where(a2 < T, a2, a1)
    b_new = np.where(b2 < T, b2, b1)
    F_final = swapped_fidelity(raw_fidelity(a_new, T, tau),
                               raw_fidelity(b_new, T, tau), p_gate, p_meas)
    return _weighted_summary(valid, np.ones(n_samples), F_final, n_samples)


def distill_then_swap(n_samples, lam, tau, T, samples, distill_strategy, swap_strategy,
                      p_gate=1.0, p_meas=1.0):
    # NOTE (correction): the ASAP branch previously set each link's distillation
    # time to link_pairs[1], the second arrival, and then swapped at the max of
    # those. A pair arriving after both links were first ready could therefore
    # postpone a swap that the stated policy requires to happen immediately, so
    # the schedule used information not available at decision time. The swap
    # time is now fixed at max(a1, b1) first, and a link is distilled only if
    # its second pair has already arrived by then.
    a1, a2 = samples['t_l1_1'], samples['t_l1_2']
    b1, b2 = samples['t_l2_1'], samples['t_l2_2']
    valid = (a1 < T) & (b1 < T)

    if distill_strategy == 'ASAP' and swap_strategy == 'ASAP':
        t_swap = np.maximum(a1, b1)
        distill_a = valid & (a2 <= t_swap)
        distill_b = valid & (b2 <= t_swap)

        Fa_d, pa = isotropic_purification_pairwise(
            raw_fidelity(a1, a2, tau), np.full_like(a1, F_INIT), p_gate, p_meas)
        Fb_d, pb = isotropic_purification_pairwise(
            raw_fidelity(b1, b2, tau), np.full_like(b1, F_INIT), p_gate, p_meas)

        Fa = np.where(distill_a, compute_fidelity(Fa_d, t_swap - a2, tau),
                      raw_fidelity(a1, t_swap, tau))
        Fb = np.where(distill_b, compute_fidelity(Fb_d, t_swap - b2, tau),
                      raw_fidelity(b1, t_swap, tau))
        weight = np.where(distill_a, pa, 1.0) * np.where(distill_b, pb, 1.0)
        F_final = compute_fidelity(
            swapped_fidelity(Fa, Fb, p_gate, p_meas), T - t_swap, tau)
        return _weighted_summary(valid, weight, F_final, n_samples)

    def link_at_T(x1, x2):
        has_two = x2 < T
        if distill_strategy == 'ASAP':
            F_d, p_d = isotropic_purification_pairwise(
                raw_fidelity(x1, x2, tau), np.full_like(x1, F_INIT), p_gate, p_meas)
            F_two = compute_fidelity(F_d, T - x2, tau)
        else:
            F_d, p_d = isotropic_purification_pairwise(
                raw_fidelity(x1, T, tau), raw_fidelity(x2, T, tau), p_gate, p_meas)
            F_two = F_d
        return (np.where(has_two, F_two, raw_fidelity(x1, T, tau)),
                np.where(has_two, p_d, 1.0))

    Fa, pa = link_at_T(a1, a2)
    Fb, pb = link_at_T(b1, b2)
    F_final = swapped_fidelity(Fa, Fb, p_gate, p_meas)
    return _weighted_summary(valid, pa * pb, F_final, n_samples)


def _swap_pair(x, y, tau, asap, T, p_gate, p_meas):
    t = np.maximum(x, y) if asap else np.full_like(x, T)
    F = swapped_fidelity(raw_fidelity(x, t, tau), raw_fidelity(y, t, tau),
                         p_gate, p_meas)
    return t, F


def swap_then_distill(n_samples, lam, tau, T, samples, swap_strategy, distill_strategy,
                      p_gate=1.0, p_meas=1.0):
    # NOTE (correction): distillation requires two copies of entanglement shared
    # between the SAME two end nodes, so the second copy must come from a second
    # full swap, which itself requires a second elementary pair on EACH segment.
    # NOTE (correction): the second swap was previously performed at T, with the
    # elementary pairs decayed to T before being swapped, so only the first of
    # the two swaps was actually ASAP. Both swaps now occur as soon as their
    # inputs exist, and only the final distillation is deferred for the D-ALAP
    # variants.
    a1, a2 = samples['t_l1_1'], samples['t_l1_2']
    b1, b2 = samples['t_l2_1'], samples['t_l2_2']
    valid = (a1 < T) & (b1 < T)
    has_second = valid & (a2 < T) & (b2 < T)

    swap_asap = (swap_strategy == 'ASAP')
    t1, F1 = _swap_pair(a1, b1, tau, swap_asap, T, p_gate, p_meas)
    t2, F2 = _swap_pair(a2, b2, tau, swap_asap, T, p_gate, p_meas)

    if distill_strategy == 'ASAP':
        t_d = np.maximum(t1, t2)
        F_d, p_d = isotropic_purification_pairwise(
            compute_fidelity(F1, t_d - t1, tau),
            compute_fidelity(F2, t_d - t2, tau), p_gate, p_meas)
        F_if_two = compute_fidelity(F_d, T - t_d, tau)
    else:
        F_d, p_d = isotropic_purification_pairwise(
            compute_fidelity(F1, T - t1, tau),
            compute_fidelity(F2, T - t2, tau), p_gate, p_meas)
        F_if_two = F_d

    F_one = compute_fidelity(F1, T - t1, tau)
    F_final = np.where(has_second, F_if_two, F_one)
    weight = np.where(has_second, p_d, 1.0)
    return _weighted_summary(valid, weight, F_final, n_samples)


def discard_oldest_distribution(n_samples, lam, tau, T, samples, p_gate=1.0, p_meas=1.0):
    a1, a2 = samples['t_l1_1'], samples['t_l1_2']
    b1, b2 = samples['t_l2_1'], samples['t_l2_2']
    valid = (a1 < T) & (b1 < T)
    a_new = np.where(a2 < T, a2, a1)
    b_new = np.where(b2 < T, b2, b1)
    F = swapped_fidelity(raw_fidelity(a_new, T, tau),
                         raw_fidelity(b_new, T, tau), p_gate, p_meas)[valid]
    return F, coherent_information_vectorized(F)


def swap_then_distill_distribution(n_samples, lam, tau, T, samples,
                                   swap_strategy, distill_strategy,
                                   p_gate=1.0, p_meas=1.0):
    # NOTE (correction): same topology and second-swap timing fixes as in
    # swap_then_distill. The distillation attempt is rejection-sampled so that
    # only actual successful outputs enter the histogram.
    a1, a2 = samples['t_l1_1'], samples['t_l1_2']
    b1, b2 = samples['t_l2_1'], samples['t_l2_2']
    valid = (a1 < T) & (b1 < T)
    has_second = valid & (a2 < T) & (b2 < T)

    swap_asap = (swap_strategy == 'ASAP')
    t1, F1 = _swap_pair(a1, b1, tau, swap_asap, T, p_gate, p_meas)
    t2, F2 = _swap_pair(a2, b2, tau, swap_asap, T, p_gate, p_meas)

    if distill_strategy == 'ASAP':
        t_d = np.maximum(t1, t2)
        F_d, p_d = isotropic_purification_pairwise(
            compute_fidelity(F1, t_d - t1, tau),
            compute_fidelity(F2, t_d - t2, tau), p_gate, p_meas)
        F_if_two = compute_fidelity(F_d, T - t_d, tau)
    else:
        F_d, p_d = isotropic_purification_pairwise(
            compute_fidelity(F1, T - t1, tau),
            compute_fidelity(F2, T - t2, tau), p_gate, p_meas)
        F_if_two = F_d

    F_one = compute_fidelity(F1, T - t1, tau)
    accept = np.random.uniform(0.0, 1.0, size=n_samples) < p_d
    keep = valid & np.where(has_second, accept, True)
    F = np.where(has_second, F_if_two, F_one)[keep]
    return F, coherent_information_vectorized(F)


def shared_bin_edges(*datasets, bins=60):
    pooled = np.concatenate([np.asarray(d).ravel() for d in datasets
                             if np.asarray(d).size > 0])
    if pooled.size == 0:
        return np.linspace(0.0, 1.0, bins + 1)
    lo, hi = float(pooled.min()), float(pooled.max())
    if hi <= lo:
        hi = lo + 1e-9
    return np.linspace(lo, hi, bins + 1)


def analytic_repeated_swap(F0, N, p_gate=1.0, p_meas=1.0):
    arr = [F0] * N
    while len(arr) > 1:
        arr = [swapped_fidelity(arr[j], arr[j+1], p_gate, p_meas) if j+1 < len(arr)
               else arr[j] for j in range(0, len(arr), 2)]
    return arr[0]

print("\n" + "="*80)
print("QUANTUM REPEATER SIMULATION")
print("="*80)
print(f"Operation parameters: p_gate = {P_GATE}, p_meas = {P_MEAS}")
if P_GATE == 1.0 and P_MEAS == 1.0:
    print("  → PERFECT OPERATIONS (reproduces original code)")
elif P_GATE == 0.9 and P_MEAS == 0.9:
    print("  → IMPERFECT OPERATIONS (paper's condition)")
else:
    print(f"  → CUSTOM OPERATION QUALITY")
print("="*80)

print("\n" + "="*80)
print("COMPUTING PHYSICAL PARAMETER REGIMES")
print("="*80)

results_physical = {}
for lam in lambda_vals_physical:
    for tau in tau_vals_physical:
        key = f"lam{lam}_tau{tau}"
        print(f"\nProcessing λ={lam}/s, τ={tau}s...")

        T_min = 0.01 * tau
        T_max = 0.2 * tau

        T_vals = np.linspace(T_min, T_max, 30)

        results = {
            'T': T_vals,
            'discard_Ic': [], 'discard_F': [], 'discard_Pr': [],
            'dt_aa_Ic': [], 'dt_aa_F': [], 'dt_aa_Pr': [],
            'dt_al_Ic': [], 'dt_al_F': [], 'dt_al_Pr': [],
            'dt_ll_Ic': [], 'dt_ll_F': [], 'dt_ll_Pr': [],
            'st_aa_Ic': [], 'st_aa_F': [], 'st_aa_Pr': [],
            'st_al_Ic': [], 'st_al_F': [], 'st_al_Pr': [],
            'st_ll_Ic': [], 'st_ll_F': [], 'st_ll_Pr': []
        }

        for T in T_vals:
            np.random.seed(SEED)
            samples = sample_link_arrivals(n_samples, lam)




            mean_Ic, _, F_mean, Pr = discard_oldest(n_samples, lam, tau, T, samples, P_GATE, P_MEAS)
            results['discard_Ic'].append(mean_Ic)
            results['discard_F'].append(F_mean)
            results['discard_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = distill_then_swap(n_samples, lam, tau, T, samples, 'ASAP', 'ASAP', P_GATE, P_MEAS)
            results['dt_aa_Ic'].append(mean_Ic)
            results['dt_aa_F'].append(F_mean)
            results['dt_aa_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = distill_then_swap(n_samples, lam, tau, T, samples, 'ASAP', 'ALAP', P_GATE, P_MEAS)
            results['dt_al_Ic'].append(mean_Ic)
            results['dt_al_F'].append(F_mean)
            results['dt_al_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = distill_then_swap(n_samples, lam, tau, T, samples, 'ALAP', 'ALAP', P_GATE, P_MEAS)
            results['dt_ll_Ic'].append(mean_Ic)
            results['dt_ll_F'].append(F_mean)
            results['dt_ll_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = swap_then_distill(n_samples, lam, tau, T, samples, 'ASAP', 'ASAP', P_GATE, P_MEAS)
            results['st_aa_Ic'].append(mean_Ic)
            results['st_aa_F'].append(F_mean)
            results['st_aa_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = swap_then_distill(n_samples, lam, tau, T, samples, 'ASAP', 'ALAP', P_GATE, P_MEAS)
            results['st_al_Ic'].append(mean_Ic)
            results['st_al_F'].append(F_mean)
            results['st_al_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = swap_then_distill(n_samples, lam, tau, T, samples, 'ALAP', 'ALAP', P_GATE, P_MEAS)
            results['st_ll_Ic'].append(mean_Ic)
            results['st_ll_F'].append(F_mean)
            results['st_ll_Pr'].append(Pr)

        results_physical[key] = results

        df = pd.DataFrame(results)
        df['Data_Section'] = f'Physical_Params_{key}'
        parts = key.replace('lam', '').split('_tau')
        df['lambda'] = float(parts[0])
        df['tau'] = float(parts[1])
        df['p_gate'] = P_GATE
        df['p_meas'] = P_MEAS
        all_dataframes.append(df)

# ---------------------------------------------------------------------------
# Fig. 5 diagnostic (Allen's comment: "at the top (what about D-ASAP-S-ASAP?)").
# Prints where each strategy's expected fidelity sits at lambda=10, tau=0.1 so
# the two-group sentence in Sec. IV.A can be corrected against the data rather
# than by inspection of the plot.
# ---------------------------------------------------------------------------
print("\n" + "="*80)
print("FIG. 5 DIAGNOSTIC: expected fidelity grouping at lambda=10/s, tau=0.1s")
print("="*80)
_res_fig5 = results_physical['lam10.0_tau0.1']
print(f"{'Strategy':<18} {'F[0]':>10} {'F[-1]':>10} {'mean':>10}")
print("-"*80)
for _p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']:
    _F = np.array(_res_fig5[f'{_p}_F'])
    print(f"{PROTOCOL_LABELS[_p]:<18} {_F[0]:>10.4f} {_F[-1]:>10.4f} {_F.mean():>10.4f}")
print("="*80)

print("\n" + "="*80)
print("PARAMETER REGIME DIAGNOSTICS")
print("="*80)

for lam in lambda_vals_physical:
    for tau in tau_vals_physical:
        key = f"lam{lam}_tau{tau}"

        expected_gen_time = 2.0 / lam
        T_max = 0.2 * tau
        ratio = T_max / expected_gen_time

        max_Ic = max([np.max(results_physical[key][f'{p}_Ic']) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']])

        if ratio < 0.5:
            status = "FAILED"
            reason = f"T_max ({T_max:.4f}s) much less than gen time ({expected_gen_time:.4f}s)"
        elif ratio < 1.0:
            status = "MARGINAL"
            reason = f"T_max ({T_max:.4f}s) less than gen time ({expected_gen_time:.4f}s)"
        elif max_Ic < 0.1:
            status = "LOW Ic"
            reason = f"T_max adequate but high decoherence"
        else:
            status = "GOOD"
            reason = f"T_max ({T_max:.4f}s) greater than gen time ({expected_gen_time:.4f}s)"

        print(f"\n{key}: {status}")
        print(f"  Expected generation time: {expected_gen_time:.6f}s")
        print(f"  T_max (coherence time): {T_max:.6f}s")
        print(f"  Ratio (T_max/gen_time): {ratio:.3f}")
        print(f"  Max coherent info: {max_Ic:.6f}")
        print(f"  Reason: {reason}")

print("\n" + "="*80)
print("SUMMARY")
print("="*80)

good_regimes = []
marginal_regimes = []
failed_regimes = []

for lam in lambda_vals_physical:
    for tau in tau_vals_physical:
        key = f"lam{lam}_tau{tau}"
        expected_gen_time = 2.0 / lam
        T_max = 0.2 * tau
        ratio = T_max / expected_gen_time
        max_Ic = max([np.max(results_physical[key][f'{p}_Ic']) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']])

        if ratio >= 1.0 and max_Ic >= 0.1:
            good_regimes.append(key)
        elif ratio < 0.5:
            failed_regimes.append(key)
        else:
            marginal_regimes.append(key)

print(f"\nGOOD regimes ({len(good_regimes)}): {', '.join(good_regimes)}")
print(f"MARGINAL regimes ({len(marginal_regimes)}): {', '.join(marginal_regimes)}")
print(f"FAILED regimes ({len(failed_regimes)}): {', '.join(failed_regimes)}")

print("\n" + "="*80)
print("GENERATING FIGURES WITH PHYSICAL PARAMETERS")
print("="*80)

# Figures 1–9: one figure per (lambda, metric) combination.
# Each figure is a 1×3 row across the three tau values.
# lambda_vals_physical = [10.0, 3.0, 100.0]
# metrics: Ic, F, Pr;  9 figures total

metric_cfg = [
    ('Ic',  'Weighted coherent info',  'coherent_info'),
    ('F',   'Expected fidelity',       'fidelity'),
    ('Pr',  'Success probability',     'success_prob'),
]

fig_counter = 1
for lam in lambda_vals_physical:
    lam_str = str(int(lam)) if lam == int(lam) else str(lam)

    for metric_key, metric_ylabel, metric_fname in metric_cfg:
        fig, axes = plt.subplots(1, 3, figsize=(18, 5))

        for j, tau in enumerate(tau_vals_physical):
            key = f"lam{lam}_tau{tau}"
            res = results_physical[key]
            ax = axes[j]


            ax.plot(res['T'], res[f'discard_{metric_key}'],
                    label=PROTOCOL_LABELS['discard'], marker='D', color='black', markersize=5)
            ax.plot(res['T'], res[f'dt_aa_{metric_key}'],
                    label=PROTOCOL_LABELS['dt_aa'], marker='o', alpha=0.7)
            ax.plot(res['T'], res[f'dt_al_{metric_key}'],
                    label=PROTOCOL_LABELS['dt_al'], marker='s', alpha=0.7)
            ax.plot(res['T'], res[f'dt_ll_{metric_key}'],
                    label=PROTOCOL_LABELS['dt_ll'], marker='^', alpha=0.7)
            ax.plot(res['T'], res[f'st_aa_{metric_key}'],
                    label=PROTOCOL_LABELS['st_aa'], marker='v', alpha=0.7)
            ax.plot(res['T'], res[f'st_al_{metric_key}'],
                    label=PROTOCOL_LABELS['st_al'], marker='<', alpha=0.7)
            ax.plot(res['T'], res[f'st_ll_{metric_key}'],
                    label=PROTOCOL_LABELS['st_ll'], marker='>', alpha=0.7)

            ax.set_title(f"λ={lam}/s, τ={tau}s", fontweight='bold')
            ax.set_xlabel("T (s)")
            ax.set_ylabel(metric_ylabel)

            if tau == 0.1:
                ax.set_xticks(np.arange(0, 0.021, 0.005))
            elif tau == 1.0:
                ax.set_xticks(np.arange(0, 0.21, 0.05))
            elif tau == 100.0:
                ax.set_xticks(np.arange(0, 21, 5))

            ax.grid(alpha=0.3)
            if j == 0:
                ax.legend(fontsize=14, ncol=2)

        plt.tight_layout()
        fname = f"figures_for_paper/lam{lam_str}_{metric_fname}_vs_T.pdf"
        plt.savefig(fname, dpi=300)
        plt.show()
        print(f"  ✓ Figure {fig_counter} saved: lam{lam_str}_{metric_fname}_vs_T.pdf")
        fig_counter += 1

print("\n" + "="*80)
print("GENERATING ADDITIONAL FIGURES")
print("="*80)

lambda_vals = np.linspace(0.1, 2.0, 20)
tau_regimes = {'small': 0.5, 'medium': 10.0, 'large': 50.0}

results_by_tau = {}
fidelities_by_tau = {}
success_probs_by_tau = {}

for tau_name, tau_val in tau_regimes.items():
    print(f"\nProcessing τ = {tau_val} ({tau_name})...")
    results_8protocols = {'discard': [], 'dt_aa': [], 'dt_al': [], 'dt_ll': [], 'st_aa': [], 'st_al': [], 'st_ll': []}
    results_4basic = {'dt_END': [], 'dt_ASAP': [], 'st_END': [], 'st_ASAP': []}
    std_8protocols = {'discard': [], 'dt_aa': [], 'dt_al': [], 'dt_ll': [], 'st_aa': [], 'st_al': [], 'st_ll': []}
    fidelities_8protocols = {'discard': [], 'dt_aa': [], 'dt_al': [], 'dt_ll': [], 'st_aa': [], 'st_al': [], 'st_ll': []}
    probs_8protocols = {'discard': [], 'dt_aa': [], 'dt_al': [], 'dt_ll': [], 'st_aa': [], 'st_al': [], 'st_ll': []}

    for lam in lambda_vals:
        np.random.seed(SEED)
        samples = sample_link_arrivals(n_samples, lam)
        T = 2.0 / lam

        mean, std, fid, pr = discard_oldest(n_samples, lam, tau_val, T, samples, P_GATE, P_MEAS)
        results_8protocols['discard'].append(mean)
        std_8protocols['discard'].append(std)
        fidelities_8protocols['discard'].append(fid)
        probs_8protocols['discard'].append(pr)

        mean, std, fid, pr = distill_then_swap(n_samples, lam, tau_val, T, samples, 'ASAP', 'ASAP', P_GATE, P_MEAS)
        results_8protocols['dt_aa'].append(mean)
        std_8protocols['dt_aa'].append(std)
        fidelities_8protocols['dt_aa'].append(fid)
        probs_8protocols['dt_aa'].append(pr)

        mean, std, fid, pr = distill_then_swap(n_samples, lam, tau_val, T, samples, 'ASAP', 'ALAP', P_GATE, P_MEAS)
        results_8protocols['dt_al'].append(mean)
        std_8protocols['dt_al'].append(std)
        fidelities_8protocols['dt_al'].append(fid)
        probs_8protocols['dt_al'].append(pr)

        mean, std, fid, pr = distill_then_swap(n_samples, lam, tau_val, T, samples, 'ALAP', 'ALAP', P_GATE, P_MEAS)
        results_8protocols['dt_ll'].append(mean)
        std_8protocols['dt_ll'].append(std)
        fidelities_8protocols['dt_ll'].append(fid)
        probs_8protocols['dt_ll'].append(pr)

        mean, std, fid, pr = swap_then_distill(n_samples, lam, tau_val, T, samples, 'ASAP', 'ASAP', P_GATE, P_MEAS)
        results_8protocols['st_aa'].append(mean)
        std_8protocols['st_aa'].append(std)
        fidelities_8protocols['st_aa'].append(fid)
        probs_8protocols['st_aa'].append(pr)

        mean, std, fid, pr = swap_then_distill(n_samples, lam, tau_val, T, samples, 'ASAP', 'ALAP', P_GATE, P_MEAS)
        results_8protocols['st_al'].append(mean)
        std_8protocols['st_al'].append(std)
        fidelities_8protocols['st_al'].append(fid)
        probs_8protocols['st_al'].append(pr)

        mean, std, fid, pr = swap_then_distill(n_samples, lam, tau_val, T, samples, 'ALAP', 'ALAP', P_GATE, P_MEAS)
        results_8protocols['st_ll'].append(mean)
        std_8protocols['st_ll'].append(std)
        fidelities_8protocols['st_ll'].append(fid)
        probs_8protocols['st_ll'].append(pr)

        results_4basic['dt_END'].append(distill_then_swap(n_samples, lam, tau_val, T, samples, 'ALAP', 'ALAP', P_GATE, P_MEAS)[0])
        results_4basic['dt_ASAP'].append(distill_then_swap(n_samples, lam, tau_val, T, samples, 'ASAP', 'ASAP', P_GATE, P_MEAS)[0])
        results_4basic['st_END'].append(swap_then_distill(n_samples, lam, tau_val, T, samples, 'ALAP', 'ALAP', P_GATE, P_MEAS)[0])
        results_4basic['st_ASAP'].append(swap_then_distill(n_samples, lam, tau_val, T, samples, 'ASAP', 'ASAP', P_GATE, P_MEAS)[0])

    results_by_tau[tau_name] = {**results_8protocols, **results_4basic}
    fidelities_by_tau[tau_name] = fidelities_8protocols
    success_probs_by_tau[tau_name] = probs_8protocols

tau = tau_regimes['medium']
results_8protocols = {k: results_by_tau['medium'][k] for k in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']}
results_4basic = {k: results_by_tau['medium'][k] for k in ['dt_END', 'dt_ASAP', 'st_END', 'st_ASAP']}
std_8protocols = {k: [] for k in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']}

T_vals = np.linspace(0.2, 2.0, 18)
lambda_fixed = 1.0
np.random.seed(SEED)
samples_fixed = sample_link_arrivals(n_samples, lambda_fixed)
Ic_dt_T, Ic_st_T = [], []
for T in T_vals:
    Ic_dt_T.append(distill_then_swap(n_samples, lambda_fixed, tau, T, samples_fixed, 'ALAP', 'ALAP', P_GATE, P_MEAS)[0])
    Ic_st_T.append(swap_then_distill(n_samples, lambda_fixed, tau, T, samples_fixed, 'ALAP', 'ALAP', P_GATE, P_MEAS)[0])

dist_fracs = np.linspace(0.1, 0.9, 15)
swap_fracs = np.linspace(0.1, 0.9, 15)
Ic_grid = np.zeros((len(dist_fracs), len(swap_fracs)))
F_grid = np.zeros_like(Ic_grid)
T_hm = 2.0/lambda_fixed
for i, df in enumerate(dist_fracs):
    for j, sf in enumerate(swap_fracs):
        t_dist, t_swap = df*T_hm, sf*T_hm
        Fvals = []
        for k in range(n_samples, 5000):
            l1 = sorted([samples_fixed['t_l1_1'][k], samples_fixed['t_l1_2'][k]])
            l2 = sorted([samples_fixed['t_l2_1'][k], samples_fixed['t_l2_2'][k]])
            if len([t for t in l1 if t < T_hm]) >= 2 and len([t for t in l2 if t < T_hm]) >= 2:
                F1p, _ = isotropic_purification_pairwise(raw_fidelity(l1[0], t_dist, tau), raw_fidelity(l1[1], t_dist, tau), P_GATE, P_MEAS)
                F2p, _ = isotropic_purification_pairwise(raw_fidelity(l2[0], t_dist, tau), raw_fidelity(l2[1], t_dist, tau), P_GATE, P_MEAS)
                F1 = compute_fidelity(F1p, max(t_swap-t_dist,0), tau)
                F2 = compute_fidelity(F2p, max(t_swap-t_dist,0), tau)
                Fsw = swapped_fidelity(F1, F2, P_GATE, P_MEAS)
                Fvals.append(compute_fidelity(Fsw, max(T_hm-t_swap,0), tau))
        if Fvals:
            Ic_grid[i,j] = np.mean(coherent_information_vectorized(np.array(Fvals)))
            F_grid[i,j] = np.mean(Fvals)

# ---------------------------------------------------------------------------
# Fig. 9 operating point (Allen's comment: "For instance try
# (lambda, tau, T) = (1, 100, 0.5) with 100,000 trials").
# tau_hist and T_hist are now set explicitly rather than inherited from
# tau_regimes['medium'] and 2.0/lam_hist, which gave tau=10.0 and T=2.0 and
# left only 3 and 1 positive-Ic samples in the panel.
# ---------------------------------------------------------------------------
lam_hist = 1.0
tau_hist = 100.0
T_hist = 0.5
n_samples_hist = 100000
np.random.seed(SEED)
samples_hist = sample_link_arrivals(n_samples_hist, lam_hist)
Fsw_ex, Ic_ex = swap_then_distill_distribution(n_samples_hist, lam_hist, tau_hist, T_hist, samples_hist, 'ASAP', 'ASAP', P_GATE, P_MEAS)
Fsw_discard, Ic_discard = discard_oldest_distribution(n_samples_hist, lam_hist, tau_hist, T_hist, samples_hist, P_GATE, P_MEAS)

# Diagnostic for the Fig. 9 caption and Sec. IV.B text. If the positive-Ic
# counts are still in the tens rather than the thousands, the panel is not a
# distribution and the deadline, not tau, is what needs changing.
print("\n" + "="*80)
print(f"FIG. 9 DIAGNOSTIC: lambda={lam_hist}/s, tau={tau_hist}s, T={T_hist}s, "
      f"{n_samples_hist} attempted samples")
print("="*80)
print(f"  kept outputs:  S-ASAP-D-ASAP={len(Fsw_ex)}, Discard-Swap={len(Fsw_discard)}")
print(f"  positive Ic:   S-ASAP-D-ASAP={int(np.sum(Ic_ex > 0))}, "
      f"Discard-Swap={int(np.sum(Ic_discard > 0))}")
if len(Fsw_ex) > 0:
    print(f"  S-ASAP-D-ASAP F: mean={np.mean(Fsw_ex):.4f}, std={np.std(Fsw_ex):.4f}, "
          f"min={np.min(Fsw_ex):.4f}, max={np.max(Fsw_ex):.4f}")
if len(Fsw_discard) > 0:
    print(f"  Discard-Swap  F: mean={np.mean(Fsw_discard):.4f}, std={np.std(Fsw_discard):.4f}, "
          f"min={np.min(Fsw_discard):.4f}, max={np.max(Fsw_discard):.4f}")
print("="*80)

F0_list = [0.45, 0.49, 0.51, 0.6, 0.8]
purif_threshold = {}
for F0 in F0_list:
    F = F0
    seq = [F0]
    for _ in range(10):
        F, _ = isotropic_purification_pairwise(F, F, P_GATE, P_MEAS)
        seq.append(F)
    purif_threshold[F0] = seq

def recurrence_yield(F0, n_raw=4000, rounds=5):
    arr = np.full(n_raw, F0)
    for _ in range(rounds):
        if len(arr) < 2:
            break
        idx = np.random.permutation(len(arr))
        if len(idx) % 2:
            idx = idx[:-1]
        p = idx.reshape(-1, 2)
        F_purif, _ = isotropic_purification_pairwise(arr[p[:,0]], arr[p[:,1]], P_GATE, P_MEAS)
        arr = F_purif
    return len(arr)/n_raw

F0s_yield = np.linspace(0.52, 0.95, 10)
yields = [np.mean([recurrence_yield(f) for _ in range(5)]) for f in F0s_yield]

N_list = [2, 4, 8, 16, 32]
Ic_scaling_sim, Ic_scaling_analytic = [], []
lam_example, T_example = 1.0, 20.0
for seg in N_list:
    reps = []
    for _ in range(1500):
        Fs = [0.25 + 0.75*np.exp(-2*(T_example-np.random.exponential(1/lam_example))/tau) for __ in range(seg)]
        Fsw = Fs[0]
        for x in Fs[1:]:
            Fsw = swapped_fidelity(Fsw, x, P_GATE, P_MEAS)
        reps.append(Fsw)
    Ic_scaling_sim.append(np.mean(coherent_information_vectorized(np.array(reps))))
    baseline_sample = np.random.exponential(scale=1.0/lam_example, size=200000)
    T_total = 2.0*(seg/lam_example)
    T_per_link = np.maximum(0.0, (T_total/seg)-baseline_sample[:seg])
    F_link_mean = np.mean(raw_fidelity(baseline_sample[:seg], T_per_link, tau))
    Ic_scaling_analytic.append(coherent_information_vectorized(np.array([analytic_repeated_swap(F_link_mean, seg, P_GATE, P_MEAS)]))[0])

fig3 = plt.figure(figsize=(7,5))
plt.plot(T_vals, Ic_dt_T, label="DT-END", marker='o')
plt.plot(T_vals, Ic_st_T, label="ST-END", marker='s')
plt.xlabel("T (time units)")
plt.ylabel("Weighted coherent info")
plt.legend(fontsize=14)
plt.grid()
plt.tight_layout()
plt.savefig("figures_for_paper/Ic_vs_T_both_protocols.pdf", dpi=300)
plt.show()
print("  ✓ Figure 10 saved: Ic_vs_T_both_protocols.pdf")

fig4 = plt.figure(figsize=(7,5))
plt.plot(lambda_vals, results_4basic['dt_END'], label="DT-END", marker='o')
plt.plot(lambda_vals, results_4basic['dt_ASAP'], label="DT-ASAP", marker='o', linestyle='--')
plt.plot(lambda_vals, results_4basic['st_END'], label="ST-END", marker='s')
plt.plot(lambda_vals, results_4basic['st_ASAP'], label="ST-ASAP", marker='s', linestyle='--')
plt.xlabel("λ (Rate, 1/time units)")
plt.ylabel("Weighted coherent info")
plt.grid()
plt.legend(fontsize=14)
plt.tight_layout()
plt.savefig("figures_for_paper/Ic_vs_lambda_strategy_comparison.pdf", dpi=300)
plt.show()
print("  ✓ Figure 11 saved: Ic_vs_lambda_strategy_comparison.pdf")

fig5 = plt.figure(figsize=(10,4.5))
plt.subplot(1,2,1)
plt.title("Coherent Information")
plt.contourf(swap_fracs, dist_fracs, Ic_grid, 30, cmap='viridis')
plt.colorbar(label="$I_c$")
plt.xlabel("Swap fraction")
plt.ylabel("Distill fraction")
plt.subplot(1,2,2)
plt.title("Final Fidelity")
plt.contourf(swap_fracs, dist_fracs, F_grid, 30, cmap='plasma')
plt.colorbar(label="F")
plt.xlabel("Swap fraction")
plt.ylabel("Distill fraction")
plt.tight_layout()
plt.savefig("figures_for_paper/timing_heatmaps_Ic_and_Fidelity.pdf", dpi=300)
plt.show()
print("  ✓ Figure 12 saved: timing_heatmaps_Ic_and_Fidelity.pdf")

fig6 = plt.figure(figsize=(7,5))
_edges_F = shared_bin_edges(Fsw_ex, Fsw_discard)
plt.hist(Fsw_ex, bins=_edges_F, density=True, color='skyblue', edgecolor='black', alpha=0.7, label=PROTOCOL_LABELS['st_aa'])
plt.hist(Fsw_discard, bins=_edges_F, density=True, color='lightcoral', edgecolor='black', alpha=0.5, label=PROTOCOL_LABELS['discard'])
plt.xlabel("Final Fidelity", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.title(f"Fidelity Distribution (λ={lam_hist}, τ={tau_hist}, T={T_hist:.1f})", fontsize=13, fontweight='bold')
plt.legend(fontsize=14)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures_for_paper/fidelity_histogram_example.pdf", dpi=300)
plt.show()
print("  ✓ Figure 13 saved: fidelity_histogram_example.pdf")

fig7 = plt.figure(figsize=(7,5))
Ic_ex_pos = Ic_ex[Ic_ex > 0]
Ic_discard_pos = Ic_discard[Ic_discard > 0]
_edges_I = shared_bin_edges(Ic_ex_pos, Ic_discard_pos)
if len(Ic_ex_pos) > 0:
    plt.hist(Ic_ex_pos, bins=_edges_I, density=True, color='mediumseagreen', edgecolor='black', alpha=0.7, label=f'{PROTOCOL_LABELS["st_aa"]} ({len(Ic_ex_pos)} samples)')
if len(Ic_discard_pos) > 0:
    plt.hist(Ic_discard_pos, bins=_edges_I, density=True, color='orange', edgecolor='black', alpha=0.5, label=f'{PROTOCOL_LABELS["discard"]} ({len(Ic_discard_pos)} samples)')
plt.xlabel("Coherent Information", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.title(f"Coherent Information Distribution (Ic > 0)\n(λ={lam_hist}, τ={tau_hist}, T={T_hist:.1f})", fontsize=13, fontweight='bold')
plt.legend(fontsize=14)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures_for_paper/coherent_info_histogram_example.pdf", dpi=300)
plt.show()
print("  ✓ Figure 14 saved: coherent_info_histogram_example.pdf")

fig8 = plt.figure(figsize=(6,4))
for F0 in F0_list:
    plt.plot(purif_threshold[F0], label=f"$F_0$={F0:.2f}", marker='o')
plt.axhline(0.5, color='k', ls='--', label='Threshold')
plt.legend(fontsize=14)
plt.xlabel("Iteration")
plt.ylabel("Fidelity")
plt.title("Purification Threshold Behavior")
plt.grid()
plt.tight_layout()
plt.savefig("figures_for_paper/fig_purification_threshold.pdf", dpi=300)
plt.show()
print("  ✓ Figure 15 saved: fig_purification_threshold.pdf")

fig9 = plt.figure(figsize=(6,4))
plt.plot(F0s_yield, yields, marker='o', color='green')
plt.xlabel("Initial Fidelity $F_0$")
plt.ylabel("Yield")
plt.title("Recurrence Purification Yield")
plt.grid()
plt.tight_layout()
plt.savefig("figures_for_paper/fig_recurrence_yield.pdf", dpi=300)
plt.show()
print("  ✓ Figure 16 saved: fig_recurrence_yield.pdf")

fig10 = plt.figure(figsize=(6,4))
plt.plot(N_list, Ic_scaling_sim, marker='o', label='Simulation')
plt.plot(N_list, Ic_scaling_analytic, marker='s', linestyle='--', label='Analytic')
plt.xscale('log', base=2)
plt.xlabel("Segments N")
plt.ylabel("Weighted coherent info")
plt.title("Repeater Scaling")
plt.grid(which='both', ls='--')
plt.legend(fontsize=14)
plt.tight_layout()
plt.savefig("figures_for_paper/fig_repeater_scaling.pdf", dpi=300)
plt.show()
print("  ✓ Figure 17 saved: fig_repeater_scaling.pdf")

fig11 = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, results_8protocols['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color='black', markersize=7)
plt.plot(lambda_vals, results_8protocols['dt_aa'], label=PROTOCOL_LABELS['dt_aa'], marker='o', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['dt_al'], label=PROTOCOL_LABELS['dt_al'], marker='s', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['dt_ll'], label=PROTOCOL_LABELS['dt_ll'], marker='^', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['st_aa'], label=PROTOCOL_LABELS['st_aa'], marker='v', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['st_al'], label=PROTOCOL_LABELS['st_al'], marker='<', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['st_ll'], label=PROTOCOL_LABELS['st_ll'], marker='>', linewidth=2, alpha=0.7)
plt.title("Seven Protocol Comparison", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Weighted coherent info", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', ncol=2, fontsize=14)
plt.tight_layout()
plt.savefig("figures_for_paper/all_protocols_comparison.pdf", dpi=300)
plt.show()
print("  ✓ Figure 18 saved: all_protocols_comparison.pdf")

fig_pr_lambda = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, success_probs_by_tau['medium']['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color='black', markersize=7)
plt.plot(lambda_vals, success_probs_by_tau['medium']['dt_aa'], label=PROTOCOL_LABELS['dt_aa'], marker='o', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_tau['medium']['dt_al'], label=PROTOCOL_LABELS['dt_al'], marker='s', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_tau['medium']['dt_ll'], label=PROTOCOL_LABELS['dt_ll'], marker='^', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_tau['medium']['st_aa'], label=PROTOCOL_LABELS['st_aa'], marker='v', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_tau['medium']['st_al'], label=PROTOCOL_LABELS['st_al'], marker='<', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_tau['medium']['st_ll'], label=PROTOCOL_LABELS['st_ll'], marker='>', linewidth=2, alpha=0.7)
plt.title("Success Probability vs λ", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Success probability", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', ncol=2, fontsize=14)
plt.tight_layout()
plt.savefig("figures_for_paper/success_prob_vs_lambda.pdf", dpi=300)
plt.show()
print("  ✓ Figure 19 saved: success_prob_vs_lambda.pdf")

df_8protocols = pd.DataFrame({
    'lambda': lambda_vals,
    'Discard-Oldest_mean': results_8protocols['discard'],
    'D-ASAP-S-ASAP_mean': results_8protocols['dt_aa'],
    'D-ASAP-S-ALAP_mean': results_8protocols['dt_al'],
    'D-ALAP-S-ALAP_mean': results_8protocols['dt_ll'],
    'S-ASAP-D-ASAP_mean': results_8protocols['st_aa'],
    'S-ASAP-D-ALAP_mean': results_8protocols['st_al'],
    'S-ALAP-D-ALAP_mean': results_8protocols['st_ll']
})
df_8protocols['Data_Section'] = 'All_Protocols'
df_8protocols['p_gate'] = P_GATE
df_8protocols['p_meas'] = P_MEAS
all_dataframes.append(df_8protocols)

df_regimes = pd.DataFrame({
    'lambda': lambda_vals,
    **{f'{tau_name}_discard_Ic': results_by_tau[tau_name]['discard'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_discard_F': fidelities_by_tau[tau_name]['discard'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_discard_Pr': success_probs_by_tau[tau_name]['discard'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_st_aa_Ic': results_by_tau[tau_name]['st_aa'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_st_aa_F': fidelities_by_tau[tau_name]['st_aa'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_st_aa_Pr': success_probs_by_tau[tau_name]['st_aa'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_dt_ll_Ic': results_by_tau[tau_name]['dt_ll'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_dt_ll_F': fidelities_by_tau[tau_name]['dt_ll'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_dt_ll_Pr': success_probs_by_tau[tau_name]['dt_ll'] for tau_name in tau_regimes.keys()},
})
df_regimes['Data_Section'] = 'Parameter_Regimes'
df_regimes['p_gate'] = P_GATE
df_regimes['p_meas'] = P_MEAS
all_dataframes.append(df_regimes)

stats_summary = {
    PROTOCOL_LABELS['discard']: {'mean': np.mean(results_8protocols['discard']), 'std': np.std(results_8protocols['discard']), 'max': np.max(results_8protocols['discard']), 'min': np.min(results_8protocols['discard'])},
    PROTOCOL_LABELS['dt_aa']: {'mean': np.mean(results_8protocols['dt_aa']), 'std': np.std(results_8protocols['dt_aa']), 'max': np.max(results_8protocols['dt_aa']), 'min': np.min(results_8protocols['dt_aa'])},
    PROTOCOL_LABELS['dt_al']: {'mean': np.mean(results_8protocols['dt_al']), 'std': np.std(results_8protocols['dt_al']), 'max': np.max(results_8protocols['dt_al']), 'min': np.min(results_8protocols['dt_al'])},
    PROTOCOL_LABELS['dt_ll']: {'mean': np.mean(results_8protocols['dt_ll']), 'std': np.std(results_8protocols['dt_ll']), 'max': np.max(results_8protocols['dt_ll']), 'min': np.min(results_8protocols['dt_ll'])},
    PROTOCOL_LABELS['st_aa']: {'mean': np.mean(results_8protocols['st_aa']), 'std': np.std(results_8protocols['st_aa']), 'max': np.max(results_8protocols['st_aa']), 'min': np.min(results_8protocols['st_aa'])},
    PROTOCOL_LABELS['st_al']: {'mean': np.mean(results_8protocols['st_al']), 'std': np.std(results_8protocols['st_al']), 'max': np.max(results_8protocols['st_al']), 'min': np.min(results_8protocols['st_al'])},
    PROTOCOL_LABELS['st_ll']: {'mean': np.mean(results_8protocols['st_ll']), 'std': np.std(results_8protocols['st_ll']), 'max': np.max(results_8protocols['st_ll']), 'min': np.min(results_8protocols['st_ll'])}
}

df_stats = pd.DataFrame(stats_summary).T
df_stats['Protocol'] = df_stats.index
df_stats['Data_Section'] = 'Protocol_Statistics'
df_stats['p_gate'] = P_GATE
df_stats['p_meas'] = P_MEAS
all_dataframes.append(df_stats.reset_index(drop=True))

temporal_stats = {
    'DT-END': {'mean': np.mean(Ic_dt_T), 'std': np.std(Ic_dt_T), 'max': np.max(Ic_dt_T), 'min': np.min(Ic_dt_T)},
    'ST-END': {'mean': np.mean(Ic_st_T), 'std': np.std(Ic_st_T), 'max': np.max(Ic_st_T), 'min': np.min(Ic_st_T)}
}
df_temporal = pd.DataFrame(temporal_stats).T
df_temporal['Protocol'] = df_temporal.index
df_temporal['Data_Section'] = 'Temporal_Analysis'
df_temporal['p_gate'] = P_GATE
df_temporal['p_meas'] = P_MEAS
all_dataframes.append(df_temporal.reset_index(drop=True))

fidelity_stats = {
    'Fsw_mean': np.mean(Fsw_ex), 'Fsw_std': np.std(Fsw_ex), 'Fsw_min': np.min(Fsw_ex), 'Fsw_max': np.max(Fsw_ex),
    'Ic_mean': np.mean(Ic_ex), 'Ic_std': np.std(Ic_ex), 'Ic_min': np.min(Ic_ex), 'Ic_max': np.max(Ic_ex)
}
df_fidelity = pd.DataFrame([fidelity_stats])
df_fidelity['Data_Section'] = 'Fidelity_Distribution'
df_fidelity['p_gate'] = P_GATE
df_fidelity['p_meas'] = P_MEAS
all_dataframes.append(df_fidelity)

timing_stats = {
    'optimal_distill_frac': dist_fracs[np.unravel_index(Ic_grid.argmax(), Ic_grid.shape)[0]],
    'optimal_swap_frac': swap_fracs[np.unravel_index(Ic_grid.argmax(), Ic_grid.shape)[1]],
    'max_Ic_timing': np.max(Ic_grid),
    'max_F_timing': np.max(F_grid),
    'mean_Ic_timing': np.mean(Ic_grid[Ic_grid > 0]),
    'mean_F_timing': np.mean(F_grid[F_grid > 0])
}
df_timing = pd.DataFrame([timing_stats])
df_timing['Data_Section'] = 'Timing_Optimization'
df_timing['p_gate'] = P_GATE
df_timing['p_meas'] = P_MEAS
all_dataframes.append(df_timing)

best_protocol = max(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
worst_protocol = min(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
improvement_vs_discard = ((stats_summary[best_protocol]['mean'] - stats_summary[PROTOCOL_LABELS['discard']]['mean']) / stats_summary[PROTOCOL_LABELS['discard']]['mean'] * 100) if stats_summary[PROTOCOL_LABELS['discard']]['mean'] != 0 else float('inf')

comparison_metrics = {
    'best_protocol': best_protocol,
    'best_mean_Ic': stats_summary[best_protocol]['mean'],
    'best_max_Ic': stats_summary[best_protocol]['max'],
    'worst_protocol': worst_protocol,
    'worst_mean_Ic': stats_summary[worst_protocol]['mean'],
    'improvement_vs_discard_pct': improvement_vs_discard,
    'discard_mean': stats_summary[PROTOCOL_LABELS['discard']]['mean'],
    'dt_end_mean_temporal': temporal_stats['DT-END']['mean'],
    'st_end_mean_temporal': temporal_stats['ST-END']['mean'],
    'dt_end_max_temporal': temporal_stats['DT-END']['max'],
    'st_end_max_temporal': temporal_stats['ST-END']['max'],
    'temporal_improvement_pct': ((temporal_stats['ST-END']['mean'] - temporal_stats['DT-END']['mean']) / temporal_stats['DT-END']['mean'] * 100) if temporal_stats['DT-END']['mean'] != 0 else float('inf')
}
df_comparison = pd.DataFrame([comparison_metrics])
df_comparison['Data_Section'] = 'Key_Comparisons'
df_comparison['p_gate'] = P_GATE
df_comparison['p_meas'] = P_MEAS
all_dataframes.append(df_comparison)

df_combined = pd.concat(all_dataframes, ignore_index=True, sort=False)
df_combined.to_csv("figures_for_paper/double_link_combined_data.csv", index=False)

print("\n" + "="*80)
print("FIGURE GENERATION COMPLETE")
print("="*80)
print(f"\nAll figures saved to: figures_for_paper/")
print(f"\nPhysical parameter figures (9 total — one per lambda × metric):")
for lam in lambda_vals_physical:
    lam_str = str(int(lam)) if lam == int(lam) else str(lam)
    for _, _, metric_fname in metric_cfg:
        print(f"  lam{lam_str}_{metric_fname}_vs_T.pdf")
print("\nAdditional figures:")
print("  10. Ic_vs_T_both_protocols.pdf")
print("  11. Ic_vs_lambda_strategy_comparison.pdf")
print("  12. timing_heatmaps_Ic_and_Fidelity.pdf")
print("  13. fidelity_histogram_example.pdf")
print("  14. coherent_info_histogram_example.pdf")
print("  15. fig_purification_threshold.pdf")
print("  16. fig_recurrence_yield.pdf")
print("  17. fig_repeater_scaling.pdf")
print("  18. all_protocols_comparison.pdf")
print("  19. success_prob_vs_lambda.pdf")
print("\n" + "="*80)
print("PARAMETER REGIME COMPARISON")
print("="*80)
for tau_name, tau_val in tau_regimes.items():
    print(f"\nτ = {tau_val} ({tau_name}):")
    print(f"  Best protocol (Ic): {max(['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll'], key=lambda p: np.mean(results_by_tau[tau_name][p]))}")
    print(f"  Mean fidelity range: [{np.min([np.mean(fidelities_by_tau[tau_name][p]) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]):.4f}, {np.max([np.mean(fidelities_by_tau[tau_name][p]) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]):.4f}]")
    print(f"  Mean success prob range: [{np.min([np.mean(success_probs_by_tau[tau_name][p]) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]):.4f}, {np.max([np.mean(success_probs_by_tau[tau_name][p]) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]):.4f}]")
print("\n" + "="*80)
print("KEY STATISTICS SUMMARY (τ = {})".format(tau))
print("="*80)
print(f"\nBest Protocol: {best_protocol}")
print(f"  Mean Ic: {stats_summary[best_protocol]['mean']:.6f}")
print(f"  Std Dev: {stats_summary[best_protocol]['std']:.6f}")
print(f"  Max Ic: {stats_summary[best_protocol]['max']:.6f}")
print(f"  Min Ic: {stats_summary[best_protocol]['min']:.6f}")
print(f"\nWorst Protocol: {worst_protocol}")
print(f"  Mean Ic: {stats_summary[worst_protocol]['mean']:.6f}")
print(f"\n{PROTOCOL_LABELS['discard']} Baseline:")
print(f"  Mean Ic: {stats_summary[PROTOCOL_LABELS['discard']]['mean']:.6f}")
print(f"  Mean Fidelity: {np.mean(fidelities_by_tau['medium']['discard']):.6f}")
print(f"  Mean Success Prob: {np.mean(success_probs_by_tau['medium']['discard']):.6f}")
print(f"\nPerformance Improvement:")
print(f"  Best vs Discard-Oldest: {improvement_vs_discard:+.2f}%")
print(f"\nTemporal Analysis (DT-END vs ST-END):")
print(f"  DT-END Mean: {temporal_stats['DT-END']['mean']:.6f} (Max: {temporal_stats['DT-END']['max']:.6f})")
print(f"  ST-END Mean: {temporal_stats['ST-END']['mean']:.6f} (Max: {temporal_stats['ST-END']['max']:.6f})")
print(f"  ST-END improvement: {comparison_metrics['temporal_improvement_pct']:+.2f}%")
print(f"\nTiming Optimization:")
print(f"  Optimal Distill Fraction: {timing_stats['optimal_distill_frac']:.3f}")
print(f"  Optimal Swap Fraction: {timing_stats['optimal_swap_frac']:.3f}")
print(f"  Max Ic at Optimal Timing: {timing_stats['max_Ic_timing']:.6f}")
print(f"\nFidelity Distribution Statistics:")
print(f"  Mean Fidelity: {fidelity_stats['Fsw_mean']:.4f} ± {fidelity_stats['Fsw_std']:.4f}")
print(f"  Range: [{fidelity_stats['Fsw_min']:.4f}, {fidelity_stats['Fsw_max']:.4f}]")
print(f"  Mean Ic: {fidelity_stats['Ic_mean']:.4f} ± {fidelity_stats['Ic_std']:.4f}")
print("\n" + "="*80)
print("ALL 7 PROTOCOLS PERFORMANCE TABLE")
print("="*80)
print(f"{'Protocol':<20} {'Mean Ic':>12} {'Std Dev':>12} {'Max Ic':>12} {'Min Ic':>12}")
print("-"*80)
for protocol in [PROTOCOL_LABELS[k] for k in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]:
    s = stats_summary[protocol]
    print(f"{protocol:<20} {s['mean']:>12.6f} {s['std']:>12.6f} {s['max']:>12.6f} {s['min']:>12.6f}")
print("="*80)
print("\nAll data saved to single CSV file:")
print("  - figures_for_paper/double_link_combined_data.csv")
print("    Contains sections: Physical_Params (9 regimes), All_Protocols,")
print("    Parameter_Regimes, Protocol_Statistics, Temporal_Analysis,")
print("    Fidelity_Distribution, Timing_Optimization, Key_Comparisons")
print("="*80)
print("\n" + "="*80)
print("OPERATION ERROR PARAMETERS USED")
print("="*80)
print(f"p_gate = {P_GATE}")
print(f"p_meas = {P_MEAS}")
if P_GATE == 1.0 and P_MEAS == 1.0:
    print("\n Perfect operations - Results identical to original code")
    print("  To test imperfect operations (paper's condition):")
    print("  Change P_GATE = 0.9 and P_MEAS = 0.9 at line ~476")
elif P_GATE == 0.9 and P_MEAS == 0.9:
    print("\n Imperfect operations - Paper's condition")
    print("  This should show the observation from the paper:")
    print("  Per-memory rate decreases with more memories")
print("="*80)

print("\n" + "="*80)
print("MERGING ALL PDFs INTO COMBINED DOCUMENT")
print("="*80)

from pypdf import PdfWriter, PdfReader

# Ordered list of all PDF figures generated above
pdf_files_to_merge = []

# 9 physical parameter figures (lambda x metric order)
for lam in lambda_vals_physical:
    lam_str = str(int(lam)) if lam == int(lam) else str(lam)
    for _, _, metric_fname in metric_cfg:
        pdf_files_to_merge.append(f"figures_for_paper/lam{lam_str}_{metric_fname}_vs_T.pdf")

# Remaining figures
pdf_files_to_merge += [
    "figures_for_paper/Ic_vs_T_both_protocols.pdf",
    "figures_for_paper/Ic_vs_lambda_strategy_comparison.pdf",
    "figures_for_paper/timing_heatmaps_Ic_and_Fidelity.pdf",
    "figures_for_paper/fidelity_histogram_example.pdf",
    "figures_for_paper/coherent_info_histogram_example.pdf",
    "figures_for_paper/fig_purification_threshold.pdf",
    "figures_for_paper/fig_recurrence_yield.pdf",
    "figures_for_paper/fig_repeater_scaling.pdf",
    "figures_for_paper/all_protocols_comparison.pdf",
    "figures_for_paper/success_prob_vs_lambda.pdf",
]

combined_pdf_path = "figures_for_paper/all_figures_combined.pdf"

writer = PdfWriter()
for pdf_path in pdf_files_to_merge:
    reader = PdfReader(pdf_path)
    for page in reader.pages:
        writer.add_page(page)

with open(combined_pdf_path, "wb") as output_file:
    writer.write(output_file)

print(f"\nCombined PDF saved to: {combined_pdf_path}")
print(f"Total pages merged: {sum(len(PdfReader(p).pages) for p in pdf_files_to_merge)}")
print("="*80)

# Single Link Version Below

# Version with variables in one place to edit F_init and error rate(s)

# Version replacing c with tau for single-link figure generation

# @title
# Single link code with operation errors in purification
# Modified to include p_gate and p_meas parameters (Paper Eq. 8, 9)

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

plt.rcParams.update({
    'font.size': 13,
    'axes.labelsize': 16,
    'axes.titlesize': 17,
    'xtick.labelsize': 13,
    'ytick.labelsize': 13,
    'legend.fontsize': 12,
    'figure.titlesize': 18,
    'lines.linewidth': 2.4,
    'lines.markersize': 7
})

PROTOCOL_COLORS = {
    'discard': 'black',
    'asap': '#1f77b4',
    'alap': '#ff7f0e',
}

PROTOCOL_LABELS = {
    'discard': 'Discard-Oldest',
    'asap': 'Distill-ASAP',
    'alap': 'Distill-ALAP',
}

os.makedirs("figures_single_link", exist_ok=True)

SEED = 42
np.random.seed(SEED)
n_samples = 5000

F_INIT = 0.90
P_GATE = 1.00
P_MEAS = 1.00

lambda_vals_physical = [10.0, 1e4]
tau_vals_physical = [0.1, 1.0, 100.0]

all_dataframes = []

def raw_fidelity(t_gen, t_total, tau):
    A = 1/4
    B = F_INIT - A
    return np.clip(A + B * np.exp(-2 * (t_total - t_gen) / tau), 0, 1)

def compute_fidelity(F_init, t_idle, tau):
    A = 1/4
    B = F_init - A
    return np.clip(A + B * np.exp(-2 * t_idle / tau), 0, 1)

def isotropic_purification_pairwise(F1, F2, p_gate=1.0, p_meas=1.0):
    """
    Entanglement purification with optional operation errors (Werner states).
    Returns (F_out, p_success) tuple.
    When p_gate=1.0, p_meas=1.0: uses original formula
    When imperfect: uses Paper Equations (8) and (9)
    """
    e1 = (1 - F1) / 3
    e2 = (1 - F2) / 3

    if p_gate == 1.0 and p_meas == 1.0:
        num = F1 * F2 + (1/9) * (1 - F1) * (1 - F2)
        denom = (F1 * F2 + (1/3) * F1 * (1 - F2) + (1/3) * F2 * (1 - F1) +
                 (5/9) * (1 - F1) * (1 - F2))
        F_out = np.clip(num / denom, 0, 1)
        p_success = denom
    else:
        eta = p_meas
        p = p_gate

        p_success = (p**2 * (eta**2 + (1 - eta)**2) *
                     (F1*F2 + F1*e2 + e1*F2 + 5*e1*e2) +
                     2 * p**2 * eta * (1 - eta) *
                     (2*F1*e2 + 2*e1*F2 + 4*e1*e2) +
                     (1 - p**2) / 2)

        numerator = ((eta**2 + (1 - eta)**2) * (F1*F2 + e1*e2) +
                     2 * eta * (1 - eta) * (F1*e2 + e1*e2) +
                     (1 - p**2) / (8 * p**2))

        denominator = ((eta**2 + (1 - eta)**2) *
                       (F1*F2 + F1*e2 + e1*F2 + 5*e1*e2) +
                       2 * eta * (1 - eta) *
                       (2*F1*e2 + 2*e1*F2 + 4*e1*e2) +
                       (1 - p**2) / (2 * p**2))

        F_out = np.clip(numerator / denominator, 0, 1)

    return F_out, p_success

def shared_bin_edges(*datasets, bins=60):
    pooled = np.concatenate([np.asarray(d).ravel() for d in datasets
                             if np.asarray(d).size > 0])
    if pooled.size == 0:
        return np.linspace(0.0, 1.0, bins + 1)
    lo, hi = float(pooled.min()), float(pooled.max())
    if hi <= lo:
        hi = lo + 1e-9
    return np.linspace(lo, hi, bins + 1)


def coherent_information_vectorized(F):
    λ1 = F
    λ_rest = (1 - F) / 3
    eigs = np.stack([λ1, λ_rest, λ_rest, λ_rest], axis=-1)
    S = -np.sum(eigs * np.log2(eigs + 1e-12), axis=-1)
    return np.maximum(0, 1 - S)

def generate_poisson_arrivals(lam, T, n_samples):
    X = np.random.exponential(1/lam, n_samples)
    X[X > T] = np.inf
    return X

def single_link_discard_oldest(n_samples, lam, tau, T, samples, p_gate=1.0, p_meas=1.0):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)

    for i in range(n_samples):
        available = [t for t in [t1a[i], t2a[i]] if t < T]
        if len(available) > 0:
            F_final[i] = raw_fidelity(max(available), T, tau)
            used[i] = True

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate
    std_Ic = 0.0

    return mean_Ic, std_Ic, F_mean, success_rate

def single_link_distill_asap(n_samples, lam, tau, T, samples, p_gate=1.0, p_meas=1.0):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)
    p_success_all = np.ones(n_samples)

    for i in range(n_samples):
        if t1a[i] < T and t2a[i] < T:
            t_dist = max(t1a[i], t2a[i])
            F1 = raw_fidelity(t1a[i], t_dist, tau)
            F2 = raw_fidelity(t2a[i], t_dist, tau)
            F_pur, p_succ = isotropic_purification_pairwise(F1, F2, p_gate, p_meas)
            F_final[i] = compute_fidelity(F_pur, T - t_dist, tau)
            used[i] = True
            p_success_all[i] = p_succ
        elif t1a[i] < T:
            F_final[i] = raw_fidelity(t1a[i], T, tau)
            used[i] = True
        elif t2a[i] < T:
            F_final[i] = raw_fidelity(t2a[i], T, tau)
            used[i] = True

    # NOTE (correction): F_mean must be the fidelity conditioned on actual
    # protocol success, i.e. weighted by each realization's purification
    # success probability p_success_all[i] (which is 1.0 for the single-arrival
    # cases and equal to the CNOT-distillation success probability for the
    # two-arrival cases). The original code used a plain unweighted mean over
    # "used" realizations, then separately multiplied Ic by mean(p_success),
    # which biases F_mean toward realizations with low p_success just as much
    # as those with high p_success, even though low-p_success realizations
    # contribute less to the actual (weighted) ensemble of successful outcomes.
    F_mean = (np.sum(p_success_all[used] * F_final[used]) / np.sum(p_success_all[used])
              if np.sum(used) > 0 else 0.0)
    p_success_mean = np.mean(p_success_all[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate * p_success_mean
    std_Ic = 0.0

    return mean_Ic, std_Ic, F_mean, success_rate

def single_link_distill_alap(n_samples, lam, tau, T, samples, p_gate=1.0, p_meas=1.0):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)
    p_success_all = np.ones(n_samples)

    for i in range(n_samples):
        if t1a[i] < T and t2a[i] < T:
            F1 = raw_fidelity(t1a[i], T, tau)
            F2 = raw_fidelity(t2a[i], T, tau)
            F_final[i], p_succ = isotropic_purification_pairwise(F1, F2, p_gate, p_meas)
            used[i] = True
            p_success_all[i] = p_succ
        elif t1a[i] < T:
            F_final[i] = raw_fidelity(t1a[i], T, tau)
            used[i] = True
        elif t2a[i] < T:
            F_final[i] = raw_fidelity(t2a[i], T, tau)
            used[i] = True

    # NOTE (correction): same weighted-mean fix as single_link_distill_asap above.
    F_mean = (np.sum(p_success_all[used] * F_final[used]) / np.sum(p_success_all[used])
              if np.sum(used) > 0 else 0.0)
    p_success_mean = np.mean(p_success_all[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate * p_success_mean
    std_Ic = 0.0

    return mean_Ic, std_Ic, F_mean, success_rate

print("\n" + "="*80)
print("SINGLE-LINK QUANTUM REPEATER SIMULATION")
print("="*80)
print(f"Operation parameters: p_gate = {P_GATE}, p_meas = {P_MEAS}")
if P_GATE == 1.0 and P_MEAS == 1.0:
    print("  → PERFECT OPERATIONS (reproduces original code)")
elif P_GATE == 0.9 and P_MEAS == 0.9:
    print("  → IMPERFECT OPERATIONS (paper's condition)")
else:
    print(f"  → CUSTOM OPERATION QUALITY")
print("="*80)

print("\n" + "="*80)
print("COMPUTING PHYSICAL PARAMETER REGIMES")
print("="*80)

results_physical = {}
for lam in lambda_vals_physical:
    for tau in tau_vals_physical:
        key = f"lam{lam}_tau{tau}"
        print(f"\nProcessing λ={lam}/s, τ={tau}s...")

        T_min = 0.01 * tau
        T_max = 0.2 * tau
        T_vals = np.linspace(T_min, T_max, 30)

        results = {
            'T': T_vals,
            'discard_Ic': [], 'discard_F': [], 'discard_Pr': [],
            'asap_Ic': [], 'asap_F': [], 'asap_Pr': [],
            'alap_Ic': [], 'alap_F': [], 'alap_Pr': [],
        }

        for T in T_vals:
            np.random.seed(SEED)
            samples = {
                't_l1_1': generate_poisson_arrivals(lam, T, n_samples),
                't_l2_1': generate_poisson_arrivals(lam, T, n_samples)
            }

            mean_Ic, _, F_mean, Pr = single_link_discard_oldest(n_samples, lam, tau, T, samples, P_GATE, P_MEAS)
            results['discard_Ic'].append(mean_Ic)
            results['discard_F'].append(F_mean)
            results['discard_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = single_link_distill_asap(n_samples, lam, tau, T, samples, P_GATE, P_MEAS)
            results['asap_Ic'].append(mean_Ic)
            results['asap_F'].append(F_mean)
            results['asap_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = single_link_distill_alap(n_samples, lam, tau, T, samples, P_GATE, P_MEAS)
            results['alap_Ic'].append(mean_Ic)
            results['alap_F'].append(F_mean)
            results['alap_Pr'].append(Pr)

        results_physical[key] = results

        df = pd.DataFrame(results)
        df['Data_Section'] = f'Physical_Params_{key}'
        parts = key.replace('lam', '').split('_tau')
        df['lambda'] = float(parts[0])
        df['tau'] = float(parts[1])
        df['p_gate'] = P_GATE
        df['p_meas'] = P_MEAS
        all_dataframes.append(df)

print("\n" + "="*80)
print("PARAMETER REGIME DIAGNOSTICS")
print("="*80)

for lam in lambda_vals_physical:
    for tau in tau_vals_physical:
        key = f"lam{lam}_tau{tau}"

        expected_gen_time = 1.0 / lam
        T_max = 0.2 * tau
        ratio = T_max / expected_gen_time

        max_Ic = max([np.max(results_physical[key][f'{p}_Ic']) for p in ['discard', 'asap', 'alap']])

        if ratio < 0.5:
            status = "FAILED"
            reason = f"T_max ({T_max:.4f}s) much less than gen time ({expected_gen_time:.4f}s)"
        elif ratio < 1.0:
            status = "MARGINAL"
            reason = f"T_max ({T_max:.4f}s) less than gen time ({expected_gen_time:.4f}s)"
        elif max_Ic < 0.1:
            status = "LOW Ic"
            reason = f"T_max adequate but high decoherence"
        else:
            status = "GOOD"
            reason = f"T_max ({T_max:.4f}s) greater than gen time ({expected_gen_time:.4f}s)"

        print(f"\n{key}: {status}")
        print(f"  Expected generation time: {expected_gen_time:.6f}s")
        print(f"  T_max (coherence time): {T_max:.6f}s")
        print(f"  Ratio (T_max/gen_time): {ratio:.3f}")
        print(f"  Max coherent info: {max_Ic:.6f}")
        print(f"  Reason: {reason}")

print("\n" + "="*80)
print("SUMMARY")
print("="*80)

good_regimes = []
marginal_regimes = []
failed_regimes = []

for lam in lambda_vals_physical:
    for tau in tau_vals_physical:
        key = f"lam{lam}_tau{tau}"
        expected_gen_time = 1.0 / lam
        T_max = 0.2 * tau
        ratio = T_max / expected_gen_time
        max_Ic = max([np.max(results_physical[key][f'{p}_Ic']) for p in ['discard', 'asap', 'alap']])

        if ratio >= 1.0 and max_Ic >= 0.1:
            good_regimes.append(key)
        elif ratio < 0.5:
            failed_regimes.append(key)
        else:
            marginal_regimes.append(key)

print(f"\nGOOD regimes ({len(good_regimes)}): {', '.join(good_regimes)}")
print(f"MARGINAL regimes ({len(marginal_regimes)}): {', '.join(marginal_regimes)}")
print(f"FAILED regimes ({len(failed_regimes)}): {', '.join(failed_regimes)}")

print("\n" + "="*80)

print("\n" + "="*80)
print("GENERATING FIGURES WITH PHYSICAL PARAMETERS")
print("="*80)

fig1 = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, tau in enumerate(tau_vals_physical):
        key = f"lam{lam}_tau{tau}"
        res = results_physical[key]

        plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_Ic'], label=PROTOCOL_LABELS['discard'],
                marker='D', color=PROTOCOL_COLORS['discard'], markersize=5)
        plt.plot(res['T'], res['asap_Ic'], label=PROTOCOL_LABELS['asap'],
                marker='o', color=PROTOCOL_COLORS['asap'], alpha=0.7)
        plt.plot(res['T'], res['alap_Ic'], label=PROTOCOL_LABELS['alap'],
                marker='s', color=PROTOCOL_COLORS['alap'], alpha=0.7)

        plt.title(f"λ={lam}/s, τ={tau}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Coherent Information")
        plt.grid(alpha=0.3)
        plt.legend(fontsize=9)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_single_link/physical_params_coherent_info_vs_T.pdf", dpi=300)
plt.show()

fig2 = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, tau in enumerate(tau_vals_physical):
        key = f"lam{lam}_tau{tau}"
        res = results_physical[key]

        plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_F'], label=PROTOCOL_LABELS['discard'],
                marker='D', color=PROTOCOL_COLORS['discard'], markersize=5)
        plt.plot(res['T'], res['asap_F'], label=PROTOCOL_LABELS['asap'],
                marker='o', color=PROTOCOL_COLORS['asap'], alpha=0.7)
        plt.plot(res['T'], res['alap_F'], label=PROTOCOL_LABELS['alap'],
                marker='s', color=PROTOCOL_COLORS['alap'], alpha=0.7)

        plt.title(f"λ={lam}/s, τ={tau}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Final Fidelity")
        plt.grid(alpha=0.3)
        plt.legend(fontsize=9)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_single_link/physical_params_fidelity_vs_T.pdf", dpi=300)
plt.show()

fig_pr = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, tau in enumerate(tau_vals_physical):
        key = f"lam{lam}_tau{tau}"
        res = results_physical[key]

        plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_Pr'], label=PROTOCOL_LABELS['discard'],
                marker='D', color=PROTOCOL_COLORS['discard'], markersize=5)
        plt.plot(res['T'], res['asap_Pr'], label=PROTOCOL_LABELS['asap'],
                marker='o', color=PROTOCOL_COLORS['asap'], alpha=0.7)
        plt.plot(res['T'], res['alap_Pr'], label=PROTOCOL_LABELS['alap'],
                marker='s', color=PROTOCOL_COLORS['alap'], alpha=0.7)

        plt.title(f"λ={lam}/s, τ={tau}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Pr(success)")
        plt.grid(alpha=0.3)
        plt.legend(fontsize=9)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_single_link/physical_params_success_prob_vs_T.pdf", dpi=300)
plt.show()

print("\n" + "="*80)
print("SUMMARY OF PHYSICAL PARAMETER REGIMES")
print("="*80)
for key, res in results_physical.items():
    print(f"\n{key}:")
    for protocol in ['discard', 'asap', 'alap']:
        max_Ic = np.max(res[f'{protocol}_Ic'])
        max_F = np.max(res[f'{protocol}_F'])
        mean_Ic = np.mean(res[f'{protocol}_Ic'])
        mean_Pr = np.mean(res[f'{protocol}_Pr'])
        print(f"  {PROTOCOL_LABELS[protocol]}: Max Ic={max_Ic:.6f}, Max F={max_F:.6f}, Mean Ic={mean_Ic:.6f}, Mean Pr={mean_Pr:.6f}")

print("\n" + "="*80)
print("GENERATING ADDITIONAL FIGURES")
print("="*80)

lambda_vals = np.linspace(0.1, 2.0, 20)
tau_regimes = {'small': 0.5, 'medium': 10.0, 'large': 50.0}

results_by_tau = {}
fidelities_by_tau = {}
success_rates_by_tau = {}

for tau_name, tau_val in tau_regimes.items():
    print(f"\nProcessing τ = {tau_val} ({tau_name})...")
    results = {'discard': [], 'asap': [], 'alap': []}
    fidelities = {'discard': [], 'asap': [], 'alap': []}
    success_rates = {'discard': [], 'asap': [], 'alap': []}
    std_vals = {'discard': [], 'asap': [], 'alap': []}

    for lam in lambda_vals:
        np.random.seed(SEED)
        T = 2.0 / lam

        samples = {
            't_l1_1': generate_poisson_arrivals(lam, T, n_samples),
            't_l2_1': generate_poisson_arrivals(lam, T, n_samples)
        }

        mean, std, fid, succ = single_link_discard_oldest(n_samples, lam, tau_val, T, samples, P_GATE, P_MEAS)
        results['discard'].append(mean)
        std_vals['discard'].append(std)
        fidelities['discard'].append(fid)
        success_rates['discard'].append(succ)

        mean, std, fid, succ = single_link_distill_asap(n_samples, lam, tau_val, T, samples, P_GATE, P_MEAS)
        results['asap'].append(mean)
        std_vals['asap'].append(std)
        fidelities['asap'].append(fid)
        success_rates['asap'].append(succ)

        mean, std, fid, succ = single_link_distill_alap(n_samples, lam, tau_val, T, samples, P_GATE, P_MEAS)
        results['alap'].append(mean)
        std_vals['alap'].append(std)
        fidelities['alap'].append(fid)
        success_rates['alap'].append(succ)

    results_by_tau[tau_name] = results
    fidelities_by_tau[tau_name] = fidelities
    success_rates_by_tau[tau_name] = success_rates
    results_by_tau[tau_name]['std_vals'] = std_vals

tau = tau_regimes['medium']
results_3protocols = {k: results_by_tau['medium'][k] for k in ['discard', 'asap', 'alap']}
std_3protocols = results_by_tau['medium']['std_vals']

T_vals = np.linspace(0.2, 2.0, 18)
lambda_fixed = 1.0
np.random.seed(SEED)
Ic_asap_T, Ic_alap_T = [], []
for T_test in T_vals:
    samples_fixed = {
        't_l1_1': generate_poisson_arrivals(lambda_fixed, T_test, n_samples),
        't_l2_1': generate_poisson_arrivals(lambda_fixed, T_test, n_samples)
    }
    Ic_asap_T.append(single_link_distill_asap(n_samples, lambda_fixed, tau, T_test, samples_fixed, P_GATE, P_MEAS)[0])
    Ic_alap_T.append(single_link_distill_alap(n_samples, lambda_fixed, tau, T_test, samples_fixed, P_GATE, P_MEAS)[0])

def single_link_discard_oldest_distribution(n_samples, lam, tau, T, samples, p_gate=1.0, p_meas=1.0):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = []

    for i in range(n_samples):
        available = [t for t in [t1a[i], t2a[i]] if t < T]
        if len(available) > 0:
            F_final.append(raw_fidelity(max(available), T, tau))

    F_arr = np.array(F_final)
    I_c = coherent_information_vectorized(F_arr)
    return F_arr, I_c

def single_link_distill_alap_distribution(n_samples, lam, tau, T, samples, p_gate=1.0, p_meas=1.0):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = []
    for i in range(n_samples):
        if t1a[i] < T and t2a[i] < T:
            F1 = raw_fidelity(t1a[i], T, tau)
            F2 = raw_fidelity(t2a[i], T, tau)
            F_pur, p_succ = isotropic_purification_pairwise(F1, F2, p_gate, p_meas)
            if np.random.uniform(0, 1) < p_succ:
                F_final.append(F_pur)
            # else: distillation failed, protocol failure, no output appended
        elif t1a[i] < T:
            F_final.append(raw_fidelity(t1a[i], T, tau))
        elif t2a[i] < T:
            F_final.append(raw_fidelity(t2a[i], T, tau))
    F_arr = np.array(F_final)
    I_c = coherent_information_vectorized(F_arr)
    return F_arr, I_c

lam_hist = 1.0
tau_hist = tau
T_hist = 2.0 / lam_hist
n_samples_hist = 100000
np.random.seed(SEED)
samples_hist = {
    't_l1_1': generate_poisson_arrivals(lam_hist, T_hist, n_samples_hist),
    't_l2_1': generate_poisson_arrivals(lam_hist, T_hist, n_samples_hist)
}
F_alap, Ic_alap = single_link_distill_alap_distribution(n_samples_hist, lam_hist, tau_hist, T_hist, samples_hist, P_GATE, P_MEAS)
F_discard, Ic_discard = single_link_discard_oldest_distribution(n_samples_hist, lam_hist, tau_hist, T_hist, samples_hist, P_GATE, P_MEAS)

F0_list = [0.45, 0.49, 0.51, 0.6, 0.8]
purif_threshold = {}
for F0 in F0_list:
    F = F0
    seq = [F0]
    for _ in range(10):
        F, _ = isotropic_purification_pairwise(F, F, P_GATE, P_MEAS)
        seq.append(F)
    purif_threshold[F0] = seq

def recurrence_yield(F0, n_raw=4000, rounds=5, p_gate=1.0, p_meas=1.0):
    arr = np.full(n_raw, F0)
    for _ in range(rounds):
        if len(arr) < 2:
            break
        idx = np.random.permutation(len(arr))
        if len(idx) % 2:
            idx = idx[:-1]
        p = idx.reshape(-1, 2)
        F_purif, _ = isotropic_purification_pairwise(arr[p[:,0]], arr[p[:,1]], p_gate, p_meas)
        arr = F_purif
    return len(arr)/n_raw

F0s_yield = np.linspace(0.52, 0.95, 10)
yields = [np.mean([recurrence_yield(f, p_gate=P_GATE, p_meas=P_MEAS) for _ in range(5)]) for f in F0s_yield]

N_list = [2, 4, 8, 16, 32]
Ic_scaling_sim = []
lam_example, T_example = 1.0, 20.0
for seg in N_list:
    reps = []
    for _ in range(1500):
        Fs = [0.25 + 0.65*np.exp(-2*(T_example-np.random.exponential(1/lam_example))/tau) for __ in range(seg)]
        F_result = Fs[0]
        for j in range(1, len(Fs)):
            F_temp, _ = isotropic_purification_pairwise(F_result, Fs[j], P_GATE, P_MEAS) if j < len(Fs) else (F_result, 1.0)
            F_result = F_temp
        reps.append(F_result)
    Ic_scaling_sim.append(np.mean(coherent_information_vectorized(np.array(reps))))

fig3 = plt.figure(figsize=(7,5))
plt.plot(T_vals, Ic_asap_T, label=PROTOCOL_LABELS['asap'], marker='o', color=PROTOCOL_COLORS['asap'])
plt.plot(T_vals, Ic_alap_T, label=PROTOCOL_LABELS['alap'], marker='s', color=PROTOCOL_COLORS['alap'])
plt.xlabel("T (time units)")
plt.ylabel("Coherent Information")
plt.legend()
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/Ic_vs_T_both_protocols.pdf", dpi=300)
plt.show()

fig4 = plt.figure(figsize=(7,5))
plt.plot(lambda_vals, results_3protocols['asap'], label=PROTOCOL_LABELS['asap'], marker='o', color=PROTOCOL_COLORS['asap'])
plt.plot(lambda_vals, results_3protocols['alap'], label=PROTOCOL_LABELS['alap'], marker='s', color=PROTOCOL_COLORS['alap'])
plt.xlabel("λ (Rate, 1/time units)")
plt.ylabel("Coherent Information")
plt.grid()
plt.legend()
plt.tight_layout()
plt.savefig("figures_single_link/Ic_vs_lambda_strategy_comparison.pdf", dpi=300)
plt.show()

fig6 = plt.figure(figsize=(7,5))
_edges_F = shared_bin_edges(F_alap, F_discard)
plt.hist(F_alap, bins=_edges_F, density=True, color='skyblue', edgecolor='black', alpha=0.7, label=PROTOCOL_LABELS['alap'])
plt.hist(F_discard, bins=_edges_F, density=True, color='lightcoral', edgecolor='black', alpha=0.5, label=PROTOCOL_LABELS['discard'])
plt.xlabel("Final Fidelity", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.title(f"Fidelity Distribution (λ={lam_hist}, τ={tau_hist}, T={T_hist:.1f})", fontsize=13, fontweight='bold')
plt.legend(fontsize=10)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures_single_link/fidelity_histogram_example.pdf", dpi=300)
plt.show()

fig7 = plt.figure(figsize=(7,5))
Ic_alap_pos = Ic_alap[Ic_alap > 0]
Ic_discard_pos = Ic_discard[Ic_discard > 0]
_edges_I = shared_bin_edges(Ic_alap_pos, Ic_discard_pos)
if len(Ic_alap_pos) > 0:
    plt.hist(Ic_alap_pos, bins=_edges_I, density=True, color='mediumseagreen', edgecolor='black', alpha=0.7, label=f'{PROTOCOL_LABELS["alap"]} ({len(Ic_alap_pos)} samples)')
if len(Ic_discard_pos) > 0:
    plt.hist(Ic_discard_pos, bins=_edges_I, density=True, color='orange', edgecolor='black', alpha=0.5, label=f'{PROTOCOL_LABELS["discard"]} ({len(Ic_discard_pos)} samples)')
plt.xlabel("Coherent Information", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.title(f"Coherent Information Distribution (Ic > 0)\n(λ={lam_hist}, τ={tau_hist}, T={T_hist:.1f})", fontsize=13, fontweight='bold')
plt.legend(fontsize=9)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures_single_link/coherent_info_histogram_example.pdf", dpi=300)
plt.show()

fig8 = plt.figure(figsize=(6,4))
for F0 in F0_list:
    plt.plot(purif_threshold[F0], label=f"$F_0$={F0:.2f}", marker='o')
plt.axhline(0.5, color='k', ls='--', label='Threshold')
plt.legend(fontsize=8)
plt.xlabel("Iteration")
plt.ylabel("Fidelity")
plt.title("Purification Threshold Behavior")
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/fig_purification_threshold.pdf", dpi=300)
plt.show()

fig9 = plt.figure(figsize=(6,4))
plt.plot(F0s_yield, yields, marker='o', color='green')
plt.xlabel("Initial Fidelity $F_0$")
plt.ylabel("Yield")
plt.title("Recurrence Purification Yield")
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/fig_recurrence_yield.pdf", dpi=300)
plt.show()

fig10 = plt.figure(figsize=(6,4))
plt.plot(N_list, Ic_scaling_sim, marker='o', label='Simulation')
plt.xscale('log', base=2)
plt.xlabel("Segments N")
plt.ylabel("Coherent Information")
plt.title("Single-Link Repeater Scaling")
plt.grid(which='both', ls='--')
plt.legend()
plt.tight_layout()
plt.savefig("figures_single_link/fig_repeater_scaling.pdf", dpi=300)
plt.show()

fig11 = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, results_3protocols['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color=PROTOCOL_COLORS['discard'], markersize=7)
plt.plot(lambda_vals, results_3protocols['asap'], label=PROTOCOL_LABELS['asap'], marker='o', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_3protocols['alap'], label=PROTOCOL_LABELS['alap'], marker='s', linewidth=2, alpha=0.7)
plt.title(f"Three Protocol Comparison", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Coherent Information", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', fontsize=10)
plt.tight_layout()
plt.savefig("figures_single_link/all_protocols_comparison.pdf", dpi=300)
plt.show()

fig_pr_lambda = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, success_rates_by_tau['medium']['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color=PROTOCOL_COLORS['discard'], markersize=7)
plt.plot(lambda_vals, success_rates_by_tau['medium']['asap'], label=PROTOCOL_LABELS['asap'], marker='o', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_rates_by_tau['medium']['alap'], label=PROTOCOL_LABELS['alap'], marker='s', linewidth=2, alpha=0.7)
plt.title("Success Probability vs λ", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Pr(success)", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', fontsize=10)
plt.tight_layout()
plt.savefig("figures_single_link/success_prob_vs_lambda.pdf", dpi=300)
plt.show()

df_3protocols = pd.DataFrame({
    'lambda': lambda_vals,
    'Discard-Oldest_mean': results_3protocols['discard'],
    'Distill-ASAP_mean': results_3protocols['asap'],
    'Distill-ALAP_mean': results_3protocols['alap']
})
df_3protocols['Data_Section'] = 'All_Protocols'
df_3protocols['p_gate'] = P_GATE
df_3protocols['p_meas'] = P_MEAS
all_dataframes.append(df_3protocols)

df_regimes = pd.DataFrame({
    'lambda': lambda_vals,
    **{f'{tau_name}_discard_Ic': results_by_tau[tau_name]['discard'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_discard_F': fidelities_by_tau[tau_name]['discard'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_discard_Pr': success_rates_by_tau[tau_name]['discard'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_asap_Ic': results_by_tau[tau_name]['asap'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_asap_F': fidelities_by_tau[tau_name]['asap'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_asap_Pr': success_rates_by_tau[tau_name]['asap'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_alap_Ic': results_by_tau[tau_name]['alap'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_alap_F': fidelities_by_tau[tau_name]['alap'] for tau_name in tau_regimes.keys()},
    **{f'{tau_name}_alap_Pr': success_rates_by_tau[tau_name]['alap'] for tau_name in tau_regimes.keys()},
})
df_regimes['Data_Section'] = 'Parameter_Regimes'
df_regimes['p_gate'] = P_GATE
df_regimes['p_meas'] = P_MEAS
all_dataframes.append(df_regimes)

stats_summary = {
    PROTOCOL_LABELS['discard']: {'mean': np.mean(results_3protocols['discard']), 'std': np.std(results_3protocols['discard']), 'max': np.max(results_3protocols['discard']), 'min': np.min(results_3protocols['discard'])},
    PROTOCOL_LABELS['asap']: {'mean': np.mean(results_3protocols['asap']), 'std': np.std(results_3protocols['asap']), 'max': np.max(results_3protocols['asap']), 'min': np.min(results_3protocols['asap'])},
    PROTOCOL_LABELS['alap']: {'mean': np.mean(results_3protocols['alap']), 'std': np.std(results_3protocols['alap']), 'max': np.max(results_3protocols['alap']), 'min': np.min(results_3protocols['alap'])}
}

df_stats = pd.DataFrame(stats_summary).T
df_stats['Protocol'] = df_stats.index
df_stats['Data_Section'] = 'Protocol_Statistics'
df_stats['p_gate'] = P_GATE
df_stats['p_meas'] = P_MEAS
all_dataframes.append(df_stats.reset_index(drop=True))

temporal_stats = {
    'ASAP': {'mean': np.mean(Ic_asap_T), 'std': np.std(Ic_asap_T), 'max': np.max(Ic_asap_T), 'min': np.min(Ic_asap_T)},
    'ALAP': {'mean': np.mean(Ic_alap_T), 'std': np.std(Ic_alap_T), 'max': np.max(Ic_alap_T), 'min': np.min(Ic_alap_T)}
}
df_temporal = pd.DataFrame(temporal_stats).T
df_temporal['Protocol'] = df_temporal.index
df_temporal['Data_Section'] = 'Temporal_Analysis'
df_temporal['p_gate'] = P_GATE
df_temporal['p_meas'] = P_MEAS
all_dataframes.append(df_temporal.reset_index(drop=True))

fidelity_stats = {
    'Fsw_mean': np.mean(F_alap), 'Fsw_std': np.std(F_alap), 'Fsw_min': np.min(F_alap), 'Fsw_max': np.max(F_alap),
    'Ic_mean': np.mean(Ic_alap), 'Ic_std': np.std(Ic_alap), 'Ic_min': np.min(Ic_alap), 'Ic_max': np.max(Ic_alap)
}
df_fidelity = pd.DataFrame([fidelity_stats])
df_fidelity['Data_Section'] = 'Fidelity_Distribution'
df_fidelity['p_gate'] = P_GATE
df_fidelity['p_meas'] = P_MEAS
all_dataframes.append(df_fidelity)

best_protocol = max(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
worst_protocol = min(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
improvement_vs_discard = ((stats_summary[best_protocol]['mean'] - stats_summary[PROTOCOL_LABELS['discard']]['mean']) / stats_summary[PROTOCOL_LABELS['discard']]['mean'] * 100) if stats_summary[PROTOCOL_LABELS['discard']]['mean'] != 0 else float('inf')

comparison_metrics = {
    'best_protocol': best_protocol,
    'best_mean_Ic': stats_summary[best_protocol]['mean'],
    'best_max_Ic': stats_summary[best_protocol]['max'],
    'worst_protocol': worst_protocol,
    'worst_mean_Ic': stats_summary[worst_protocol]['mean'],
    'improvement_vs_discard_pct': improvement_vs_discard,
    'discard_mean': stats_summary[PROTOCOL_LABELS['discard']]['mean'],
    'asap_mean_temporal': temporal_stats['ASAP']['mean'],
    'alap_mean_temporal': temporal_stats['ALAP']['mean'],
    'asap_max_temporal': temporal_stats['ASAP']['max'],
    'alap_max_temporal': temporal_stats['ALAP']['max'],
    'temporal_improvement_pct': ((temporal_stats['ALAP']['mean'] - temporal_stats['ASAP']['mean']) / temporal_stats['ASAP']['mean'] * 100) if temporal_stats['ASAP']['mean'] != 0 else float('inf')
}
df_comparison = pd.DataFrame([comparison_metrics])
df_comparison['Data_Section'] = 'Key_Comparisons'
df_comparison['p_gate'] = P_GATE
df_comparison['p_meas'] = P_MEAS
all_dataframes.append(df_comparison)

df_combined = pd.concat(all_dataframes, ignore_index=True, sort=False)
df_combined.to_csv("figures_single_link/single_link_combined_data.csv", index=False)

print("\n" + "="*80)
print("FIGURE GENERATION COMPLETE")
print("="*80)
print(f"\nAll figures saved to: figures_single_link/")
print(f"Total figures generated: 12")
print("\nFigure List:")
print("  1. physical_params_coherent_info_vs_T.pdf")
print("  2. physical_params_fidelity_vs_T.pdf")
print("  3. physical_params_success_prob_vs_T.pdf")
print("  4. Ic_vs_T_both_protocols.pdf")
print("  5. Ic_vs_lambda_strategy_comparison.pdf")
print("  6. fidelity_histogram_example.pdf")
print("  7. coherent_info_histogram_example.pdf")
print("  8. fig_purification_threshold.pdf")
print("  9. fig_recurrence_yield.pdf")
print(" 10. fig_repeater_scaling.pdf")
print(" 11. all_protocols_comparison.pdf")
print(" 12. success_prob_vs_lambda.pdf")

print("\n" + "="*80)
print("PARAMETER REGIME COMPARISON")
print("="*80)
for tau_name, tau_val in tau_regimes.items():
    print(f"\nτ = {tau_val} ({tau_name}):")
    print(f"  Best protocol (Ic): {max(['discard', 'asap', 'alap'], key=lambda p: np.mean(results_by_tau[tau_name][p]))}")
    print(f"  Mean fidelity range: [{np.min([np.mean(fidelities_by_tau[tau_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}, {np.max([np.mean(fidelities_by_tau[tau_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}]")
    print(f"  Mean success prob range: [{np.min([np.mean(success_rates_by_tau[tau_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}, {np.max([np.mean(success_rates_by_tau[tau_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}]")

print("\n" + "="*80)
print("KEY STATISTICS SUMMARY (τ = {})".format(tau))
print("="*80)
print(f"\nBest Protocol: {best_protocol}")
print(f"  Mean Ic: {stats_summary[best_protocol]['mean']:.6f}")
print(f"  Std Dev: {stats_summary[best_protocol]['std']:.6f}")
print(f"  Max Ic: {stats_summary[best_protocol]['max']:.6f}")
print(f"  Min Ic: {stats_summary[best_protocol]['min']:.6f}")
print(f"\nWorst Protocol: {worst_protocol}")
print(f"  Mean Ic: {stats_summary[worst_protocol]['mean']:.6f}")
print(f"\n{PROTOCOL_LABELS['discard']} Baseline:")
print(f"  Mean Ic: {stats_summary[PROTOCOL_LABELS['discard']]['mean']:.6f}")
print(f"  Mean Fidelity: {np.mean(fidelities_by_tau['medium']['discard']):.6f}")
print(f"  Mean Success Prob: {np.mean(success_rates_by_tau['medium']['discard']):.6f}")
print(f"\nPerformance Improvement:")
print(f"  Best vs Discard-Oldest: {improvement_vs_discard:+.2f}%")
print(f"\nTemporal Analysis (ASAP vs ALAP):")
print(f"  ASAP Mean: {temporal_stats['ASAP']['mean']:.6f} (Max: {temporal_stats['ASAP']['max']:.6f})")
print(f"  ALAP Mean: {temporal_stats['ALAP']['mean']:.6f} (Max: {temporal_stats['ALAP']['max']:.6f})")
print(f"  ALAP improvement: {comparison_metrics['temporal_improvement_pct']:+.2f}%")
print(f"\nFidelity Distribution Statistics:")
print(f"  Mean Fidelity: {fidelity_stats['Fsw_mean']:.4f} ± {fidelity_stats['Fsw_std']:.4f}")
print(f"  Range: [{fidelity_stats['Fsw_min']:.4f}, {fidelity_stats['Fsw_max']:.4f}]")
print(f"  Mean Ic: {fidelity_stats['Ic_mean']:.4f} ± {fidelity_stats['Ic_std']:.4f}")
print("\n" + "="*80)
print("ALL 3 PROTOCOLS PERFORMANCE TABLE")
print("="*80)
print(f"{'Protocol':<20} {'Mean Ic':>12} {'Std Dev':>12} {'Max Ic':>12} {'Min Ic':>12}")
print("-"*80)
for protocol in [PROTOCOL_LABELS[k] for k in ['discard', 'asap', 'alap']]:
    s = stats_summary[protocol]
    print(f"{protocol:<20} {s['mean']:>12.6f} {s['std']:>12.6f} {s['max']:>12.6f} {s['min']:>12.6f}")
print("="*80)
print("\nAll data saved to single CSV file:")
print("  - figures_single_link/single_link_combined_data.csv")
print("    Contains sections: Physical_Params (6 regimes), All_Protocols,")
print("    Parameter_Regimes, Protocol_Statistics, Temporal_Analysis,")
print("    Fidelity_Distribution, Key_Comparisons")
print("="*80)
print("\n" + "="*80)
print("OPERATION ERROR PARAMETERS USED")
print("="*80)
print(f"p_gate = {P_GATE}")
print(f"p_meas = {P_MEAS}")
if P_GATE == 1.0 and P_MEAS == 1.0:
    print("\n Perfect operations - Results identical to original code")
    print("  To test imperfect operations (paper's condition):")
    print("  Change P_GATE = 0.9 and P_MEAS = 0.9 at lines 47-48")
elif P_GATE == 0.9 and P_MEAS == 0.9:
    print("\n Imperfect operations - Paper's condition")
    print("  This should show degradation in purification performance")
print("="*80)

print("\n" + "="*80)
print("MERGING ALL PDFs INTO COMBINED DOCUMENT")
print("="*80)

from pypdf import PdfWriter, PdfReader

# Ordered list of all PDF figures generated above
pdf_files_to_merge = [
    "figures_single_link/physical_params_coherent_info_vs_T.pdf",
    "figures_single_link/physical_params_fidelity_vs_T.pdf",
    "figures_single_link/physical_params_success_prob_vs_T.pdf",
    "figures_single_link/Ic_vs_T_both_protocols.pdf",
    "figures_single_link/Ic_vs_lambda_strategy_comparison.pdf",
    "figures_single_link/fidelity_histogram_example.pdf",
    "figures_single_link/coherent_info_histogram_example.pdf",
    "figures_single_link/fig_purification_threshold.pdf",
    "figures_single_link/fig_recurrence_yield.pdf",
    "figures_single_link/fig_repeater_scaling.pdf",
    "figures_single_link/all_protocols_comparison.pdf",
    "figures_single_link/success_prob_vs_lambda.pdf",
]

combined_pdf_path = "figures_single_link/all_figures_combined.pdf"

writer = PdfWriter()
for pdf_path in pdf_files_to_merge:
    reader = PdfReader(pdf_path)
    for page in reader.pages:
        writer.add_page(page)

with open(combined_pdf_path, "wb") as output_file:
    writer.write(output_file)

print(f"\nCombined PDF saved to: {combined_pdf_path}")
print(f"Total pages merged: {sum(len(PdfReader(p).pages) for p in pdf_files_to_merge)}")
print("="*80)