# -*- coding: utf-8 -*-
"""OneLinkNumericalCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVMlN7l-Gltm0qnk3ddBRGt_PiluVCBg
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

plt.rcParams.update({
    'font.size': 13,
    'axes.labelsize': 16,
    'axes.titlesize': 17,
    'xtick.labelsize': 13,
    'ytick.labelsize': 13,
    'legend.fontsize': 12,
    'figure.titlesize': 18,
    'lines.linewidth': 2.4,
    'lines.markersize': 7
})

PROTOCOL_COLORS = {
    'discard': 'black',
    'asap': '#1f77b4',
    'alap': '#ff7f0e',
}

PROTOCOL_LABELS = {
    'discard': 'Discard-Oldest',
    'asap': 'Distill-ASAP',
    'alap': 'Distill-ALAP',
}

os.makedirs("figures_single_link", exist_ok=True)

SEED = 42
np.random.seed(SEED)

lambda_vals_physical = [10.0, 1e4]
c_vals_physical = [0.1, 1.0, 100.0]

def coherent_information(F):
    F = np.clip(F, 1e-12, 1 - 1e-12)
    lambda1 = F
    lambda_rest = (1 - F) / 3
    eigs = np.array([lambda1, lambda_rest, lambda_rest, lambda_rest])
    S = -np.sum(eigs * np.log2(eigs + 1e-12))
    return np.maximum(0, 1 - S)

def isotropic_purification_pairwise(F1, F2):
    num = F1 * F2 + (1/9) * (1 - F1) * (1 - F2)
    denom = (F1 * F2 + (1/3) * F1 * (1 - F2) + (1/3) * F2 * (1 - F1) + (5/9) * (1 - F1) * (1 - F2))
    return np.clip(num / denom, 0, 1)

def discard_oldest_analytical(lam, c, T, F0=0.9):
    eps = 1e-8
    expLT = np.exp(-lam * T)
    exp2LT = np.exp(-2 * lam * T)
    exp2Tc = np.exp(-2 * T / c)
    F0_eff = F0 - 0.25

    term1 = 0.25 - 0.25 * exp2LT
    coeff = 2 * lam * F0_eff

    denom1 = lam - 2/c
    if abs(denom1) < eps:
        bracket1 = T * (expLT + 1) * exp2Tc
    else:
        bracket1 = (expLT + 1) * (exp2Tc - expLT) / denom1

    denom2 = 2*lam - 2/c
    if abs(denom2) < eps:
        bracket2 = T * exp2Tc
    else:
        bracket2 = (exp2Tc - exp2LT) / denom2

    term2 = coeff * (bracket1 - bracket2)

    Fbar = (term1 + term2) / (1 - exp2LT + eps)
    Fbar = np.clip(Fbar, 0, 1)
    success_rate = 1 - exp2LT
    R = success_rate * coherent_information(Fbar)

    return Fbar, R, success_rate

def distill_alap_analytical(lam, c, T, F0=0.9):
    eps = 1e-8
    L = lam
    lam_orig = lam

    if abs(c * L - 2) < 0.05:
        delta = 0.02
        lam_low = (2.0 - delta) / c
        lam_high = (2.0 + delta) / c
        T_low = 2.0 / lam_low
        T_high = 2.0 / lam_high

        L_low = lam_low
        expLT_low = np.exp(-L_low * T_low)
        exp2LT_low = np.exp(-2 * L_low * T_low)
        exp2Tc_low = np.exp(-2 * T_low / c)
        expSum_low = np.exp(-T_low * (2/c + L_low))
        cL_low = c * L_low

        num1_low = 5 * c * c * (1 - 4*F0) * (1 - 4*F0) * L_low * L_low * np.exp(-4*T_low/c)
        num2_low = 6 * c * (4*F0 - 1) * L_low * (cL_low - 2) * exp2Tc_low
        num3_low = -20 * c * (4*F0 - 1) * L_low * (2*c*(F0-1)*L_low + 3) * expSum_low
        num4_low = -12 * (cL_low - 2) * expLT_low * (2*c*(F0-1)*L_low + 3)
        num5_inner_low = 8*cL_low*(10*F0*(c*(F0-2)*L_low + 3) + cL_low + 6) - 108
        num5_low = exp2LT_low * num5_inner_low
        num6_low = 9 * (cL_low - 2) * (cL_low - 2)
        numerator_low = num1_low + num2_low + num3_low + num4_low + num5_low + num6_low

        denom_factor_low = 4 * (cL_low - 2) * (cL_low - 2)
        denom1_low = (c*c * (1-4*F0)*(1-4*F0) * L_low*L_low * np.exp(-4*T_low/c)) / ((cL_low-2)*(cL_low-2))
        denom2_low = -(2 * c*c * (1-4*F0)*(1-4*F0) * L_low*L_low * expSum_low) / ((cL_low-2)*(cL_low-2))
        denom3_inner_low = cL_low * (c * (8*F0*F0 - 4*F0 - 13) * L_low + 54) - 54
        denom3_low = (2 * exp2LT_low * denom3_inner_low) / ((cL_low-2)*(cL_low-2))
        denom4_low = 18 * expLT_low + 9
        denominator_low = denom_factor_low * (denom1_low + denom2_low + denom3_low + denom4_low)
        Fbar_low = numerator_low / (denominator_low + eps)

        p_succ_term1_low = (c*c * (1-4*F0)*(1-4*F0) * L_low*L_low * np.exp(-4*T_low/c)) / ((cL_low-2)*(cL_low-2))
        p_succ_term2_low = -(2 * c*c * (1-4*F0)*(1-4*F0) * L_low*L_low * expSum_low) / ((cL_low-2)*(cL_low-2))
        p_succ_term3_inner_low = cL_low * (c*(8*F0*F0 - 4*F0 - 13)*L_low + 54) - 54
        p_succ_term3_low = (2 * exp2LT_low * p_succ_term3_inner_low) / ((cL_low-2)*(cL_low-2))
        p_succ_term4_low = 18 * expLT_low + 9
        p_succ_mean_low = (1/18) * (p_succ_term1_low + p_succ_term2_low + p_succ_term3_low + p_succ_term4_low)

        L_high = lam_high
        expLT_high = np.exp(-L_high * T_high)
        exp2LT_high = np.exp(-2 * L_high * T_high)
        exp2Tc_high = np.exp(-2 * T_high / c)
        expSum_high = np.exp(-T_high * (2/c + L_high))
        cL_high = c * L_high

        num1_high = 5 * c * c * (1 - 4*F0) * (1 - 4*F0) * L_high * L_high * np.exp(-4*T_high/c)
        num2_high = 6 * c * (4*F0 - 1) * L_high * (cL_high - 2) * exp2Tc_high
        num3_high = -20 * c * (4*F0 - 1) * L_high * (2*c*(F0-1)*L_high + 3) * expSum_high
        num4_high = -12 * (cL_high - 2) * expLT_high * (2*c*(F0-1)*L_high + 3)
        num5_inner_high = 8*cL_high*(10*F0*(c*(F0-2)*L_high + 3) + cL_high + 6) - 108
        num5_high = exp2LT_high * num5_inner_high
        num6_high = 9 * (cL_high - 2) * (cL_high - 2)
        numerator_high = num1_high + num2_high + num3_high + num4_high + num5_high + num6_high

        denom_factor_high = 4 * (cL_high - 2) * (cL_high - 2)
        denom1_high = (c*c * (1-4*F0)*(1-4*F0) * L_high*L_high * np.exp(-4*T_high/c)) / ((cL_high-2)*(cL_high-2))
        denom2_high = -(2 * c*c * (1-4*F0)*(1-4*F0) * L_high*L_high * expSum_high) / ((cL_high-2)*(cL_high-2))
        denom3_inner_high = cL_high * (c * (8*F0*F0 - 4*F0 - 13) * L_high + 54) - 54
        denom3_high = (2 * exp2LT_high * denom3_inner_high) / ((cL_high-2)*(cL_high-2))
        denom4_high = 18 * expLT_high + 9
        denominator_high = denom_factor_high * (denom1_high + denom2_high + denom3_high + denom4_high)
        Fbar_high = numerator_high / (denominator_high + eps)

        p_succ_term1_high = (c*c * (1-4*F0)*(1-4*F0) * L_high*L_high * np.exp(-4*T_high/c)) / ((cL_high-2)*(cL_high-2))
        p_succ_term2_high = -(2 * c*c * (1-4*F0)*(1-4*F0) * L_high*L_high * expSum_high) / ((cL_high-2)*(cL_high-2))
        p_succ_term3_inner_high = cL_high * (c*(8*F0*F0 - 4*F0 - 13)*L_high + 54) - 54
        p_succ_term3_high = (2 * exp2LT_high * p_succ_term3_inner_high) / ((cL_high-2)*(cL_high-2))
        p_succ_term4_high = 18 * expLT_high + 9
        p_succ_mean_high = (1/18) * (p_succ_term1_high + p_succ_term2_high + p_succ_term3_high + p_succ_term4_high)

        alpha = (lam - lam_low) / (lam_high - lam_low)
        Fbar = Fbar_low * (1 - alpha) + Fbar_high * alpha
        p_succ_mean = p_succ_mean_low * (1 - alpha) + p_succ_mean_high * alpha
    else:
        expLT = np.exp(-L * T)
        exp2LT = np.exp(-2 * L * T)
        exp2Tc = np.exp(-2 * T / c)
        expSum = np.exp(-T * (2/c + L))
        cL = c * L

        num1 = 5 * c * c * (1 - 4*F0) * (1 - 4*F0) * L * L * np.exp(-4*T/c)
        num2 = 6 * c * (4*F0 - 1) * L * (cL - 2) * exp2Tc
        num3 = -20 * c * (4*F0 - 1) * L * (2*c*(F0-1)*L + 3) * expSum
        num4 = -12 * (cL - 2) * expLT * (2*c*(F0-1)*L + 3)
        num5_inner = 8*cL*(10*F0*(c*(F0-2)*L + 3) + cL + 6) - 108
        num5 = exp2LT * num5_inner
        num6 = 9 * (cL - 2) * (cL - 2)
        numerator = num1 + num2 + num3 + num4 + num5 + num6

        denom_factor = 4 * (cL - 2) * (cL - 2)

        denom1 = (c*c * (1-4*F0)*(1-4*F0) * L*L * np.exp(-4*T/c)) / ((cL-2)*(cL-2))
        denom2 = -(2 * c*c * (1-4*F0)*(1-4*F0) * L*L * expSum) / ((cL-2)*(cL-2))
        denom3_inner = cL * (c * (8*F0*F0 - 4*F0 - 13) * L + 54) - 54
        denom3 = (2 * exp2LT * denom3_inner) / ((cL-2)*(cL-2))
        denom4 = 18 * expLT + 9
        denominator = denom_factor * (denom1 + denom2 + denom3 + denom4)

        Fbar = numerator / (denominator + eps)

        p_succ_term1 = (c*c * (1-4*F0)*(1-4*F0) * L*L * np.exp(-4*T/c)) / ((cL-2)*(cL-2))
        p_succ_term2 = -(2 * c*c * (1-4*F0)*(1-4*F0) * L*L * expSum) / ((cL-2)*(cL-2))
        p_succ_term3_inner = cL * (c*(8*F0*F0 - 4*F0 - 13)*L + 54) - 54
        p_succ_term3 = (2 * exp2LT * p_succ_term3_inner) / ((cL-2)*(cL-2))
        p_succ_term4 = 18 * expLT + 9

        p_succ_mean = (1/18) * (p_succ_term1 + p_succ_term2 + p_succ_term3 + p_succ_term4)

    Fbar = np.clip(Fbar, 0, 1)
    p_succ_mean = np.clip(p_succ_mean, 0, 1)

    exp2LT_orig = np.exp(-2 * lam_orig * T)
    success_rate = 1 - exp2LT_orig
    R = success_rate * p_succ_mean * coherent_information(Fbar)

    return Fbar, R, success_rate

def distill_asap_analytical(lam, c, T, F0=0.9):
    eps = 1e-8
    lam_orig = lam

    if abs(c*lam - 2) < eps:
        lam = lam * (1 + 1e-10)

    numerator = (-6 * np.exp(2*T/c + 3*T*lam) * (-1 + c*lam) * (2 + c*lam) * (3 + 2*c*(-1 + F0)*lam) -
                 2*c * np.exp(3*T*lam) * (-1 + 4*F0) * lam * (-1 + c*lam) * (-19 + 16*F0 + 10*c*(-1 + F0)*lam) +
                 np.exp(2*T*(1/c + 2*lam)) * (-2 + c*lam) * (-1 + c*lam) * (9 + c*(5 - 4*F0 + 8*F0**2)*lam) +
                 c * np.exp(4*T*lam) * (-1 + 4*F0) * lam * (2 + c*lam) * (1 + c*lam + 8*F0*(-2 + c*lam)) +
                 np.exp(2*T*(1/c + lam)) * (2 + c*lam) * (-27 + c*lam*(25 + 4*c*lam + 8*F0*(8 - F0 + 5*c*(-2 + F0)*lam))))

    denominator = (4 * (-1 + c*lam) * (-c**2 * np.exp(3*T*lam) * (1 - 4*F0)**2 * lam**2 +
                                        np.exp(2*T*(1/c + lam)) * (2 + c*lam) * (27 + c*(-13 - 4*F0 + 8*F0**2)*lam) +
                                        np.exp(2*T*(1/c + 2*lam)) * (-2 + c*lam) * (9 + c*(5 - 4*F0 + 8*F0**2)*lam) +
                                        9 * np.exp(2*T/c + 3*T*lam) * (-4 + c**2 * lam**2)))

    Fbar = numerator / (denominator + eps)
    Fbar = np.clip(Fbar, 0, 1)

    p_succ_numerator = (1 / (9 * (-4 + c**2 * lam**2)) *
                        np.exp(-2*T*(1/c + 2*lam)) *
                        (-c**2 * np.exp(3*T*lam) * (1 - 4*F0)**2 * lam**2 +
                         np.exp(2*T*(1/c + lam)) * (2 + c*lam) * (27 + c*(-13 - 4*F0 + 8*F0**2)*lam) +
                         np.exp(2*T*(1/c + 2*lam)) * (-2 + c*lam) * (9 + c*(5 - 4*F0 + 8*F0**2)*lam) +
                         9 * np.exp(2*T/c + 3*T*lam) * (-4 + c**2 * lam**2)))

    p_succ_mean = np.clip(p_succ_numerator, 0, 1)

    success_rate = 1 - np.exp(-2 * lam_orig * T)
    R = success_rate * p_succ_mean * coherent_information(Fbar)

    return Fbar, R, success_rate

print("\n" + "="*80)
print("COMPUTING PHYSICAL PARAMETER REGIMES")
print("="*80)

results_physical = {}
for lam in lambda_vals_physical:
    for c in c_vals_physical:
        key = f"lam{lam}_c{c}"
        print(f"\nProcessing λ={lam}/s, c={c}s...")

        T_min = 0.01 * c
        T_max = 0.2 * c
        T_vals = np.linspace(T_min, T_max, 30)

        results = {
            'T': T_vals,
            'discard_Ic': [], 'discard_F': [], 'discard_success': [],
            'asap_Ic': [], 'asap_F': [], 'asap_success': [],
            'alap_Ic': [], 'alap_F': [], 'alap_success': [],
        }

        for T in T_vals:
            F_discard, R_discard, succ_discard = discard_oldest_analytical(lam, c, T, F0=0.9)
            results['discard_Ic'].append(R_discard)
            results['discard_F'].append(F_discard)
            results['discard_success'].append(succ_discard)

            F_asap, R_asap, succ_asap = distill_asap_analytical(lam, c, T, F0=0.9)
            results['asap_Ic'].append(R_asap)
            results['asap_F'].append(F_asap)
            results['asap_success'].append(succ_asap)

            F_alap, R_alap, succ_alap = distill_alap_analytical(lam, c, T, F0=0.9)
            results['alap_Ic'].append(R_alap)
            results['alap_F'].append(F_alap)
            results['alap_success'].append(succ_alap)

        results_physical[key] = results

print("\n" + "="*80)
print("GENERATING FIGURES WITH PHYSICAL PARAMETERS")
print("="*80)

fig1 = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, c in enumerate(c_vals_physical):
        key = f"lam{lam}_c{c}"
        res = results_physical[key]

        plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_Ic'], label=PROTOCOL_LABELS['discard'],
                marker='D', color=PROTOCOL_COLORS['discard'], markersize=5)
        plt.plot(res['T'], res['asap_Ic'], label=PROTOCOL_LABELS['asap'],
                marker='o', color=PROTOCOL_COLORS['asap'], alpha=0.7)
        plt.plot(res['T'], res['alap_Ic'], label=PROTOCOL_LABELS['alap'],
                marker='s', color=PROTOCOL_COLORS['alap'], alpha=0.7)

        plt.title(f"λ={lam}/s, c={c}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Coherent Information")
        plt.grid(alpha=0.3)
        plt.legend(fontsize=9)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_single_link/physical_params_coherent_info_vs_T.pdf", dpi=300)
plt.show()

fig2 = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, c in enumerate(c_vals_physical):
        key = f"lam{lam}_c{c}"
        res = results_physical[key]

        plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_F'], label=PROTOCOL_LABELS['discard'],
                marker='D', color=PROTOCOL_COLORS['discard'], markersize=5)
        plt.plot(res['T'], res['asap_F'], label=PROTOCOL_LABELS['asap'],
                marker='o', color=PROTOCOL_COLORS['asap'], alpha=0.7)
        plt.plot(res['T'], res['alap_F'], label=PROTOCOL_LABELS['alap'],
                marker='s', color=PROTOCOL_COLORS['alap'], alpha=0.7)
        plt.axhline(y=0.8107, color='k', linestyle=':', label='Positive coherent information threshold')

        plt.title(f"λ={lam}/s, c={c}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Final Fidelity")
        plt.grid(alpha=0.3)
        plt.legend(fontsize=9)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_single_link/physical_params_fidelity_vs_T.pdf", dpi=300)
plt.show()

for key, res in results_physical.items():
    df = pd.DataFrame(res)
    df.to_csv(f"figures_single_link/data_{key}.csv", index=False)

print("\n" + "="*80)
print("SUMMARY OF PHYSICAL PARAMETER REGIMES")
print("="*80)
for key, res in results_physical.items():
    print(f"\n{key}:")
    for protocol in ['discard', 'asap', 'alap']:
        max_Ic = np.max(res[f'{protocol}_Ic'])
        max_F = np.max(res[f'{protocol}_F'])
        mean_Ic = np.mean(res[f'{protocol}_Ic'])
        print(f"  {PROTOCOL_LABELS[protocol]}: Max Ic={max_Ic:.6f}, Max F={max_F:.6f}, Mean Ic={mean_Ic:.6f}")

print("\n" + "="*80)
print("GENERATING ADDITIONAL FIGURES")
print("="*80)

lambda_vals = np.linspace(0.1, 2.0, 20)
c_regimes = {'small': 0.5, 'medium': 10.0, 'large': 50.0}

results_by_c = {}
fidelities_by_c = {}
success_rates_by_c = {}

for c_name, c_val in c_regimes.items():
    print(f"\nProcessing c = {c_val} ({c_name})...")
    results = {'discard': [], 'asap': [], 'alap': []}
    fidelities = {'discard': [], 'asap': [], 'alap': []}
    success_rates = {'discard': [], 'asap': [], 'alap': []}
    std_vals = {'discard': [], 'asap': [], 'alap': []}

    for lam in lambda_vals:
        T = 2.0 / lam

        F_discard, R_discard, succ_discard = discard_oldest_analytical(lam, c_val, T, F0=0.9)
        results['discard'].append(R_discard)
        std_vals['discard'].append(0.0)
        fidelities['discard'].append(F_discard)
        success_rates['discard'].append(succ_discard)

        F_asap, R_asap, succ_asap = distill_asap_analytical(lam, c_val, T, F0=0.9)
        results['asap'].append(R_asap)
        std_vals['asap'].append(0.0)
        fidelities['asap'].append(F_asap)
        success_rates['asap'].append(succ_asap)

        F_alap, R_alap, succ_alap = distill_alap_analytical(lam, c_val, T, F0=0.9)
        results['alap'].append(R_alap)
        std_vals['alap'].append(0.0)
        fidelities['alap'].append(F_alap)
        success_rates['alap'].append(succ_alap)

    results_by_c[c_name] = results
    fidelities_by_c[c_name] = fidelities
    success_rates_by_c[c_name] = success_rates
    results_by_c[c_name]['std_vals'] = std_vals

c = c_regimes['medium']
results_3protocols = {k: results_by_c['medium'][k] for k in ['discard', 'asap', 'alap']}
std_3protocols = results_by_c['medium']['std_vals']

T_vals = np.linspace(0.2, 2.0, 18)
lambda_fixed = 1.0
Ic_asap_T, Ic_alap_T = [], []
for T_test in T_vals:
    _, R_asap, _ = distill_asap_analytical(lambda_fixed, c, T_test, F0=0.9)
    Ic_asap_T.append(R_asap)
    _, R_alap, _ = distill_alap_analytical(lambda_fixed, c, T_test, F0=0.9)
    Ic_alap_T.append(R_alap)

fig3 = plt.figure(figsize=(7,5))
plt.plot(T_vals, Ic_asap_T, label=PROTOCOL_LABELS['asap'], marker='o', color=PROTOCOL_COLORS['asap'])
plt.plot(T_vals, Ic_alap_T, label=PROTOCOL_LABELS['alap'], marker='s', color=PROTOCOL_COLORS['alap'])
plt.xlabel("T (time units)")
plt.ylabel("Coherent Information")
plt.legend()
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/Ic_vs_T_both_protocols.pdf", dpi=300)
plt.show()

fig4 = plt.figure(figsize=(7,5))
plt.plot(lambda_vals, results_3protocols['asap'], label=PROTOCOL_LABELS['asap'], marker='o', color=PROTOCOL_COLORS['asap'])
plt.plot(lambda_vals, results_3protocols['alap'], label=PROTOCOL_LABELS['alap'], marker='s', color=PROTOCOL_COLORS['alap'])
plt.xlabel("λ (Rate, 1/time units)")
plt.ylabel("Coherent Information")
plt.grid()
plt.legend()
plt.tight_layout()
plt.savefig("figures_single_link/Ic_vs_lambda_strategy_comparison.pdf", dpi=300)
plt.show()

F0_list = [0.45, 0.49, 0.51, 0.6, 0.8]
purif_threshold = {}
for F0 in F0_list:
    F = F0
    seq = [F0]
    for _ in range(10):
        F = isotropic_purification_pairwise(F, F)
        seq.append(F)
    purif_threshold[F0] = seq

fig8 = plt.figure(figsize=(6,4))
for F0 in F0_list:
    plt.plot(purif_threshold[F0], label=f"$F_0$={F0:.2f}", marker='o')
plt.axhline(0.5, color='k', ls='--', label='Threshold')
plt.legend(fontsize=8)
plt.xlabel("Iteration")
plt.ylabel("Fidelity")
plt.title("Purification Threshold Behavior")
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/fig_purification_threshold.pdf", dpi=300)
plt.show()

def recurrence_yield(F0, n_raw=4000, rounds=5):
    arr = np.full(n_raw, F0)
    for _ in range(rounds):
        if len(arr) < 2:
            break
        idx = np.random.permutation(len(arr))
        if len(idx) % 2:
            idx = idx[:-1]
        p = idx.reshape(-1, 2)
        arr = isotropic_purification_pairwise(arr[p[:,0]], arr[p[:,1]])
    return len(arr)/n_raw

F0s_yield = np.linspace(0.52, 0.95, 10)
yields = [np.mean([recurrence_yield(f) for _ in range(5)]) for f in F0s_yield]

fig9 = plt.figure(figsize=(6,4))
plt.plot(F0s_yield, yields, marker='o', color='green')
plt.xlabel("Initial Fidelity $F_0$")
plt.ylabel("Yield")
plt.title("Recurrence Purification Yield")
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/fig_recurrence_yield.pdf", dpi=300)
plt.show()

N_list = [2, 4, 8, 16, 32]
Ic_scaling_sim = []
lam_example, T_example = 1.0, 20.0
for seg in N_list:
    reps = []
    for _ in range(1500):
        Fs = [0.25 + 0.65*np.exp(-2*(T_example-np.random.exponential(1/lam_example))/c) for __ in range(seg)]
        F_result = Fs[0]
        for j in range(1, len(Fs)):
            F_temp = isotropic_purification_pairwise(F_result, Fs[j]) if j < len(Fs) else F_result
            F_result = F_temp
        reps.append(F_result)
    Ic_scaling_sim.append(np.mean(coherent_information(np.array(reps))))

fig10 = plt.figure(figsize=(6,4))
plt.plot(N_list, Ic_scaling_sim, marker='o', label='Simulation')
plt.xscale('log', base=2)
plt.xlabel("Segments N")
plt.ylabel("Coherent Information")
plt.title("Single-Link Repeater Scaling")
plt.grid(which='both', ls='--')
plt.legend()
plt.tight_layout()
plt.savefig("figures_single_link/fig_repeater_scaling.pdf", dpi=300)
plt.show()

fig11 = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, results_3protocols['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color=PROTOCOL_COLORS['discard'], markersize=7)
plt.plot(lambda_vals, results_3protocols['asap'], label=PROTOCOL_LABELS['asap'], marker='o', linewidth=2.5, color=PROTOCOL_COLORS['asap'], markersize=7)
plt.plot(lambda_vals, results_3protocols['alap'], label=PROTOCOL_LABELS['alap'], marker='s', linewidth=2.5, color=PROTOCOL_COLORS['alap'], markersize=7)
plt.title(f"Single-Link Protocol Comparison (c = {c_regimes['medium']})", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Coherent Information", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', fontsize=10)
plt.tight_layout()
plt.savefig("figures_single_link/all_protocols_comparison.pdf", dpi=300)
plt.show()

df_single_link = pd.DataFrame({
    'lambda': lambda_vals,
    'Discard_mean': results_3protocols['discard'],
    'Discard_std': std_3protocols['discard'],
    'Discard_fidelity': fidelities_by_c['medium']['discard'],
    'Discard_success': success_rates_by_c['medium']['discard'],
    'ASAP_mean': results_3protocols['asap'],
    'ASAP_std': std_3protocols['asap'],
    'ASAP_fidelity': fidelities_by_c['medium']['asap'],
    'ASAP_success': success_rates_by_c['medium']['asap'],
    'ALAP_mean': results_3protocols['alap'],
    'ALAP_std': std_3protocols['alap'],
    'ALAP_fidelity': fidelities_by_c['medium']['alap'],
    'ALAP_success': success_rates_by_c['medium']['alap'],
})
df_single_link.to_csv("figures_single_link/all_protocols_data.csv", index=False)

df_regimes = pd.DataFrame({
    'lambda': lambda_vals,
    **{f'{c_name}_discard_Ic': results_by_c[c_name]['discard'] for c_name in c_regimes.keys()},
    **{f'{c_name}_asap_Ic': results_by_c[c_name]['asap'] for c_name in c_regimes.keys()},
    **{f'{c_name}_alap_Ic': results_by_c[c_name]['alap'] for c_name in c_regimes.keys()},
    **{f'{c_name}_discard_F': fidelities_by_c[c_name]['discard'] for c_name in c_regimes.keys()},
    **{f'{c_name}_asap_F': fidelities_by_c[c_name]['asap'] for c_name in c_regimes.keys()},
    **{f'{c_name}_alap_F': fidelities_by_c[c_name]['alap'] for c_name in c_regimes.keys()},
})
df_regimes.to_csv("figures_single_link/parameter_regime_data.csv", index=False)

stats_summary = {}
for protocol in ['discard', 'asap', 'alap']:
    stats_summary[protocol] = {
        'mean': np.mean(results_3protocols[protocol]),
        'std': np.std(results_3protocols[protocol]),
        'max': np.max(results_3protocols[protocol]),
        'min': np.min(results_3protocols[protocol]),
        'mean_fidelity': np.mean(fidelities_by_c['medium'][protocol]),
        'mean_success_rate': np.mean(success_rates_by_c['medium'][protocol])
    }
df_stats = pd.DataFrame(stats_summary).T
df_stats.to_csv("figures_single_link/protocol_statistics_summary.csv")

temporal_stats = {
    'ASAP': {'mean': np.mean(Ic_asap_T), 'std': np.std(Ic_asap_T), 'max': np.max(Ic_asap_T), 'min': np.min(Ic_asap_T)},
    'ALAP': {'mean': np.mean(Ic_alap_T), 'std': np.std(Ic_alap_T), 'max': np.max(Ic_alap_T), 'min': np.min(Ic_alap_T)}
}
df_temporal = pd.DataFrame(temporal_stats).T
df_temporal.to_csv("figures_single_link/temporal_analysis_statistics.csv")

best_protocol = max(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
worst_protocol = min(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
improvement_vs_discard = ((stats_summary[best_protocol]['mean'] - stats_summary['discard']['mean']) / stats_summary['discard']['mean'] * 100) if stats_summary['discard']['mean'] != 0 else float('inf')

comparison_metrics = {
    'best_protocol': best_protocol,
    'best_mean_Ic': stats_summary[best_protocol]['mean'],
    'best_max_Ic': stats_summary[best_protocol]['max'],
    'worst_protocol': worst_protocol,
    'worst_mean_Ic': stats_summary[worst_protocol]['mean'],
    'improvement_vs_discard_pct': improvement_vs_discard,
    'discard_mean': stats_summary['discard']['mean'],
    'asap_mean_temporal': temporal_stats['ASAP']['mean'],
    'alap_mean_temporal': temporal_stats['ALAP']['mean'],
    'asap_max_temporal': temporal_stats['ASAP']['max'],
    'alap_max_temporal': temporal_stats['ALAP']['max'],
    'temporal_improvement_pct': ((temporal_stats['ALAP']['mean'] - temporal_stats['ASAP']['mean']) / temporal_stats['ASAP']['mean'] * 100) if temporal_stats['ASAP']['mean'] != 0 else float('inf')
}
df_comparison = pd.DataFrame([comparison_metrics])
df_comparison.to_csv("figures_single_link/key_comparison_metrics.csv", index=False)

print("\n" + "="*80)
print("FIGURE GENERATION COMPLETE")
print("="*80)
print(f"\nAll figures saved to: figures_single_link/")
print(f"Total figures generated: 10")
print("\n" + "="*80)
print("PARAMETER REGIME COMPARISON")
print("="*80)
for c_name, c_val in c_regimes.items():
    print(f"\nc = {c_val} ({c_name}):")
    best_c = max(['discard', 'asap', 'alap'], key=lambda p: np.mean(results_by_c[c_name][p]))
    print(f"  Best protocol: {best_c.upper()}")
    print(f"  Mean Ic: {np.mean(results_by_c[c_name][best_c]):.6f}")
    print(f"  Mean fidelity range: [{np.min([np.mean(fidelities_by_c[c_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}, {np.max([np.mean(fidelities_by_c[c_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}]")
print("\n" + "="*80)
print(f"KEY STATISTICS SUMMARY (c = {c})")
print("="*80)
print(f"\nBest Protocol: {best_protocol.upper()}")
print(f"  Mean Ic: {stats_summary[best_protocol]['mean']:.6f}")
print(f"  Std Dev: {stats_summary[best_protocol]['std']:.6f}")
print(f"  Max Ic: {stats_summary[best_protocol]['max']:.6f}")
print(f"  Min Ic: {stats_summary[best_protocol]['min']:.6f}")
print(f"\nDiscard-Oldest Baseline:")
print(f"  Mean Ic: {stats_summary['discard']['mean']:.6f}")
print(f"  Mean Fidelity: {stats_summary['discard']['mean_fidelity']:.6f}")
print(f"\nTemporal Analysis (ASAP vs ALAP):")
print(f"  ASAP Mean: {temporal_stats['ASAP']['mean']:.6f} (Max: {temporal_stats['ASAP']['max']:.6f})")
print(f"  ALAP Mean: {temporal_stats['ALAP']['mean']:.6f} (Max: {temporal_stats['ALAP']['max']:.6f})")
print("\n" + "="*80)
print("ALL 3 PROTOCOLS PERFORMANCE TABLE")
print("="*80)
print(f"{'Protocol':<15} {'Mean Ic':>12} {'Std Dev':>12} {'Mean F':>12} {'Success':>12}")
print("-"*80)
for protocol in ['discard', 'asap', 'alap']:
    s = stats_summary[protocol]
    print(f"{protocol.upper():<15} {s['mean']:>12.6f} {s['std']:>12.6f} {s['mean_fidelity']:>12.6f} {s['mean_success_rate']:>12.4f}")
print("="*80)