# -*- coding: utf-8 -*-
"""SingleLinkAnalyticalCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVMlN7l-Gltm0qnk3ddBRGt_PiluVCBg
"""

# @title
# Single link code and result generation here
# Two arrivals only

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

plt.rcParams.update({
    'font.size': 13,
    'axes.labelsize': 16,
    'axes.titlesize': 17,
    'xtick.labelsize': 13,
    'ytick.labelsize': 13,
    'legend.fontsize': 12,
    'figure.titlesize': 18,
    'lines.linewidth': 2.4,
    'lines.markersize': 7
})

PROTOCOL_COLORS = {
    'discard': 'black',
    'asap': '#1f77b4',
    'alap': '#ff7f0e',
}

PROTOCOL_LABELS = {
    'discard': 'Discard-Oldest',
    'asap': 'Distill-ASAP',
    'alap': 'Distill-ALAP',
}

os.makedirs("figures_single_link", exist_ok=True)

SEED = 42
np.random.seed(SEED)
n_samples = 5000

lambda_vals_physical = [10.0, 1e4]
c_vals_physical = [0.1, 1.0, 100.0]

all_dataframes = []

def raw_fidelity(t_gen, t_total, c, F_init=0.9):
    A = 1/4
    B = F_init - A
    return np.clip(A + B * np.exp(-2 * (t_total - t_gen) / c), 0, 1)

def compute_fidelity(F_init, t_idle, c):
    A = 1/4
    B = F_init - A
    return np.clip(A + B * np.exp(-2 * t_idle / c), 0, 1)

def isotropic_purification_pairwise(F1, F2):
    num = F1 * F2 + (1/9) * (1 - F1) * (1 - F2)
    denom = (F1 * F2 + (1/3) * F1 * (1 - F2) + (1/3) * F2 * (1 - F1) + (5/9) * (1 - F1) * (1 - F2))
    return np.clip(num / denom, 0, 1)

def coherent_information_vectorized(F):
    λ1 = F
    λ_rest = (1 - F) / 3
    eigs = np.stack([λ1, λ_rest, λ_rest, λ_rest], axis=-1)
    S = -np.sum(eigs * np.log2(eigs + 1e-12), axis=-1)
    return np.maximum(0, 1 - S)

def generate_poisson_arrivals(lam, T, n_samples):
    X = np.random.exponential(1/lam, n_samples)
    X[X > T] = np.inf
    return X

def single_link_discard_oldest(n_samples, lam, c, T, samples):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)

    for i in range(n_samples):
        available = [t for t in [t1a[i], t2a[i]] if t < T]
        if len(available) > 0:
            F_final[i] = raw_fidelity(max(available), T, c, F_init=0.9)
            used[i] = True

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate
    std_Ic = 0.0

    return mean_Ic, std_Ic, F_mean, success_rate

def single_link_distill_asap(n_samples, lam, c, T, samples):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)
    p_success_all = np.ones(n_samples)

    for i in range(n_samples):
        if t1a[i] < T and t2a[i] < T:
            t_dist = max(t1a[i], t2a[i])
            F1 = raw_fidelity(t1a[i], t_dist, c, F_init=0.9)
            F2 = raw_fidelity(t2a[i], t_dist, c, F_init=0.9)
            F_pur = isotropic_purification_pairwise(F1, F2)
            F_final[i] = compute_fidelity(F_pur, T - t_dist, c)
            used[i] = True
            p_success_all[i] = F1 * F2 + (1/3) * F1 * (1 - F2) + (1/3) * F2 * (1 - F1) + (5/9) * (1 - F1) * (1 - F2)
        elif t1a[i] < T:
            F_final[i] = raw_fidelity(t1a[i], T, c, F_init=0.9)
            used[i] = True
        elif t2a[i] < T:
            F_final[i] = raw_fidelity(t2a[i], T, c, F_init=0.9)
            used[i] = True

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    p_success_mean = np.mean(p_success_all[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate * p_success_mean
    std_Ic = 0.0

    return mean_Ic, std_Ic, F_mean, success_rate

def single_link_distill_alap(n_samples, lam, c, T, samples):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)
    p_success_all = np.ones(n_samples)

    for i in range(n_samples):
        if t1a[i] < T and t2a[i] < T:
            F1 = raw_fidelity(t1a[i], T, c, F_init=0.9)
            F2 = raw_fidelity(t2a[i], T, c, F_init=0.9)
            F_final[i] = isotropic_purification_pairwise(F1, F2)
            used[i] = True
            p_success_all[i] = F1 * F2 + (1/3) * F1 * (1 - F2) + (1/3) * F2 * (1 - F1) + (5/9) * (1 - F1) * (1 - F2)
        elif t1a[i] < T:
            F_final[i] = raw_fidelity(t1a[i], T, c, F_init=0.9)
            used[i] = True
        elif t2a[i] < T:
            F_final[i] = raw_fidelity(t2a[i], T, c, F_init=0.9)
            used[i] = True

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    p_success_mean = np.mean(p_success_all[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate * p_success_mean
    std_Ic = 0.0

    return mean_Ic, std_Ic, F_mean, success_rate

print("\n" + "="*80)
print("COMPUTING PHYSICAL PARAMETER REGIMES")
print("="*80)

results_physical = {}
for lam in lambda_vals_physical:
    for c in c_vals_physical:
        key = f"lam{lam}_c{c}"
        print(f"\nProcessing λ={lam}/s, c={c}s...")

        T_min = 0.01 * c
        T_max = 0.2 * c
        T_vals = np.linspace(T_min, T_max, 30)

        results = {
            'T': T_vals,
            'discard_Ic': [], 'discard_F': [], 'discard_Pr': [],
            'asap_Ic': [], 'asap_F': [], 'asap_Pr': [],
            'alap_Ic': [], 'alap_F': [], 'alap_Pr': [],
        }

        for T in T_vals:
            np.random.seed(SEED)
            samples = {
                't_l1_1': generate_poisson_arrivals(lam, T, n_samples),
                't_l2_1': generate_poisson_arrivals(lam, T, n_samples)
            }

            mean_Ic, _, F_mean, Pr = single_link_discard_oldest(n_samples, lam, c, T, samples)
            results['discard_Ic'].append(mean_Ic)
            results['discard_F'].append(F_mean)
            results['discard_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = single_link_distill_asap(n_samples, lam, c, T, samples)
            results['asap_Ic'].append(mean_Ic)
            results['asap_F'].append(F_mean)
            results['asap_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = single_link_distill_alap(n_samples, lam, c, T, samples)
            results['alap_Ic'].append(mean_Ic)
            results['alap_F'].append(F_mean)
            results['alap_Pr'].append(Pr)

        results_physical[key] = results

        df = pd.DataFrame(results)
        df['Data_Section'] = f'Physical_Params_{key}'
        parts = key.replace('lam', '').split('_c')
        df['lambda'] = float(parts[0])
        df['c'] = float(parts[1])
        all_dataframes.append(df)

print("\n" + "="*80)
print("PARAMETER REGIME DIAGNOSTICS")
print("="*80)

for lam in lambda_vals_physical:
    for c in c_vals_physical:
        key = f"lam{lam}_c{c}"

        expected_gen_time = 1.0 / lam
        T_max = 0.2 * c
        ratio = T_max / expected_gen_time

        max_Ic = max([np.max(results_physical[key][f'{p}_Ic']) for p in ['discard', 'asap', 'alap']])

        if ratio < 0.5:
            status = "FAILED"
            reason = f"T_max ({T_max:.4f}s) much less than gen time ({expected_gen_time:.4f}s)"
        elif ratio < 1.0:
            status = "MARGINAL"
            reason = f"T_max ({T_max:.4f}s) less than gen time ({expected_gen_time:.4f}s)"
        elif max_Ic < 0.1:
            status = "LOW Ic"
            reason = f"T_max adequate but high decoherence"
        else:
            status = "GOOD"
            reason = f"T_max ({T_max:.4f}s) greater than gen time ({expected_gen_time:.4f}s)"

        print(f"\n{key}: {status}")
        print(f"  Expected generation time: {expected_gen_time:.6f}s")
        print(f"  T_max (coherence time): {T_max:.6f}s")
        print(f"  Ratio (T_max/gen_time): {ratio:.3f}")
        print(f"  Max coherent info: {max_Ic:.6f}")
        print(f"  Reason: {reason}")

print("\n" + "="*80)
print("SUMMARY")
print("="*80)

good_regimes = []
marginal_regimes = []
failed_regimes = []

for lam in lambda_vals_physical:
    for c in c_vals_physical:
        key = f"lam{lam}_c{c}"
        expected_gen_time = 1.0 / lam
        T_max = 0.2 * c
        ratio = T_max / expected_gen_time
        max_Ic = max([np.max(results_physical[key][f'{p}_Ic']) for p in ['discard', 'asap', 'alap']])

        if ratio >= 1.0 and max_Ic >= 0.1:
            good_regimes.append(key)
        elif ratio < 0.5:
            failed_regimes.append(key)
        else:
            marginal_regimes.append(key)

print(f"\nGOOD regimes ({len(good_regimes)}): {', '.join(good_regimes)}")
print(f"MARGINAL regimes ({len(marginal_regimes)}): {', '.join(marginal_regimes)}")
print(f"FAILED regimes ({len(failed_regimes)}): {', '.join(failed_regimes)}")

print("\n" + "="*80)

print("\n" + "="*80)
print("GENERATING FIGURES WITH PHYSICAL PARAMETERS")
print("="*80)

fig1 = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, c in enumerate(c_vals_physical):
        key = f"lam{lam}_c{c}"
        res = results_physical[key]

        plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_Ic'], label=PROTOCOL_LABELS['discard'],
                marker='D', color=PROTOCOL_COLORS['discard'], markersize=5)
        plt.plot(res['T'], res['asap_Ic'], label=PROTOCOL_LABELS['asap'],
                marker='o', color=PROTOCOL_COLORS['asap'], alpha=0.7)
        plt.plot(res['T'], res['alap_Ic'], label=PROTOCOL_LABELS['alap'],
                marker='s', color=PROTOCOL_COLORS['alap'], alpha=0.7)

        plt.title(f"λ={lam}/s, c={c}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Coherent Information")
        plt.grid(alpha=0.3)
        plt.legend(fontsize=9)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_single_link/physical_params_coherent_info_vs_T.pdf", dpi=300)
plt.show()

fig2 = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, c in enumerate(c_vals_physical):
        key = f"lam{lam}_c{c}"
        res = results_physical[key]

        plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_F'], label=PROTOCOL_LABELS['discard'],
                marker='D', color=PROTOCOL_COLORS['discard'], markersize=5)
        plt.plot(res['T'], res['asap_F'], label=PROTOCOL_LABELS['asap'],
                marker='o', color=PROTOCOL_COLORS['asap'], alpha=0.7)
        plt.plot(res['T'], res['alap_F'], label=PROTOCOL_LABELS['alap'],
                marker='s', color=PROTOCOL_COLORS['alap'], alpha=0.7)

        plt.title(f"λ={lam}/s, c={c}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Final Fidelity")
        plt.grid(alpha=0.3)
        plt.legend(fontsize=9)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_single_link/physical_params_fidelity_vs_T.pdf", dpi=300)
plt.show()

fig_pr = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, c in enumerate(c_vals_physical):
        key = f"lam{lam}_c{c}"
        res = results_physical[key]

        plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_Pr'], label=PROTOCOL_LABELS['discard'],
                marker='D', color=PROTOCOL_COLORS['discard'], markersize=5)
        plt.plot(res['T'], res['asap_Pr'], label=PROTOCOL_LABELS['asap'],
                marker='o', color=PROTOCOL_COLORS['asap'], alpha=0.7)
        plt.plot(res['T'], res['alap_Pr'], label=PROTOCOL_LABELS['alap'],
                marker='s', color=PROTOCOL_COLORS['alap'], alpha=0.7)

        plt.title(f"λ={lam}/s, c={c}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Pr(success)")
        plt.grid(alpha=0.3)
        plt.legend(fontsize=9)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_single_link/physical_params_success_prob_vs_T.pdf", dpi=300)
plt.show()

print("\n" + "="*80)
print("SUMMARY OF PHYSICAL PARAMETER REGIMES")
print("="*80)
for key, res in results_physical.items():
    print(f"\n{key}:")
    for protocol in ['discard', 'asap', 'alap']:
        max_Ic = np.max(res[f'{protocol}_Ic'])
        max_F = np.max(res[f'{protocol}_F'])
        mean_Ic = np.mean(res[f'{protocol}_Ic'])
        mean_Pr = np.mean(res[f'{protocol}_Pr'])
        print(f"  {PROTOCOL_LABELS[protocol]}: Max Ic={max_Ic:.6f}, Max F={max_F:.6f}, Mean Ic={mean_Ic:.6f}, Mean Pr={mean_Pr:.6f}")

print("\n" + "="*80)
print("GENERATING ADDITIONAL FIGURES")
print("="*80)

lambda_vals = np.linspace(0.1, 2.0, 20)
c_regimes = {'small': 0.5, 'medium': 10.0, 'large': 50.0}

results_by_c = {}
fidelities_by_c = {}
success_rates_by_c = {}

for c_name, c_val in c_regimes.items():
    print(f"\nProcessing c = {c_val} ({c_name})...")
    results = {'discard': [], 'asap': [], 'alap': []}
    fidelities = {'discard': [], 'asap': [], 'alap': []}
    success_rates = {'discard': [], 'asap': [], 'alap': []}
    std_vals = {'discard': [], 'asap': [], 'alap': []}

    for lam in lambda_vals:
        np.random.seed(SEED)
        T = 2.0 / lam

        samples = {
            't_l1_1': generate_poisson_arrivals(lam, T, n_samples),
            't_l2_1': generate_poisson_arrivals(lam, T, n_samples)
        }

        mean, std, fid, succ = single_link_discard_oldest(n_samples, lam, c_val, T, samples)
        results['discard'].append(mean)
        std_vals['discard'].append(std)
        fidelities['discard'].append(fid)
        success_rates['discard'].append(succ)

        mean, std, fid, succ = single_link_distill_asap(n_samples, lam, c_val, T, samples)
        results['asap'].append(mean)
        std_vals['asap'].append(std)
        fidelities['asap'].append(fid)
        success_rates['asap'].append(succ)

        mean, std, fid, succ = single_link_distill_alap(n_samples, lam, c_val, T, samples)
        results['alap'].append(mean)
        std_vals['alap'].append(std)
        fidelities['alap'].append(fid)
        success_rates['alap'].append(succ)

    results_by_c[c_name] = results
    fidelities_by_c[c_name] = fidelities
    success_rates_by_c[c_name] = success_rates
    results_by_c[c_name]['std_vals'] = std_vals

c = c_regimes['medium']
results_3protocols = {k: results_by_c['medium'][k] for k in ['discard', 'asap', 'alap']}
std_3protocols = results_by_c['medium']['std_vals']

T_vals = np.linspace(0.2, 2.0, 18)
lambda_fixed = 1.0
np.random.seed(SEED)
Ic_asap_T, Ic_alap_T = [], []
for T_test in T_vals:
    samples_fixed = {
        't_l1_1': generate_poisson_arrivals(lambda_fixed, T_test, n_samples),
        't_l2_1': generate_poisson_arrivals(lambda_fixed, T_test, n_samples)
    }
    Ic_asap_T.append(single_link_distill_asap(n_samples, lambda_fixed, c, T_test, samples_fixed)[0])
    Ic_alap_T.append(single_link_distill_alap(n_samples, lambda_fixed, c, T_test, samples_fixed)[0])

def single_link_discard_oldest_distribution(n_samples, lam, c, T, samples):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = []

    for i in range(n_samples):
        available = [t for t in [t1a[i], t2a[i]] if t < T]
        if len(available) > 0:
            F_final.append(raw_fidelity(max(available), T, c, F_init=0.9))

    F_arr = np.array(F_final)
    I_c = coherent_information_vectorized(F_arr)
    return F_arr, I_c

def single_link_distill_alap_distribution(n_samples, lam, c, T, samples):
    t1a, t2a = samples['t_l1_1'], samples['t_l2_1']
    F_final = []
    for i in range(n_samples):
        if t1a[i] < T and t2a[i] < T:
            F1 = raw_fidelity(t1a[i], T, c, F_init=0.9)
            F2 = raw_fidelity(t2a[i], T, c, F_init=0.9)
            F_final.append(isotropic_purification_pairwise(F1, F2))
        elif t1a[i] < T:
            F_final.append(raw_fidelity(t1a[i], T, c, F_init=0.9))
        elif t2a[i] < T:
            F_final.append(raw_fidelity(t2a[i], T, c, F_init=0.9))
    F_arr = np.array(F_final)
    I_c = coherent_information_vectorized(F_arr)
    return F_arr, I_c

lam_hist = 1.0
c_hist = c
T_hist = 2.0 / lam_hist
n_samples_hist = 100000
np.random.seed(SEED)
samples_hist = {
    't_l1_1': generate_poisson_arrivals(lam_hist, T_hist, n_samples_hist),
    't_l2_1': generate_poisson_arrivals(lam_hist, T_hist, n_samples_hist)
}
F_alap, Ic_alap = single_link_distill_alap_distribution(n_samples_hist, lam_hist, c_hist, T_hist, samples_hist)
F_discard, Ic_discard = single_link_discard_oldest_distribution(n_samples_hist, lam_hist, c_hist, T_hist, samples_hist)

F0_list = [0.45, 0.49, 0.51, 0.6, 0.8]
purif_threshold = {}
for F0 in F0_list:
    F = F0
    seq = [F0]
    for _ in range(10):
        F = isotropic_purification_pairwise(F, F)
        seq.append(F)
    purif_threshold[F0] = seq

def recurrence_yield(F0, n_raw=4000, rounds=5):
    arr = np.full(n_raw, F0)
    for _ in range(rounds):
        if len(arr) < 2:
            break
        idx = np.random.permutation(len(arr))
        if len(idx) % 2:
            idx = idx[:-1]
        p = idx.reshape(-1, 2)
        arr = isotropic_purification_pairwise(arr[p[:,0]], arr[p[:,1]])
    return len(arr)/n_raw

F0s_yield = np.linspace(0.52, 0.95, 10)
yields = [np.mean([recurrence_yield(f) for _ in range(5)]) for f in F0s_yield]

N_list = [2, 4, 8, 16, 32]
Ic_scaling_sim = []
lam_example, T_example = 1.0, 20.0
for seg in N_list:
    reps = []
    for _ in range(1500):
        Fs = [0.25 + 0.65*np.exp(-2*(T_example-np.random.exponential(1/lam_example))/c) for __ in range(seg)]
        F_result = Fs[0]
        for j in range(1, len(Fs)):
            F_temp = isotropic_purification_pairwise(F_result, Fs[j]) if j < len(Fs) else F_result
            F_result = F_temp
        reps.append(F_result)
    Ic_scaling_sim.append(np.mean(coherent_information_vectorized(np.array(reps))))

fig3 = plt.figure(figsize=(7,5))
plt.plot(T_vals, Ic_asap_T, label=PROTOCOL_LABELS['asap'], marker='o', color=PROTOCOL_COLORS['asap'])
plt.plot(T_vals, Ic_alap_T, label=PROTOCOL_LABELS['alap'], marker='s', color=PROTOCOL_COLORS['alap'])
plt.xlabel("T (time units)")
plt.ylabel("Coherent Information")
plt.legend()
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/Ic_vs_T_both_protocols.pdf", dpi=300)
plt.show()

fig4 = plt.figure(figsize=(7,5))
plt.plot(lambda_vals, results_3protocols['asap'], label=PROTOCOL_LABELS['asap'], marker='o', color=PROTOCOL_COLORS['asap'])
plt.plot(lambda_vals, results_3protocols['alap'], label=PROTOCOL_LABELS['alap'], marker='s', color=PROTOCOL_COLORS['alap'])
plt.xlabel("λ (Rate, 1/time units)")
plt.ylabel("Coherent Information")
plt.grid()
plt.legend()
plt.tight_layout()
plt.savefig("figures_single_link/Ic_vs_lambda_strategy_comparison.pdf", dpi=300)
plt.show()

fig6 = plt.figure(figsize=(7,5))
plt.hist(F_alap, bins=60, density=True, color='skyblue', edgecolor='black', alpha=0.7, label=PROTOCOL_LABELS['alap'])
plt.hist(F_discard, bins=60, density=True, color='lightcoral', edgecolor='black', alpha=0.5, label=PROTOCOL_LABELS['discard'])
plt.xlabel("Final Fidelity", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.title(f"Fidelity Distribution (λ={lam_hist}, c={c_hist}, T={T_hist:.1f})", fontsize=13, fontweight='bold')
plt.legend(fontsize=10)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures_single_link/fidelity_histogram_example.pdf", dpi=300)
plt.show()

fig7 = plt.figure(figsize=(7,5))
Ic_alap_pos = Ic_alap[Ic_alap > 0]
Ic_discard_pos = Ic_discard[Ic_discard > 0]
if len(Ic_alap_pos) > 0:
    plt.hist(Ic_alap_pos, bins=60, density=True, color='mediumseagreen', edgecolor='black', alpha=0.7, label=f'{PROTOCOL_LABELS["alap"]} ({len(Ic_alap_pos)} samples)')
if len(Ic_discard_pos) > 0:
    plt.hist(Ic_discard_pos, bins=60, density=True, color='orange', edgecolor='black', alpha=0.5, label=f'{PROTOCOL_LABELS["discard"]} ({len(Ic_discard_pos)} samples)')
plt.xlabel("Coherent Information", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.title(f"Coherent Information Distribution (Ic > 0)\n(λ={lam_hist}, c={c_hist}, T={T_hist:.1f})", fontsize=13, fontweight='bold')
plt.legend(fontsize=9)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures_single_link/coherent_info_histogram_example.pdf", dpi=300)
plt.show()

fig8 = plt.figure(figsize=(6,4))
for F0 in F0_list:
    plt.plot(purif_threshold[F0], label=f"$F_0$={F0:.2f}", marker='o')
plt.axhline(0.5, color='k', ls='--', label='Threshold')
plt.legend(fontsize=8)
plt.xlabel("Iteration")
plt.ylabel("Fidelity")
plt.title("Purification Threshold Behavior")
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/fig_purification_threshold.pdf", dpi=300)
plt.show()

fig9 = plt.figure(figsize=(6,4))
plt.plot(F0s_yield, yields, marker='o', color='green')
plt.xlabel("Initial Fidelity $F_0$")
plt.ylabel("Yield")
plt.title("Recurrence Purification Yield")
plt.grid()
plt.tight_layout()
plt.savefig("figures_single_link/fig_recurrence_yield.pdf", dpi=300)
plt.show()

fig10 = plt.figure(figsize=(6,4))
plt.plot(N_list, Ic_scaling_sim, marker='o', label='Simulation')
plt.xscale('log', base=2)
plt.xlabel("Segments N")
plt.ylabel("Coherent Information")
plt.title("Single-Link Repeater Scaling")
plt.grid(which='both', ls='--')
plt.legend()
plt.tight_layout()
plt.savefig("figures_single_link/fig_repeater_scaling.pdf", dpi=300)
plt.show()

fig11 = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, results_3protocols['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color=PROTOCOL_COLORS['discard'], markersize=7)
plt.plot(lambda_vals, results_3protocols['asap'], label=PROTOCOL_LABELS['asap'], marker='o', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_3protocols['alap'], label=PROTOCOL_LABELS['alap'], marker='s', linewidth=2, alpha=0.7)
plt.title(f"Three Protocol Comparison", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Coherent Information", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', fontsize=10)
plt.tight_layout()
plt.savefig("figures_single_link/all_protocols_comparison.pdf", dpi=300)
plt.show()

fig_pr_lambda = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, success_rates_by_c['medium']['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color=PROTOCOL_COLORS['discard'], markersize=7)
plt.plot(lambda_vals, success_rates_by_c['medium']['asap'], label=PROTOCOL_LABELS['asap'], marker='o', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_rates_by_c['medium']['alap'], label=PROTOCOL_LABELS['alap'], marker='s', linewidth=2, alpha=0.7)
plt.title("Success Probability vs λ", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Pr(success)", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', fontsize=10)
plt.tight_layout()
plt.savefig("figures_single_link/success_prob_vs_lambda.pdf", dpi=300)
plt.show()

df_3protocols = pd.DataFrame({
    'lambda': lambda_vals,
    'Discard-Oldest_mean': results_3protocols['discard'],
    'Distill-ASAP_mean': results_3protocols['asap'],
    'Distill-ALAP_mean': results_3protocols['alap']
})
df_3protocols['Data_Section'] = 'All_Protocols'
all_dataframes.append(df_3protocols)

df_regimes = pd.DataFrame({
    'lambda': lambda_vals,
    **{f'{c_name}_discard_Ic': results_by_c[c_name]['discard'] for c_name in c_regimes.keys()},
    **{f'{c_name}_discard_F': fidelities_by_c[c_name]['discard'] for c_name in c_regimes.keys()},
    **{f'{c_name}_discard_Pr': success_rates_by_c[c_name]['discard'] for c_name in c_regimes.keys()},
    **{f'{c_name}_asap_Ic': results_by_c[c_name]['asap'] for c_name in c_regimes.keys()},
    **{f'{c_name}_asap_F': fidelities_by_c[c_name]['asap'] for c_name in c_regimes.keys()},
    **{f'{c_name}_asap_Pr': success_rates_by_c[c_name]['asap'] for c_name in c_regimes.keys()},
    **{f'{c_name}_alap_Ic': results_by_c[c_name]['alap'] for c_name in c_regimes.keys()},
    **{f'{c_name}_alap_F': fidelities_by_c[c_name]['alap'] for c_name in c_regimes.keys()},
    **{f'{c_name}_alap_Pr': success_rates_by_c[c_name]['alap'] for c_name in c_regimes.keys()},
})
df_regimes['Data_Section'] = 'Parameter_Regimes'
all_dataframes.append(df_regimes)

stats_summary = {
    PROTOCOL_LABELS['discard']: {'mean': np.mean(results_3protocols['discard']), 'std': np.std(results_3protocols['discard']), 'max': np.max(results_3protocols['discard']), 'min': np.min(results_3protocols['discard'])},
    PROTOCOL_LABELS['asap']: {'mean': np.mean(results_3protocols['asap']), 'std': np.std(results_3protocols['asap']), 'max': np.max(results_3protocols['asap']), 'min': np.min(results_3protocols['asap'])},
    PROTOCOL_LABELS['alap']: {'mean': np.mean(results_3protocols['alap']), 'std': np.std(results_3protocols['alap']), 'max': np.max(results_3protocols['alap']), 'min': np.min(results_3protocols['alap'])}
}

df_stats = pd.DataFrame(stats_summary).T
df_stats['Protocol'] = df_stats.index
df_stats['Data_Section'] = 'Protocol_Statistics'
all_dataframes.append(df_stats.reset_index(drop=True))

temporal_stats = {
    'ASAP': {'mean': np.mean(Ic_asap_T), 'std': np.std(Ic_asap_T), 'max': np.max(Ic_asap_T), 'min': np.min(Ic_asap_T)},
    'ALAP': {'mean': np.mean(Ic_alap_T), 'std': np.std(Ic_alap_T), 'max': np.max(Ic_alap_T), 'min': np.min(Ic_alap_T)}
}
df_temporal = pd.DataFrame(temporal_stats).T
df_temporal['Protocol'] = df_temporal.index
df_temporal['Data_Section'] = 'Temporal_Analysis'
all_dataframes.append(df_temporal.reset_index(drop=True))

fidelity_stats = {
    'Fsw_mean': np.mean(F_alap), 'Fsw_std': np.std(F_alap), 'Fsw_min': np.min(F_alap), 'Fsw_max': np.max(F_alap),
    'Ic_mean': np.mean(Ic_alap), 'Ic_std': np.std(Ic_alap), 'Ic_min': np.min(Ic_alap), 'Ic_max': np.max(Ic_alap)
}
df_fidelity = pd.DataFrame([fidelity_stats])
df_fidelity['Data_Section'] = 'Fidelity_Distribution'
all_dataframes.append(df_fidelity)

best_protocol = max(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
worst_protocol = min(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
improvement_vs_discard = ((stats_summary[best_protocol]['mean'] - stats_summary[PROTOCOL_LABELS['discard']]['mean']) / stats_summary[PROTOCOL_LABELS['discard']]['mean'] * 100) if stats_summary[PROTOCOL_LABELS['discard']]['mean'] != 0 else float('inf')

comparison_metrics = {
    'best_protocol': best_protocol,
    'best_mean_Ic': stats_summary[best_protocol]['mean'],
    'best_max_Ic': stats_summary[best_protocol]['max'],
    'worst_protocol': worst_protocol,
    'worst_mean_Ic': stats_summary[worst_protocol]['mean'],
    'improvement_vs_discard_pct': improvement_vs_discard,
    'discard_mean': stats_summary[PROTOCOL_LABELS['discard']]['mean'],
    'asap_mean_temporal': temporal_stats['ASAP']['mean'],
    'alap_mean_temporal': temporal_stats['ALAP']['mean'],
    'asap_max_temporal': temporal_stats['ASAP']['max'],
    'alap_max_temporal': temporal_stats['ALAP']['max'],
    'temporal_improvement_pct': ((temporal_stats['ALAP']['mean'] - temporal_stats['ASAP']['mean']) / temporal_stats['ASAP']['mean'] * 100) if temporal_stats['ASAP']['mean'] != 0 else float('inf')
}
df_comparison = pd.DataFrame([comparison_metrics])
df_comparison['Data_Section'] = 'Key_Comparisons'
all_dataframes.append(df_comparison)

df_combined = pd.concat(all_dataframes, ignore_index=True, sort=False)
df_combined.to_csv("figures_single_link/single_link_combined_data.csv", index=False)

print("\n" + "="*80)
print("FIGURE GENERATION COMPLETE")
print("="*80)
print(f"\nAll figures saved to: figures_single_link/")
print(f"Total figures generated: 13")
print("\nFigure List:")
print("  1. physical_params_coherent_info_vs_T.pdf")
print("  2. physical_params_fidelity_vs_T.pdf")
print("  3. physical_params_success_prob_vs_T.pdf")
print("  4. Ic_vs_T_both_protocols.pdf")
print("  5. Ic_vs_lambda_strategy_comparison.pdf")
print("  6. fidelity_histogram_example.pdf")
print("  7. coherent_info_histogram_example.pdf")
print("  8. fig_purification_threshold.pdf")
print("  9. fig_recurrence_yield.pdf")
print(" 10. fig_repeater_scaling.pdf")
print(" 11. all_protocols_comparison.pdf")
print(" 12. success_prob_vs_lambda.pdf")

print("\n" + "="*80)
print("PARAMETER REGIME COMPARISON")
print("="*80)
for c_name, c_val in c_regimes.items():
    print(f"\nc = {c_val} ({c_name}):")
    print(f"  Best protocol (Ic): {max(['discard', 'asap', 'alap'], key=lambda p: np.mean(results_by_c[c_name][p]))}")
    print(f"  Mean fidelity range: [{np.min([np.mean(fidelities_by_c[c_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}, {np.max([np.mean(fidelities_by_c[c_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}]")
    print(f"  Mean success prob range: [{np.min([np.mean(success_rates_by_c[c_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}, {np.max([np.mean(success_rates_by_c[c_name][p]) for p in ['discard', 'asap', 'alap']]):.4f}]")

print("\n" + "="*80)
print("KEY STATISTICS SUMMARY (c = {})".format(c))
print("="*80)
print(f"\nBest Protocol: {best_protocol}")
print(f"  Mean Ic: {stats_summary[best_protocol]['mean']:.6f}")
print(f"  Std Dev: {stats_summary[best_protocol]['std']:.6f}")
print(f"  Max Ic: {stats_summary[best_protocol]['max']:.6f}")
print(f"  Min Ic: {stats_summary[best_protocol]['min']:.6f}")
print(f"\nWorst Protocol: {worst_protocol}")
print(f"  Mean Ic: {stats_summary[worst_protocol]['mean']:.6f}")
print(f"\n{PROTOCOL_LABELS['discard']} Baseline:")
print(f"  Mean Ic: {stats_summary[PROTOCOL_LABELS['discard']]['mean']:.6f}")
print(f"  Mean Fidelity: {np.mean(fidelities_by_c['medium']['discard']):.6f}")
print(f"  Mean Success Prob: {np.mean(success_rates_by_c['medium']['discard']):.6f}")
print(f"\nPerformance Improvement:")
print(f"  Best vs Discard-Oldest: {improvement_vs_discard:+.2f}%")
print(f"\nTemporal Analysis (ASAP vs ALAP):")
print(f"  ASAP Mean: {temporal_stats['ASAP']['mean']:.6f} (Max: {temporal_stats['ASAP']['max']:.6f})")
print(f"  ALAP Mean: {temporal_stats['ALAP']['mean']:.6f} (Max: {temporal_stats['ALAP']['max']:.6f})")
print(f"  ALAP improvement: {comparison_metrics['temporal_improvement_pct']:+.2f}%")
print(f"\nFidelity Distribution Statistics:")
print(f"  Mean Fidelity: {fidelity_stats['Fsw_mean']:.4f} ± {fidelity_stats['Fsw_std']:.4f}")
print(f"  Range: [{fidelity_stats['Fsw_min']:.4f}, {fidelity_stats['Fsw_max']:.4f}]")
print(f"  Mean Ic: {fidelity_stats['Ic_mean']:.4f} ± {fidelity_stats['Ic_std']:.4f}")
print("\n" + "="*80)
print("ALL 3 PROTOCOLS PERFORMANCE TABLE")
print("="*80)
print(f"{'Protocol':<20} {'Mean Ic':>12} {'Std Dev':>12} {'Max Ic':>12} {'Min Ic':>12}")
print("-"*80)
for protocol in [PROTOCOL_LABELS[k] for k in ['discard', 'asap', 'alap']]:
    s = stats_summary[protocol]
    print(f"{protocol:<20} {s['mean']:>12.6f} {s['std']:>12.6f} {s['max']:>12.6f} {s['min']:>12.6f}")
print("="*80)
print("\nAll data saved to single CSV file:")
print("  - figures_single_link/single_link_combined_data.csv")
print("    Contains sections: Physical_Params (6 regimes), All_Protocols,")
print("    Parameter_Regimes, Protocol_Statistics, Temporal_Analysis,")
print("    Fidelity_Distribution, Key_Comparisons")
print("="*80)