# -*- coding: utf-8 -*-
"""SucessRateForSingleAndDoubleCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVMlN7l-Gltm0qnk3ddBRGt_PiluVCBg
"""

# @title
# Testing updated success rate calculations below.
# Success rate calculations
import numpy as np
import pandas as pd

SEED = 42
np.random.seed(SEED)

def coherent_information(F):
    F = np.clip(F, 1e-12, 1 - 1e-12)
    lambda1 = F
    lambda_rest = (1 - F) / 3
    eigs = np.array([lambda1, lambda_rest, lambda_rest, lambda_rest])
    S = -np.sum(eigs * np.log2(eigs + 1e-12))
    return np.maximum(0, 1 - S)

def coherent_information_vectorized(F):
    λ1 = F
    λ_rest = (1 - F) / 3
    eigs = np.stack([λ1, λ_rest, λ_rest, λ_rest], axis=-1)
    S = -np.sum(eigs * np.log2(eigs + 1e-12), axis=-1)
    return np.maximum(0, 1 - S)

def raw_fidelity(t_gen, t_total, c, F_init=0.9):
    A = 1/4
    B = F_init - A
    return np.clip(A + B * np.exp(-2 * (t_total - t_gen) / c), 0, 1)

def compute_fidelity(F_init, t_idle, c):
    A = 1/4
    B = F_init - A
    return np.clip(A + B * np.exp(-2 * t_idle / c), 0, 1)

def isotropic_purification_pairwise(F1, F2):
    num = F1 * F2 + (1/9) * (1 - F1) * (1 - F2)
    denom = (F1 * F2 + (1/3) * F1 * (1 - F2) + (1/3) * F2 * (1 - F1) + (5/9) * (1 - F1) * (1 - F2))
    return np.clip(num / denom, 0, 1)

def swapped_fidelity(F1, F2):
    return np.clip(F1 * F2 + (1 - F1) * (1 - F2) / 3, 0, 1)

def state_availability(t1a, t1b, t2a, t2b, T):
    available = np.zeros(len(t1a), dtype=int)
    available += (t1a < T).astype(int) + (t1b < T).astype(int) + (t2a < T).astype(int) + (t2b < T).astype(int)
    return available

def discard_oldest_analytical(lam, c, T, F0=0.9):
    eps = 1e-8
    expLT = np.exp(-lam * T)
    exp2LT = np.exp(-2 * lam * T)
    exp2Tc = np.exp(-2 * T / c)
    F0_eff = F0 - 0.25

    term1 = 0.25 - 0.25 * exp2LT
    coeff = 2 * lam * F0_eff

    denom1 = lam - 2/c
    if abs(denom1) < eps:
        bracket1 = T * (expLT + 1) * exp2Tc
    else:
        bracket1 = (expLT + 1) * (exp2Tc - expLT) / denom1

    denom2 = 2*lam - 2/c
    if abs(denom2) < eps:
        bracket2 = T * exp2Tc
    else:
        bracket2 = (exp2Tc - exp2LT) / denom2

    term2 = coeff * (bracket1 - bracket2)

    Fbar = (term1 + term2) / (1 - exp2LT + eps)
    Fbar = np.clip(Fbar, 0, 1)
    success_rate = 1 - exp2LT
    R = success_rate * coherent_information(Fbar)

    return Fbar, R, success_rate

def distill_alap_analytical(lam, c, T, F0=0.9):
    eps = 1e-8
    L = lam
    lam_orig = lam

    if abs(c * L - 2) < 0.05:
        delta = 0.02
        lam_low = (2.0 - delta) / c
        lam_high = (2.0 + delta) / c
        T_low = 2.0 / lam_low
        T_high = 2.0 / lam_high

        L_low = lam_low
        expLT_low = np.exp(-L_low * T_low)
        exp2LT_low = np.exp(-2 * L_low * T_low)
        exp2Tc_low = np.exp(-2 * T_low / c)
        expSum_low = np.exp(-T_low * (2/c + L_low))
        cL_low = c * L_low

        num1_low = 5 * c * c * (1 - 4*F0) * (1 - 4*F0) * L_low * L_low * np.exp(-4*T_low/c)
        num2_low = 6 * c * (4*F0 - 1) * L_low * (cL_low - 2) * exp2Tc_low
        num3_low = -20 * c * (4*F0 - 1) * L_low * (2*c*(F0-1)*L_low + 3) * expSum_low
        num4_low = -12 * (cL_low - 2) * expLT_low * (2*c*(F0-1)*L_low + 3)
        num5_inner_low = 8*cL_low*(10*F0*(c*(F0-2)*L_low + 3) + cL_low + 6) - 108
        num5_low = exp2LT_low * num5_inner_low
        num6_low = 9 * (cL_low - 2) * (cL_low - 2)
        numerator_low = num1_low + num2_low + num3_low + num4_low + num5_low + num6_low

        denom_factor_low = 4 * (cL_low - 2) * (cL_low - 2)
        denom1_low = (c*c * (1-4*F0)*(1-4*F0) * L_low*L_low * np.exp(-4*T_low/c)) / ((cL_low-2)*(cL_low-2))
        denom2_low = -(2 * c*c * (1-4*F0)*(1-4*F0) * L_low*L_low * expSum_low) / ((cL_low-2)*(cL_low-2))
        denom3_inner_low = cL_low * (c * (8*F0*F0 - 4*F0 - 13) * L_low + 54) - 54
        denom3_low = (2 * exp2LT_low * denom3_inner_low) / ((cL_low-2)*(cL_low-2))
        denom4_low = 18 * expLT_low + 9
        denominator_low = denom_factor_low * (denom1_low + denom2_low + denom3_low + denom4_low)
        Fbar_low = numerator_low / (denominator_low + eps)

        p_succ_term1_low = (c*c * (1-4*F0)*(1-4*F0) * L_low*L_low * np.exp(-4*T_low/c)) / ((cL_low-2)*(cL_low-2))
        p_succ_term2_low = -(2 * c*c * (1-4*F0)*(1-4*F0) * L_low*L_low * expSum_low) / ((cL_low-2)*(cL_low-2))
        p_succ_term3_inner_low = cL_low * (c*(8*F0*F0 - 4*F0 - 13)*L_low + 54) - 54
        p_succ_term3_low = (2 * exp2LT_low * p_succ_term3_inner_low) / ((cL_low-2)*(cL_low-2))
        p_succ_term4_low = 18 * expLT_low + 9
        p_succ_mean_low = (1/18) * (p_succ_term1_low + p_succ_term2_low + p_succ_term3_low + p_succ_term4_low)

        L_high = lam_high
        expLT_high = np.exp(-L_high * T_high)
        exp2LT_high = np.exp(-2 * L_high * T_high)
        exp2Tc_high = np.exp(-2 * T_high / c)
        expSum_high = np.exp(-T_high * (2/c + L_high))
        cL_high = c * L_high

        num1_high = 5 * c * c * (1 - 4*F0) * (1 - 4*F0) * L_high * L_high * np.exp(-4*T_high/c)
        num2_high = 6 * c * (4*F0 - 1) * L_high * (cL_high - 2) * exp2Tc_high
        num3_high = -20 * c * (4*F0 - 1) * L_high * (2*c*(F0-1)*L_high + 3) * expSum_high
        num4_high = -12 * (cL_high - 2) * expLT_high * (2*c*(F0-1)*L_high + 3)
        num5_inner_high = 8*cL_high*(10*F0*(c*(F0-2)*L_high + 3) + cL_high + 6) - 108
        num5_high = exp2LT_high * num5_inner_high
        num6_high = 9 * (cL_high - 2) * (cL_high - 2)
        numerator_high = num1_high + num2_high + num3_high + num4_high + num5_high + num6_high

        denom_factor_high = 4 * (cL_high - 2) * (cL_high - 2)
        denom1_high = (c*c * (1-4*F0)*(1-4*F0) * L_high*L_high * np.exp(-4*T_high/c)) / ((cL_high-2)*(cL_high-2))
        denom2_high = -(2 * c*c * (1-4*F0)*(1-4*F0) * L_high*L_high * expSum_high) / ((cL_high-2)*(cL_high-2))
        denom3_inner_high = cL_high * (c * (8*F0*F0 - 4*F0 - 13) * L_high + 54) - 54
        denom3_high = (2 * exp2LT_high * denom3_inner_high) / ((cL_high-2)*(cL_high-2))
        denom4_high = 18 * expLT_high + 9
        denominator_high = denom_factor_high * (denom1_high + denom2_high + denom3_high + denom4_high)
        Fbar_high = numerator_high / (denominator_high + eps)

        p_succ_term1_high = (c*c * (1-4*F0)*(1-4*F0) * L_high*L_high * np.exp(-4*T_high/c)) / ((cL_high-2)*(cL_high-2))
        p_succ_term2_high = -(2 * c*c * (1-4*F0)*(1-4*F0) * L_high*L_high * expSum_high) / ((cL_high-2)*(cL_high-2))
        p_succ_term3_inner_high = cL_high * (c*(8*F0*F0 - 4*F0 - 13)*L_high + 54) - 54
        p_succ_term3_high = (2 * exp2LT_high * p_succ_term3_inner_high) / ((cL_high-2)*(cL_high-2))
        p_succ_term4_high = 18 * expLT_high + 9
        p_succ_mean_high = (1/18) * (p_succ_term1_high + p_succ_term2_high + p_succ_term3_high + p_succ_term4_high)

        alpha = (lam - lam_low) / (lam_high - lam_low)
        Fbar = Fbar_low * (1 - alpha) + Fbar_high * alpha
        p_succ_mean = p_succ_mean_low * (1 - alpha) + p_succ_mean_high * alpha
    else:
        expLT = np.exp(-L * T)
        exp2LT = np.exp(-2 * L * T)
        exp2Tc = np.exp(-2 * T / c)
        expSum = np.exp(-T * (2/c + L))
        cL = c * L

        num1 = 5 * c * c * (1 - 4*F0) * (1 - 4*F0) * L * L * np.exp(-4*T/c)
        num2 = 6 * c * (4*F0 - 1) * L * (cL - 2) * exp2Tc
        num3 = -20 * c * (4*F0 - 1) * L * (2*c*(F0-1)*L + 3) * expSum
        num4 = -12 * (cL - 2) * expLT * (2*c*(F0-1)*L + 3)
        num5_inner = 8*cL*(10*F0*(c*(F0-2)*L + 3) + cL + 6) - 108
        num5 = exp2LT * num5_inner
        num6 = 9 * (cL - 2) * (cL - 2)
        numerator = num1 + num2 + num3 + num4 + num5 + num6

        denom_factor = 4 * (cL - 2) * (cL - 2)

        denom1 = (c*c * (1-4*F0)*(1-4*F0) * L*L * np.exp(-4*T/c)) / ((cL-2)*(cL-2))
        denom2 = -(2 * c*c * (1-4*F0)*(1-4*F0) * L*L * expSum) / ((cL-2)*(cL-2))
        denom3_inner = cL * (c * (8*F0*F0 - 4*F0 - 13) * L + 54) - 54
        denom3 = (2 * exp2LT * denom3_inner) / ((cL-2)*(cL-2))
        denom4 = 18 * expLT + 9
        denominator = denom_factor * (denom1 + denom2 + denom3 + denom4)

        Fbar = numerator / (denominator + eps)

        p_succ_term1 = (c*c * (1-4*F0)*(1-4*F0) * L*L * np.exp(-4*T/c)) / ((cL-2)*(cL-2))
        p_succ_term2 = -(2 * c*c * (1-4*F0)*(1-4*F0) * L*L * expSum) / ((cL-2)*(cL-2))
        p_succ_term3_inner = cL * (c*(8*F0*F0 - 4*F0 - 13)*L + 54) - 54
        p_succ_term3 = (2 * exp2LT * p_succ_term3_inner) / ((cL-2)*(cL-2))
        p_succ_term4 = 18 * expLT + 9

        p_succ_mean = (1/18) * (p_succ_term1 + p_succ_term2 + p_succ_term3 + p_succ_term4)

    Fbar = np.clip(Fbar, 0, 1)
    p_succ_mean = np.clip(p_succ_mean, 0, 1)

    exp2LT_orig = np.exp(-2 * lam_orig * T)
    success_rate = 1 - exp2LT_orig
    R = success_rate * p_succ_mean * coherent_information(Fbar)

    return Fbar, R, success_rate

def distill_asap_analytical(lam, c, T, F0=0.9):
    eps = 1e-8
    lam_orig = lam

    if abs(c*lam - 2) < eps:
        lam = lam * (1 + 1e-10)

    numerator = (-6 * np.exp(2*T/c + 3*T*lam) * (-1 + c*lam) * (2 + c*lam) * (3 + 2*c*(-1 + F0)*lam) -
                 2*c * np.exp(3*T*lam) * (-1 + 4*F0) * lam * (-1 + c*lam) * (-19 + 16*F0 + 10*c*(-1 + F0)*lam) +
                 np.exp(2*T*(1/c + 2*lam)) * (-2 + c*lam) * (-1 + c*lam) * (9 + c*(5 - 4*F0 + 8*F0**2)*lam) +
                 c * np.exp(4*T*lam) * (-1 + 4*F0) * lam * (2 + c*lam) * (1 + c*lam + 8*F0*(-2 + c*lam)) +
                 np.exp(2*T*(1/c + lam)) * (2 + c*lam) * (-27 + c*lam*(25 + 4*c*lam + 8*F0*(8 - F0 + 5*c*(-2 + F0)*lam))))

    denominator = (4 * (-1 + c*lam) * (-c**2 * np.exp(3*T*lam) * (1 - 4*F0)**2 * lam**2 +
                                        np.exp(2*T*(1/c + lam)) * (2 + c*lam) * (27 + c*(-13 - 4*F0 + 8*F0**2)*lam) +
                                        np.exp(2*T*(1/c + 2*lam)) * (-2 + c*lam) * (9 + c*(5 - 4*F0 + 8*F0**2)*lam) +
                                        9 * np.exp(2*T/c + 3*T*lam) * (-4 + c**2 * lam**2)))

    Fbar = numerator / (denominator + eps)
    Fbar = np.clip(Fbar, 0, 1)

    p_succ_numerator = (1 / (9 * (-4 + c**2 * lam**2)) *
                        np.exp(-2*T*(1/c + 2*lam)) *
                        (-c**2 * np.exp(3*T*lam) * (1 - 4*F0)**2 * lam**2 +
                         np.exp(2*T*(1/c + lam)) * (2 + c*lam) * (27 + c*(-13 - 4*F0 + 8*F0**2)*lam) +
                         np.exp(2*T*(1/c + 2*lam)) * (-2 + c*lam) * (9 + c*(5 - 4*F0 + 8*F0**2)*lam) +
                         9 * np.exp(2*T/c + 3*T*lam) * (-4 + c**2 * lam**2)))

    p_succ_mean = np.clip(p_succ_numerator, 0, 1)

    success_rate = 1 - np.exp(-2 * lam_orig * T)
    R = success_rate * p_succ_mean * coherent_information(Fbar)

    return Fbar, R, success_rate

def single_link_obp_analytical(lam, c, T, t_buffer, F0=0.9):
    prob_arrival = 1 - np.exp(-lam * t_buffer)

    if prob_arrival == 0:
        return 0.5, 0.0, 0.0

    avg_t_gen = (1/lam) * (1 - (1 + lam*t_buffer) * np.exp(-lam*t_buffer)) / prob_arrival

    F_at_buffer = 0.25 + (F0 - 0.25) * np.exp(-2 * (t_buffer - avg_t_gen) / c)
    F_at_T = compute_fidelity(F_at_buffer, T - t_buffer, c)

    success_rate = prob_arrival
    R = success_rate * coherent_information(F_at_T)

    return F_at_T, R, success_rate

def find_optimal_buffer_time_single_link_analytical(lam, c, T):
    t_values = np.linspace(0.01 * T, T, 50)
    best_t = T
    best_Ic = 0
    for t_buf in t_values:
        _, R, _ = single_link_obp_analytical(lam, c, T, t_buf, F0=0.9)
        if R > best_Ic:
            best_Ic = R
            best_t = t_buf
    return best_t

def discard_oldest(n_samples, lam, c, T, samples):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)

    for i in range(n_samples):
        link1_times = [t for t in [t1a[i], t1b[i]] if t < T]
        link2_times = [t for t in [t2a[i], t2b[i]] if t < T]
        if len(link1_times) >= 1 and len(link2_times) >= 1:
            F1 = raw_fidelity(max(link1_times), T, c)
            F2 = raw_fidelity(max(link2_times), T, c)
            F_final[i] = swapped_fidelity(F1, F2)
            used[i] = True

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate
    std_Ic = 0.0
    return mean_Ic, std_Ic, F_mean, success_rate

def double_link_obp_fixed_buffer(n_samples, lam, c, T, samples, t_buffer_l1, t_buffer_l2):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)

    for i in range(n_samples):
        link1_times = [t for t in [t1a[i], t1b[i]] if t < t_buffer_l1]
        link2_times = [t for t in [t2a[i], t2b[i]] if t < t_buffer_l2]

        if len(link1_times) >= 1 and len(link2_times) >= 1:
            t_first_l1 = link1_times[0]
            t_first_l2 = link2_times[0]

            F1_at_buffer = raw_fidelity(t_first_l1, t_buffer_l1, c)
            F2_at_buffer = raw_fidelity(t_first_l2, t_buffer_l2, c)

            t_swap = max(t_buffer_l1, t_buffer_l2)
            F1_at_swap = compute_fidelity(F1_at_buffer, t_swap - t_buffer_l1, c)
            F2_at_swap = compute_fidelity(F2_at_buffer, t_swap - t_buffer_l2, c)

            F_swap = swapped_fidelity(F1_at_swap, F2_at_swap)
            F_at_T = compute_fidelity(F_swap, T - t_swap, c)

            F_final[i] = F_at_T
            used[i] = True

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.5
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate
    std_Ic = 0.0

    return mean_Ic, std_Ic, F_mean, success_rate

def find_optimal_buffer_times_double_link(lam, c, T, samples, n_samples):
    t_values = np.linspace(0.01 * T, T, 10)
    best_t1, best_t2 = T, T
    best_Ic = 0

    for t1 in t_values:
        for t2 in t_values:
            mean_Ic, _, _, _ = double_link_obp_fixed_buffer(n_samples, lam, c, T, samples, t1, t2)
            if mean_Ic > best_Ic:
                best_Ic = mean_Ic
                best_t1 = t1
                best_t2 = t2

    return best_t1, best_t2

def distill_then_swap(n_samples, lam, c, T, samples, distill_strategy, swap_strategy):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    avail = state_availability(t1a, t1b, t2a, t2b, T)
    valid = avail >= 2
    F_final = np.zeros_like(t1a)
    used = valid.copy()
    p_success_all = np.ones(n_samples)

    for i in np.where(valid)[0]:
        link1_pairs = sorted([t for t in [t1a[i], t1b[i]] if t < T])
        link2_pairs = sorted([t for t in [t2a[i], t2b[i]] if t < T])
        ready_l1, ready_l2 = len(link1_pairs), len(link2_pairs)

        if distill_strategy == 'ASAP':
            p_success_total = 1.0

            if ready_l1 >= 2:
                t_dist_l1 = link1_pairs[1]
                Fa = raw_fidelity(link1_pairs[0], t_dist_l1, c)
                Fb = raw_fidelity(link1_pairs[1], t_dist_l1, c)
                F1 = isotropic_purification_pairwise(Fa, Fb)
                p_success_l1 = Fa * Fb + (1/3) * Fa * (1 - Fb) + (1/3) * Fb * (1 - Fa) + (5/9) * (1 - Fa) * (1 - Fb)
                p_success_total *= p_success_l1
            elif ready_l1 == 1:
                t_dist_l1 = link1_pairs[0]
                F1 = raw_fidelity(link1_pairs[0], t_dist_l1, c)
            else:
                used[i] = False
                continue

            if ready_l2 >= 2:
                t_dist_l2 = link2_pairs[1]
                Fa = raw_fidelity(link2_pairs[0], t_dist_l2, c)
                Fb = raw_fidelity(link2_pairs[1], t_dist_l2, c)
                F2 = isotropic_purification_pairwise(Fa, Fb)
                p_success_l2 = Fa * Fb + (1/3) * Fa * (1 - Fb) + (1/3) * Fb * (1 - Fa) + (5/9) * (1 - Fa) * (1 - Fb)
                p_success_total *= p_success_l2
            elif ready_l2 == 1:
                t_dist_l2 = link2_pairs[0]
                F2 = raw_fidelity(link2_pairs[0], t_dist_l2, c)
            else:
                used[i] = False
                continue

            if swap_strategy == 'ASAP':
                t_swap = max(t_dist_l1, t_dist_l2)
                F1_at_swap = compute_fidelity(F1, t_swap - t_dist_l1, c)
                F2_at_swap = compute_fidelity(F2, t_swap - t_dist_l2, c)
                F_swap = swapped_fidelity(F1_at_swap, F2_at_swap)
                F_final[i] = compute_fidelity(F_swap, T - t_swap, c)
            else:
                F1 = compute_fidelity(F1, T - t_dist_l1, c)
                F2 = compute_fidelity(F2, T - t_dist_l2, c)
                F_final[i] = swapped_fidelity(F1, F2)

            p_success_all[i] = p_success_total

        else:
            p_success_total = 1.0

            if ready_l1 >= 2:
                Fa = raw_fidelity(link1_pairs[0], T, c)
                Fb = raw_fidelity(link1_pairs[1], T, c)
                F1 = isotropic_purification_pairwise(Fa, Fb)
                p_success_l1 = Fa * Fb + (1/3) * Fa * (1 - Fb) + (1/3) * Fb * (1 - Fa) + (5/9) * (1 - Fa) * (1 - Fb)
                p_success_total *= p_success_l1
            elif ready_l1 == 1:
                F1 = raw_fidelity(link1_pairs[0], T, c)
            else:
                used[i] = False
                continue

            if ready_l2 >= 2:
                Fa = raw_fidelity(link2_pairs[0], T, c)
                Fb = raw_fidelity(link2_pairs[1], T, c)
                F2 = isotropic_purification_pairwise(Fa, Fb)
                p_success_l2 = Fa * Fb + (1/3) * Fa * (1 - Fb) + (1/3) * Fb * (1 - Fa) + (5/9) * (1 - Fa) * (1 - Fb)
                p_success_total *= p_success_l2
            elif ready_l2 == 1:
                F2 = raw_fidelity(link2_pairs[0], T, c)
            else:
                used[i] = False
                continue

            F_final[i] = swapped_fidelity(F1, F2)
            p_success_all[i] = p_success_total

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    p_success_mean = np.mean(p_success_all[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate * p_success_mean
    std_Ic = 0.0
    return mean_Ic, std_Ic, F_mean, success_rate

def swap_then_distill(n_samples, lam, c, T, samples, swap_strategy, distill_strategy):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    avail = state_availability(t1a, t1b, t2a, t2b, T)
    valid = avail >= 2
    F_final = np.zeros_like(t1a)
    used = valid.copy()
    p_success_all = np.ones(n_samples)

    for i in np.where(valid)[0]:
        link1_pairs = sorted([t for t in [t1a[i], t1b[i]] if t < T])
        link2_pairs = sorted([t for t in [t2a[i], t2b[i]] if t < T])
        all_times = sorted([t for t in [t1a[i], t1b[i], t2a[i], t2b[i]] if t < T])
        ready_l1, ready_l2 = len(link1_pairs), len(link2_pairs)

        if ready_l1 < 1 or ready_l2 < 1:
            used[i] = False
            continue

        p_success_total = 1.0

        if swap_strategy == 'ASAP':
            t_swap_1, t_swap_2 = link1_pairs[0], link2_pairs[0]
            t_swap = max(t_swap_1, t_swap_2)
            F1 = raw_fidelity(t_swap_1, t_swap, c)
            F2 = raw_fidelity(t_swap_2, t_swap, c)
            F_swap = swapped_fidelity(F1, F2)
            remaining = [t for t in all_times if t > t_swap]

            if distill_strategy == 'ASAP':
                if len(remaining) >= 1:
                    t_dist = remaining[0]
                    F_remain = raw_fidelity(remaining[0], t_dist, c)
                    F_swap_at_dist = compute_fidelity(F_swap, t_dist - t_swap, c)
                    F_dist = isotropic_purification_pairwise(F_swap_at_dist, F_remain)
                    p_success = F_swap_at_dist * F_remain + (1/3) * F_swap_at_dist * (1 - F_remain) + (1/3) * F_remain * (1 - F_swap_at_dist) + (5/9) * (1 - F_swap_at_dist) * (1 - F_remain)
                    p_success_total *= p_success
                    F_final[i] = compute_fidelity(F_dist, T - t_dist, c)
                else:
                    F_final[i] = compute_fidelity(F_swap, T - t_swap, c)
            else:
                F_swap_at_T = compute_fidelity(F_swap, T - t_swap, c)
                if len(remaining) >= 1:
                    F_remain = raw_fidelity(remaining[0], T, c)
                    F_final[i] = isotropic_purification_pairwise(F_swap_at_T, F_remain)
                    p_success = F_swap_at_T * F_remain + (1/3) * F_swap_at_T * (1 - F_remain) + (1/3) * F_remain * (1 - F_swap_at_T) + (5/9) * (1 - F_swap_at_T) * (1 - F_remain)
                    p_success_total *= p_success
                else:
                    F_final[i] = F_swap_at_T
        else:
            F1 = raw_fidelity(link1_pairs[0], T, c)
            F2 = raw_fidelity(link2_pairs[0], T, c)
            F_swap = swapped_fidelity(F1, F2)
            remaining = [t for t in all_times[2:] if t < T]

            if len(remaining) >= 1:
                F_remain = raw_fidelity(remaining[0], T, c)
                F_final[i] = isotropic_purification_pairwise(F_swap, F_remain)
                p_success = F_swap * F_remain + (1/3) * F_swap * (1 - F_remain) + (1/3) * F_remain * (1 - F_swap) + (5/9) * (1 - F_swap) * (1 - F_remain)
                p_success_total *= p_success
            else:
                F_final[i] = F_swap

        p_success_all[i] = p_success_total

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    p_success_mean = np.mean(p_success_all[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate * p_success_mean
    std_Ic = 0.0
    return mean_Ic, std_Ic, F_mean, success_rate

lambda_test_vals = [0.5, 1.0, 1.5, 2.0]
c_test = 10.0
n_samples_test = 5000

single_link_data = {
    'lambda': [], 'discard_success': [], 'discard_Ic': [], 'discard_std': [], 'discard_F': [],
    'asap_success': [], 'asap_Ic': [], 'asap_std': [], 'asap_F': [],
    'alap_success': [], 'alap_Ic': [], 'alap_std': [], 'alap_F': [],
    'obp_success': [], 'obp_Ic': [], 'obp_std': [], 'obp_F': [], 'obp_t_opt': []
}

double_link_data = {
    'lambda': [], 'discard_success': [], 'discard_Ic': [], 'discard_std': [], 'discard_F': [],
    'dt_aa_success': [], 'dt_aa_Ic': [], 'dt_aa_std': [], 'dt_aa_F': [],
    'dt_al_success': [], 'dt_al_Ic': [], 'dt_al_std': [], 'dt_al_F': [],
    'dt_ll_success': [], 'dt_ll_Ic': [], 'dt_ll_std': [], 'dt_ll_F': [],
    'st_aa_success': [], 'st_aa_Ic': [], 'st_aa_std': [], 'st_aa_F': [],
    'st_al_success': [], 'st_al_Ic': [], 'st_al_std': [], 'st_al_F': [],
    'st_ll_success': [], 'st_ll_Ic': [], 'st_ll_std': [], 'st_ll_F': [],
    'obp_success': [], 'obp_Ic': [], 'obp_std': [], 'obp_F': []
}

print("\n" + "="*80)
print("COMPREHENSIVE SUCCESS RATE CALCULATION")
print("="*80)
print("\nRunning comprehensive analysis...")

for λ_val in lambda_test_vals:
    print(f"  Processing λ = {λ_val}...")
    np.random.seed(42)
    T_val = 2.0 / λ_val

    samples_2L = {
        't_l1_1': np.random.exponential(scale=1/λ_val, size=n_samples_test),
        't_l1_2': np.random.exponential(scale=1/λ_val, size=n_samples_test),
        't_l2_1': np.random.exponential(scale=1/λ_val, size=n_samples_test),
        't_l2_2': np.random.exponential(scale=1/λ_val, size=n_samples_test)
    }

    single_link_data['lambda'].append(λ_val)
    F, Ic, sr = discard_oldest_analytical(λ_val, c_test, T_val, F0=0.9)
    single_link_data['discard_Ic'].append(Ic)
    single_link_data['discard_std'].append(0.0)
    single_link_data['discard_F'].append(F)
    single_link_data['discard_success'].append(sr)

    F, Ic, sr = distill_asap_analytical(λ_val, c_test, T_val, F0=0.9)
    single_link_data['asap_Ic'].append(Ic)
    single_link_data['asap_std'].append(0.0)
    single_link_data['asap_F'].append(F)
    single_link_data['asap_success'].append(sr)

    F, Ic, sr = distill_alap_analytical(λ_val, c_test, T_val, F0=0.9)
    single_link_data['alap_Ic'].append(Ic)
    single_link_data['alap_std'].append(0.0)
    single_link_data['alap_F'].append(F)
    single_link_data['alap_success'].append(sr)

    t_opt = find_optimal_buffer_time_single_link_analytical(λ_val, c_test, T_val)
    single_link_data['obp_t_opt'].append(t_opt)
    F, Ic, sr = single_link_obp_analytical(λ_val, c_test, T_val, t_opt, F0=0.9)
    single_link_data['obp_Ic'].append(Ic)
    single_link_data['obp_std'].append(0.0)
    single_link_data['obp_F'].append(F)
    single_link_data['obp_success'].append(sr)

    double_link_data['lambda'].append(λ_val)
    Ic, std, F, sr = discard_oldest(n_samples_test, λ_val, c_test, T_val, samples_2L)
    double_link_data['discard_Ic'].append(Ic)
    double_link_data['discard_std'].append(std)
    double_link_data['discard_F'].append(F)
    double_link_data['discard_success'].append(sr)

    Ic, std, F, sr = distill_then_swap(n_samples_test, λ_val, c_test, T_val, samples_2L, 'ASAP', 'ASAP')
    double_link_data['dt_aa_Ic'].append(Ic)
    double_link_data['dt_aa_std'].append(std)
    double_link_data['dt_aa_F'].append(F)
    double_link_data['dt_aa_success'].append(sr)

    Ic, std, F, sr = distill_then_swap(n_samples_test, λ_val, c_test, T_val, samples_2L, 'ASAP', 'ALAP')
    double_link_data['dt_al_Ic'].append(Ic)
    double_link_data['dt_al_std'].append(std)
    double_link_data['dt_al_F'].append(F)
    double_link_data['dt_al_success'].append(sr)

    Ic, std, F, sr = distill_then_swap(n_samples_test, λ_val, c_test, T_val, samples_2L, 'ALAP', 'ALAP')
    double_link_data['dt_ll_Ic'].append(Ic)
    double_link_data['dt_ll_std'].append(std)
    double_link_data['dt_ll_F'].append(F)
    double_link_data['dt_ll_success'].append(sr)

    Ic, std, F, sr = swap_then_distill(n_samples_test, λ_val, c_test, T_val, samples_2L, 'ASAP', 'ASAP')
    double_link_data['st_aa_Ic'].append(Ic)
    double_link_data['st_aa_std'].append(std)
    double_link_data['st_aa_F'].append(F)
    double_link_data['st_aa_success'].append(sr)

    Ic, std, F, sr = swap_then_distill(n_samples_test, λ_val, c_test, T_val, samples_2L, 'ASAP', 'ALAP')
    double_link_data['st_al_Ic'].append(Ic)
    double_link_data['st_al_std'].append(std)
    double_link_data['st_al_F'].append(F)
    double_link_data['st_al_success'].append(sr)

    Ic, std, F, sr = swap_then_distill(n_samples_test, λ_val, c_test, T_val, samples_2L, 'ALAP', 'ALAP')
    double_link_data['st_ll_Ic'].append(Ic)
    double_link_data['st_ll_std'].append(std)
    double_link_data['st_ll_F'].append(F)
    double_link_data['st_ll_success'].append(sr)

    t1_opt, t2_opt = find_optimal_buffer_times_double_link(λ_val, c_test, T_val, samples_2L, n_samples_test)
    Ic, std, F, sr = double_link_obp_fixed_buffer(n_samples_test, λ_val, c_test, T_val, samples_2L, t1_opt, t2_opt)
    double_link_data['obp_Ic'].append(Ic)
    double_link_data['obp_std'].append(std)
    double_link_data['obp_F'].append(F)
    double_link_data['obp_success'].append(sr)

print("\n" + "="*80)
print("SINGLE-LINK PROTOCOLS")
print("="*80)
print(f"{'Protocol':<20} | λ=0.5 SR% | λ=1.0 SR% | Mean Ic | Eff Thru | Mean F")
print("-"*80)

protocols_1L = ['discard', 'asap', 'alap', 'obp']
names_1L = ['Discard-Oldest', 'Distill-ASAP', 'Distill-ALAP', 'OBP']

for proto, name in zip(protocols_1L, names_1L):
    idx_05, idx_10 = 0, 1
    sr_05 = single_link_data[f'{proto}_success'][idx_05] * 100
    sr_10 = single_link_data[f'{proto}_success'][idx_10] * 100
    Ic = single_link_data[f'{proto}_Ic'][idx_10]
    F = single_link_data[f'{proto}_F'][idx_10]
    eff = Ic
    print(f"{name:<20} | {sr_05:8.2f}% | {sr_10:8.2f}% | {Ic:7.4f} | {eff:8.4f} | {F:6.4f}")

print("\n" + "="*80)
print("DOUBLE-LINK PROTOCOLS")
print("="*80)
print(f"{'Protocol':<20} | λ=0.5 SR% | λ=1.0 SR% | Mean Ic | Eff Thru | Mean F")
print("-"*80)

protocols_2L = ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll', 'obp']
names_2L = ['Discard-Oldest', 'DT-ASAP-ASAP', 'DT-ASAP-ALAP', 'DT-ALAP-ALAP',
            'ST-ASAP-ASAP', 'ST-ASAP-ALAP', 'ST-ALAP-ALAP', 'OBP']

for proto, name in zip(protocols_2L, names_2L):
    idx_05, idx_10 = 0, 1
    sr_05 = double_link_data[f'{proto}_success'][idx_05] * 100
    sr_10 = double_link_data[f'{proto}_success'][idx_10] * 100
    Ic = double_link_data[f'{proto}_Ic'][idx_10]
    F = double_link_data[f'{proto}_F'][idx_10]
    eff = Ic
    print(f"{name:<20} | {sr_05:8.2f}% | {sr_10:8.2f}% | {Ic:7.4f} | {eff:8.4f} | {F:6.4f}")

print("\n" + "="*80)
print("KEY COMPARISONS")
print("="*80)

idx_10 = 1
discard_1L_eff = single_link_data['discard_Ic'][idx_10]
discard_2L_eff = double_link_data['discard_Ic'][idx_10]
obp_1L_eff = single_link_data['obp_Ic'][idx_10]
obp_2L_eff = double_link_data['obp_Ic'][idx_10]
st_aa_eff = double_link_data['st_aa_Ic'][idx_10]

improvement_2L = ((st_aa_eff - discard_2L_eff) / discard_2L_eff) * 100
gap_1L_vs_2L = ((discard_1L_eff - st_aa_eff) / discard_1L_eff) * 100
obp_improvement_1L = ((obp_1L_eff - discard_1L_eff) / discard_1L_eff) * 100
obp_improvement_2L = ((obp_2L_eff - discard_2L_eff) / discard_2L_eff) * 100

print(f"\nSingle-Link Discard-Oldest:  {discard_1L_eff:.4f} effective throughput")
print(f"Single-Link OBP:             {obp_1L_eff:.4f} effective throughput")
print(f"Double-Link Discard-Oldest:  {discard_2L_eff:.4f} effective throughput")
print(f"Double-Link OBP:             {obp_2L_eff:.4f} effective throughput")
print(f"Double-Link ST-ASAP-ASAP:    {st_aa_eff:.4f} effective throughput")
print(f"\nST-ASAP-ASAP vs 2L-Discard:  {improvement_2L:+.1f}% improvement")
print(f"1L-Discard vs Best 2L:       {gap_1L_vs_2L:.1f}% performance gap")
print(f"OBP vs Discard (1L):         {obp_improvement_1L:+.1f}% improvement")
print(f"OBP vs Discard (2L):         {obp_improvement_2L:+.1f}% improvement")

df_1L = pd.DataFrame(single_link_data)
df_2L = pd.DataFrame(double_link_data)
df_1L.to_csv("single_link_protocols_data.csv", index=False)
df_2L.to_csv("double_link_protocols_data.csv", index=False)
print("\nData saved:")
print("  - single_link_protocols_data.csv")
print("  - double_link_protocols_data.csv")
print("="*80)