# -*- coding: utf-8 -*-
"""Two-Link-Simulation-Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVMlN7l-Gltm0qnk3ddBRGt_PiluVCBg
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

plt.rcParams.update({
    'font.size': 13,
    'axes.labelsize': 16,
    'axes.titlesize': 17,
    'xtick.labelsize': 13,
    'ytick.labelsize': 13,
    'legend.fontsize': 15,
    'figure.titlesize': 18,
    'lines.linewidth': 2.4,
    'lines.markersize': 7
})

os.makedirs("figures_for_paper", exist_ok=True)

SEED = 42
np.random.seed(SEED)

n_samples = 5000

lambda_vals_physical = [10.0, 1e4]
c_vals_physical = [0.1, 1.0, 100.0]

PROTOCOL_LABELS = {
    'discard': 'Discard-Oldest',
    'dt_aa': 'D-ASAP-S-ASAP',
    'dt_al': 'D-ASAP-S-ALAP',
    'dt_ll': 'D-ALAP-S-ALAP',
    'st_aa': 'S-ASAP-D-ASAP',
    'st_al': 'S-ASAP-D-ALAP',
    'st_ll': 'S-ALAP-D-ALAP'
}

all_dataframes = []

def raw_fidelity(t_gen, t_total, c):
    A = 1/4
    B = (3/4) * np.exp(-2 * t_total / c)
    return np.clip(A + B * np.exp(2 * t_gen / c), 0, 1)

def compute_fidelity(F_init, t_idle, c):
    A = 1/4
    B = F_init - A
    return np.clip(A + B * np.exp(-2 * t_idle / c), 0, 1)

def isotropic_purification_pairwise(F1, F2):
    num = F1 * F2 + (1/9) * (1 - F1) * (1 - F2)
    denom = (F1 * F2 + (1/3) * F1 * (1 - F2) + (1/3) * F2 * (1 - F1) + (5/9) * (1 - F1) * (1 - F2))
    return np.clip(num / denom, 0, 1)

def swapped_fidelity(F1, F2):
    return np.clip(F1 * F2 + (1 - F1) * (1 - F2) / 3, 0, 1)

def coherent_information_vectorized(F):
    λ1 = F
    λ_rest = (1 - F) / 3
    eigs = np.stack([λ1, λ_rest, λ_rest, λ_rest], axis=-1)
    S = -np.sum(eigs * np.log2(eigs + 1e-12), axis=-1)
    return np.maximum(0, 1 - S)

def state_availability(t1a, t1b, t2a, t2b, T):
    available = np.zeros(len(t1a), dtype=int)
    available += (t1a < T).astype(int) + (t1b < T).astype(int) + (t2a < T).astype(int) + (t2b < T).astype(int)
    return available

def discard_oldest(n_samples, lam, c, T, samples):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)

    for i in range(n_samples):
        link1_times = [t for t in [t1a[i], t1b[i]] if t < T]
        link2_times = [t for t in [t2a[i], t2b[i]] if t < T]
        if len(link1_times) >= 1 and len(link2_times) >= 1:
            F1 = raw_fidelity(max(link1_times), T, c)
            F2 = raw_fidelity(max(link2_times), T, c)
            F_final[i] = swapped_fidelity(F1, F2)
            used[i] = True

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate
    Ic_all = coherent_information_vectorized(F_final[used]) if np.sum(used) > 0 else np.array([])
    std_Ic = np.std(Ic_all) if len(Ic_all) > 0 else 0.0
    return mean_Ic, std_Ic, F_mean, success_rate

def distill_then_swap(n_samples, lam, c, T, samples, distill_strategy, swap_strategy):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    avail = state_availability(t1a, t1b, t2a, t2b, T)
    valid = avail >= 2
    F_final = np.zeros_like(t1a)
    p_success_all = np.ones(n_samples)
    used = valid.copy()

    for i in np.where(valid)[0]:
        link1_pairs = sorted([t for t in [t1a[i], t1b[i]] if t < T])
        link2_pairs = sorted([t for t in [t2a[i], t2b[i]] if t < T])
        ready_l1, ready_l2 = len(link1_pairs), len(link2_pairs)

        if distill_strategy == 'ASAP':
            p_success_total = 1.0

            if ready_l1 >= 2:
                t_dist_l1 = link1_pairs[1]
                Fa = raw_fidelity(link1_pairs[0], t_dist_l1, c)
                Fb = raw_fidelity(link1_pairs[1], t_dist_l1, c)
                F1 = isotropic_purification_pairwise(Fa, Fb)
                p_success_l1 = Fa * Fb + (1/3) * Fa * (1 - Fb) + (1/3) * Fb * (1 - Fa) + (5/9) * (1 - Fa) * (1 - Fb)
                p_success_total *= p_success_l1
            elif ready_l1 == 1:
                t_dist_l1 = link1_pairs[0]
                F1 = raw_fidelity(link1_pairs[0], t_dist_l1, c)
            else:
                used[i] = False
                continue

            if ready_l2 >= 2:
                t_dist_l2 = link2_pairs[1]
                Fa = raw_fidelity(link2_pairs[0], t_dist_l2, c)
                Fb = raw_fidelity(link2_pairs[1], t_dist_l2, c)
                F2 = isotropic_purification_pairwise(Fa, Fb)
                p_success_l2 = Fa * Fb + (1/3) * Fa * (1 - Fb) + (1/3) * Fb * (1 - Fa) + (5/9) * (1 - Fa) * (1 - Fb)
                p_success_total *= p_success_l2
            elif ready_l2 == 1:
                t_dist_l2 = link2_pairs[0]
                F2 = raw_fidelity(link2_pairs[0], t_dist_l2, c)
            else:
                used[i] = False
                continue

            if swap_strategy == 'ASAP':
                t_swap = max(t_dist_l1, t_dist_l2)
                F1_at_swap = compute_fidelity(F1, t_swap - t_dist_l1, c)
                F2_at_swap = compute_fidelity(F2, t_swap - t_dist_l2, c)
                F_swap = swapped_fidelity(F1_at_swap, F2_at_swap)
                F_final[i] = compute_fidelity(F_swap, T - t_swap, c)
            else:
                F1 = compute_fidelity(F1, T - t_dist_l1, c)
                F2 = compute_fidelity(F2, T - t_dist_l2, c)
                F_final[i] = swapped_fidelity(F1, F2)

            p_success_all[i] = p_success_total

        else:
            p_success_total = 1.0

            if ready_l1 >= 2:
                Fa = raw_fidelity(link1_pairs[0], T, c)
                Fb = raw_fidelity(link1_pairs[1], T, c)
                F1 = isotropic_purification_pairwise(Fa, Fb)
                p_success_l1 = Fa * Fb + (1/3) * Fa * (1 - Fb) + (1/3) * Fb * (1 - Fa) + (5/9) * (1 - Fa) * (1 - Fb)
                p_success_total *= p_success_l1
            elif ready_l1 == 1:
                F1 = raw_fidelity(link1_pairs[0], T, c)
            else:
                used[i] = False
                continue

            if ready_l2 >= 2:
                Fa = raw_fidelity(link2_pairs[0], T, c)
                Fb = raw_fidelity(link2_pairs[1], T, c)
                F2 = isotropic_purification_pairwise(Fa, Fb)
                p_success_l2 = Fa * Fb + (1/3) * Fa * (1 - Fb) + (1/3) * Fb * (1 - Fa) + (5/9) * (1 - Fa) * (1 - Fb)
                p_success_total *= p_success_l2
            elif ready_l2 == 1:
                F2 = raw_fidelity(link2_pairs[0], T, c)
            else:
                used[i] = False
                continue

            F_final[i] = swapped_fidelity(F1, F2)
            p_success_all[i] = p_success_total

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_p_success = np.mean(p_success_all[used]) if np.sum(used) > 0 else 0.0
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate * mean_p_success
    Ic_all = coherent_information_vectorized(F_final[used]) * p_success_all[used] if np.sum(used) > 0 else np.array([])
    std_Ic = np.std(Ic_all) if len(Ic_all) > 0 else 0.0
    total_success_prob = success_rate * mean_p_success
    return mean_Ic, std_Ic, F_mean, total_success_prob

def swap_then_distill(n_samples, lam, c, T, samples, swap_strategy, distill_strategy):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    avail = state_availability(t1a, t1b, t2a, t2b, T)
    valid = avail >= 2
    F_final = np.zeros_like(t1a)
    p_success_all = np.ones(n_samples)
    used = valid.copy()

    for i in np.where(valid)[0]:
        link1_pairs = sorted([t for t in [t1a[i], t1b[i]] if t < T])
        link2_pairs = sorted([t for t in [t2a[i], t2b[i]] if t < T])
        all_times = sorted([t for t in [t1a[i], t1b[i], t2a[i], t2b[i]] if t < T])
        ready_l1, ready_l2 = len(link1_pairs), len(link2_pairs)

        if ready_l1 < 1 or ready_l2 < 1:
            used[i] = False
            continue

        p_success_total = 1.0

        if swap_strategy == 'ASAP':
            t_swap_1, t_swap_2 = link1_pairs[0], link2_pairs[0]
            t_swap = max(t_swap_1, t_swap_2)
            F1 = raw_fidelity(t_swap_1, t_swap, c)
            F2 = raw_fidelity(t_swap_2, t_swap, c)
            F_swap = swapped_fidelity(F1, F2)
            remaining = [t for t in all_times if t > t_swap]

            if distill_strategy == 'ASAP':
                if len(remaining) >= 1:
                    t_dist = remaining[0]
                    F_remain = raw_fidelity(remaining[0], t_dist, c)
                    F_swap_at_dist = compute_fidelity(F_swap, t_dist - t_swap, c)
                    F_dist = isotropic_purification_pairwise(F_swap_at_dist, F_remain)
                    p_success = F_swap_at_dist * F_remain + (1/3) * F_swap_at_dist * (1 - F_remain) + (1/3) * F_remain * (1 - F_swap_at_dist) + (5/9) * (1 - F_swap_at_dist) * (1 - F_remain)
                    p_success_total *= p_success
                    F_final[i] = compute_fidelity(F_dist, T - t_dist, c)
                else:
                    F_final[i] = compute_fidelity(F_swap, T - t_swap, c)
            else:
                F_swap_at_T = compute_fidelity(F_swap, T - t_swap, c)
                if len(remaining) >= 1:
                    F_remain = raw_fidelity(remaining[0], T, c)
                    F_final[i] = isotropic_purification_pairwise(F_swap_at_T, F_remain)
                    p_success = F_swap_at_T * F_remain + (1/3) * F_swap_at_T * (1 - F_remain) + (1/3) * F_remain * (1 - F_swap_at_T) + (5/9) * (1 - F_swap_at_T) * (1 - F_remain)
                    p_success_total *= p_success
                else:
                    F_final[i] = F_swap_at_T
        else:
            F1 = raw_fidelity(link1_pairs[0], T, c)
            F2 = raw_fidelity(link2_pairs[0], T, c)
            F_swap = swapped_fidelity(F1, F2)
            remaining = [t for t in all_times[2:] if t < T]

            if len(remaining) >= 1:
                F_remain = raw_fidelity(remaining[0], T, c)
                F_final[i] = isotropic_purification_pairwise(F_swap, F_remain)
                p_success = F_swap * F_remain + (1/3) * F_swap * (1 - F_remain) + (1/3) * F_remain * (1 - F_swap) + (5/9) * (1 - F_swap) * (1 - F_remain)
                p_success_total *= p_success
            else:
                F_final[i] = F_swap

        p_success_all[i] = p_success_total

    F_mean = np.mean(F_final[used]) if np.sum(used) > 0 else 0.0
    success_rate = np.sum(used) / n_samples
    mean_p_success = np.mean(p_success_all[used]) if np.sum(used) > 0 else 0.0
    mean_Ic = coherent_information_vectorized(F_mean) * success_rate * mean_p_success
    Ic_all = coherent_information_vectorized(F_final[used]) * p_success_all[used] if np.sum(used) > 0 else np.array([])
    std_Ic = np.std(Ic_all) if len(Ic_all) > 0 else 0.0
    total_success_prob = success_rate * mean_p_success
    return mean_Ic, std_Ic, F_mean, total_success_prob

def discard_oldest_distribution(n_samples, lam, c, T, samples):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    F_final = np.zeros(n_samples)
    used = np.zeros(n_samples, dtype=bool)

    for i in range(n_samples):
        link1_times = [t for t in [t1a[i], t1b[i]] if t < T]
        link2_times = [t for t in [t2a[i], t2b[i]] if t < T]
        if len(link1_times) >= 1 and len(link2_times) >= 1:
            F1 = raw_fidelity(max(link1_times), T, c)
            F2 = raw_fidelity(max(link2_times), T, c)
            F_final[i] = swapped_fidelity(F1, F2)
            used[i] = True

    F_used = F_final[used]
    I_c = coherent_information_vectorized(F_used)
    return F_used, I_c

def swap_then_distill_distribution(n_samples, lam, c, T, samples, swap_strategy, distill_strategy):
    t1a, t1b, t2a, t2b = samples['t_l1_1'], samples['t_l1_2'], samples['t_l2_1'], samples['t_l2_2']
    avail = state_availability(t1a, t1b, t2a, t2b, T)
    valid = avail >= 2
    F_final = np.zeros_like(t1a)
    used = valid.copy()

    for i in np.where(valid)[0]:
        link1_pairs = sorted([t for t in [t1a[i], t1b[i]] if t < T])
        link2_pairs = sorted([t for t in [t2a[i], t2b[i]] if t < T])
        all_times = sorted([t for t in [t1a[i], t1b[i], t2a[i], t2b[i]] if t < T])
        ready_l1, ready_l2 = len(link1_pairs), len(link2_pairs)

        if ready_l1 < 1 or ready_l2 < 1:
            used[i] = False
            continue

        if swap_strategy == 'ASAP':
            t_swap_1, t_swap_2 = link1_pairs[0], link2_pairs[0]
            t_swap = max(t_swap_1, t_swap_2)
            F1 = raw_fidelity(t_swap_1, t_swap, c)
            F2 = raw_fidelity(t_swap_2, t_swap, c)
            F_swap = swapped_fidelity(F1, F2)
            remaining = [t for t in all_times if t > t_swap]

            if distill_strategy == 'ASAP':
                if len(remaining) >= 1:
                    t_dist = remaining[0]
                    F_remain = raw_fidelity(remaining[0], t_dist, c)
                    F_swap_at_dist = compute_fidelity(F_swap, t_dist - t_swap, c)
                    F_dist = isotropic_purification_pairwise(F_swap_at_dist, F_remain)
                    F_final[i] = compute_fidelity(F_dist, T - t_dist, c)
                else:
                    F_final[i] = compute_fidelity(F_swap, T - t_swap, c)
            else:
                F_swap_at_T = compute_fidelity(F_swap, T - t_swap, c)
                if len(remaining) >= 1:
                    F_remain = raw_fidelity(remaining[0], T, c)
                    F_final[i] = isotropic_purification_pairwise(F_swap_at_T, F_remain)
                else:
                    F_final[i] = F_swap_at_T
        else:
            F1 = raw_fidelity(link1_pairs[0], T, c)
            F2 = raw_fidelity(link2_pairs[0], T, c)
            F_swap = swapped_fidelity(F1, F2)
            remaining = [t for t in all_times[2:] if t < T]

            if len(remaining) >= 1:
                F_remain = raw_fidelity(remaining[0], T, c)
                F_final[i] = isotropic_purification_pairwise(F_swap, F_remain)
            else:
                F_final[i] = F_swap

    F_used = F_final[used]
    I_c = coherent_information_vectorized(F_used)
    return F_used, I_c

def analytic_repeated_swap(F0, N):
    arr = [F0] * N
    while len(arr) > 1:
        arr = [swapped_fidelity(arr[j], arr[j+1]) if j+1 < len(arr) else arr[j] for j in range(0, len(arr), 2)]
    return arr[0]

print("\n" + "="*80)
print("COMPUTING PHYSICAL PARAMETER REGIMES")
print("="*80)

results_physical = {}
for lam in lambda_vals_physical:
    for c in c_vals_physical:
        key = f"lam{lam}_c{c}"
        print(f"\nProcessing λ={lam}/s, c={c}s...")

        T_min = 0.01 * c
        T_max = 0.2 * c
        T_vals = np.linspace(T_min, T_max, 30)

        results = {
            'T': T_vals,
            'discard_Ic': [], 'discard_F': [], 'discard_Pr': [],
            'dt_aa_Ic': [], 'dt_aa_F': [], 'dt_aa_Pr': [],
            'dt_al_Ic': [], 'dt_al_F': [], 'dt_al_Pr': [],
            'dt_ll_Ic': [], 'dt_ll_F': [], 'dt_ll_Pr': [],
            'st_aa_Ic': [], 'st_aa_F': [], 'st_aa_Pr': [],
            'st_al_Ic': [], 'st_al_F': [], 'st_al_Pr': [],
            'st_ll_Ic': [], 'st_ll_F': [], 'st_ll_Pr': []
        }

        for T in T_vals:
            np.random.seed(SEED)
            samples = {k: np.random.exponential(scale=1/lam, size=n_samples) for k in ['t_l1_1','t_l1_2','t_l2_1','t_l2_2']}

            mean_Ic, _, F_mean, Pr = discard_oldest(n_samples, lam, c, T, samples)
            results['discard_Ic'].append(mean_Ic)
            results['discard_F'].append(F_mean)
            results['discard_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = distill_then_swap(n_samples, lam, c, T, samples, 'ASAP', 'ASAP')
            results['dt_aa_Ic'].append(mean_Ic)
            results['dt_aa_F'].append(F_mean)
            results['dt_aa_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = distill_then_swap(n_samples, lam, c, T, samples, 'ASAP', 'ALAP')
            results['dt_al_Ic'].append(mean_Ic)
            results['dt_al_F'].append(F_mean)
            results['dt_al_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = distill_then_swap(n_samples, lam, c, T, samples, 'ALAP', 'ALAP')
            results['dt_ll_Ic'].append(mean_Ic)
            results['dt_ll_F'].append(F_mean)
            results['dt_ll_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = swap_then_distill(n_samples, lam, c, T, samples, 'ASAP', 'ASAP')
            results['st_aa_Ic'].append(mean_Ic)
            results['st_aa_F'].append(F_mean)
            results['st_aa_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = swap_then_distill(n_samples, lam, c, T, samples, 'ASAP', 'ALAP')
            results['st_al_Ic'].append(mean_Ic)
            results['st_al_F'].append(F_mean)
            results['st_al_Pr'].append(Pr)

            mean_Ic, _, F_mean, Pr = swap_then_distill(n_samples, lam, c, T, samples, 'ALAP', 'ALAP')
            results['st_ll_Ic'].append(mean_Ic)
            results['st_ll_F'].append(F_mean)
            results['st_ll_Pr'].append(Pr)

        results_physical[key] = results

        df = pd.DataFrame(results)
        df['Data_Section'] = f'Physical_Params_{key}'
        parts = key.replace('lam', '').split('_c')
        df['lambda'] = float(parts[0])
        df['c'] = float(parts[1])
        all_dataframes.append(df)

print("\n" + "="*80)
print("PARAMETER REGIME DIAGNOSTICS")
print("="*80)

for lam in lambda_vals_physical:
    for c in c_vals_physical:
        key = f"lam{lam}_c{c}"

        expected_gen_time = 2.0 / lam
        T_max = 0.2 * c
        ratio = T_max / expected_gen_time

        max_Ic = max([np.max(results_physical[key][f'{p}_Ic']) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']])

        if ratio < 0.5:
            status = "FAILED"
            reason = f"T_max ({T_max:.4f}s) much less than gen time ({expected_gen_time:.4f}s)"
        elif ratio < 1.0:
            status = "MARGINAL"
            reason = f"T_max ({T_max:.4f}s) less than gen time ({expected_gen_time:.4f}s)"
        elif max_Ic < 0.1:
            status = "LOW Ic"
            reason = f"T_max adequate but high decoherence"
        else:
            status = "GOOD"
            reason = f"T_max ({T_max:.4f}s) greater than gen time ({expected_gen_time:.4f}s)"

        print(f"\n{key}: {status}")
        print(f"  Expected generation time: {expected_gen_time:.6f}s")
        print(f"  T_max (coherence time): {T_max:.6f}s")
        print(f"  Ratio (T_max/gen_time): {ratio:.3f}")
        print(f"  Max coherent info: {max_Ic:.6f}")
        print(f"  Reason: {reason}")

print("\n" + "="*80)
print("SUMMARY")
print("="*80)

good_regimes = []
marginal_regimes = []
failed_regimes = []

for lam in lambda_vals_physical:
    for c in c_vals_physical:
        key = f"lam{lam}_c{c}"
        expected_gen_time = 2.0 / lam
        T_max = 0.2 * c
        ratio = T_max / expected_gen_time
        max_Ic = max([np.max(results_physical[key][f'{p}_Ic']) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']])

        if ratio >= 1.0 and max_Ic >= 0.1:
            good_regimes.append(key)
        elif ratio < 0.5:
            failed_regimes.append(key)
        else:
            marginal_regimes.append(key)

print(f"\nGOOD regimes ({len(good_regimes)}): {', '.join(good_regimes)}")
print(f"MARGINAL regimes ({len(marginal_regimes)}): {', '.join(marginal_regimes)}")
print(f"FAILED regimes ({len(failed_regimes)}): {', '.join(failed_regimes)}")

print("\n" + "="*80)

print("\n" + "="*80)
print("GENERATING FIGURES WITH PHYSICAL PARAMETERS")
print("="*80)

fig1 = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, c in enumerate(c_vals_physical):
        key = f"lam{lam}_c{c}"
        res = results_physical[key]

        ax = plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_Ic'], label=PROTOCOL_LABELS['discard'],
                marker='D', color='black', markersize=5)
        plt.plot(res['T'], res['dt_aa_Ic'], label=PROTOCOL_LABELS['dt_aa'],
                marker='o', alpha=0.7)
        plt.plot(res['T'], res['dt_al_Ic'], label=PROTOCOL_LABELS['dt_al'],
                marker='s', alpha=0.7)
        plt.plot(res['T'], res['dt_ll_Ic'], label=PROTOCOL_LABELS['dt_ll'],
                marker='^', alpha=0.7)
        plt.plot(res['T'], res['st_aa_Ic'], label=PROTOCOL_LABELS['st_aa'],
                marker='v', alpha=0.7)
        plt.plot(res['T'], res['st_al_Ic'], label=PROTOCOL_LABELS['st_al'],
                marker='<', alpha=0.7)
        plt.plot(res['T'], res['st_ll_Ic'], label=PROTOCOL_LABELS['st_ll'],
                marker='>', alpha=0.7)

        plt.title(f"λ={lam}/s, c={c}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Weighted coherent info")

        if c == 0.1:
            plt.xticks(np.arange(0, 0.021, 0.005))
        elif c == 1.0:
            plt.xticks(np.arange(0, 0.21, 0.05))
        elif c == 100.0:
            plt.xticks(np.arange(0, 21, 5))

        plt.grid(alpha=0.3)
        if plot_idx == 1:
            plt.legend(fontsize=11, ncol=2)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_for_paper/physical_params_coherent_info_vs_T.pdf", dpi=300)
plt.show()

fig2 = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, c in enumerate(c_vals_physical):
        key = f"lam{lam}_c{c}"
        res = results_physical[key]

        ax = plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_F'], label=PROTOCOL_LABELS['discard'],
                marker='D', color='black', markersize=5)
        plt.plot(res['T'], res['dt_aa_F'], label=PROTOCOL_LABELS['dt_aa'],
                marker='o', alpha=0.7)
        plt.plot(res['T'], res['dt_al_F'], label=PROTOCOL_LABELS['dt_al'],
                marker='s', alpha=0.7)
        plt.plot(res['T'], res['dt_ll_F'], label=PROTOCOL_LABELS['dt_ll'],
                marker='^', alpha=0.7)
        plt.plot(res['T'], res['st_aa_F'], label=PROTOCOL_LABELS['st_aa'],
                marker='v', alpha=0.7)
        plt.plot(res['T'], res['st_al_F'], label=PROTOCOL_LABELS['st_al'],
                marker='<', alpha=0.7)
        plt.plot(res['T'], res['st_ll_F'], label=PROTOCOL_LABELS['st_ll'],
                marker='>', alpha=0.7)

        plt.title(f"λ={lam}/s, c={c}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Expected fidelity")

        if c == 0.1:
            plt.xticks(np.arange(0, 0.021, 0.005))
        elif c == 1.0:
            plt.xticks(np.arange(0, 0.21, 0.05))
        elif c == 100.0:
            plt.xticks(np.arange(0, 21, 5))

        plt.grid(alpha=0.3)
        if plot_idx == 1:
            plt.legend(fontsize=11, ncol=2)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_for_paper/physical_params_fidelity_vs_T.pdf", dpi=300)
plt.show()

fig_pr = plt.figure(figsize=(18, 12))
plot_idx = 1
for i, lam in enumerate(lambda_vals_physical):
    for j, c in enumerate(c_vals_physical):
        key = f"lam{lam}_c{c}"
        res = results_physical[key]

        ax = plt.subplot(2, 3, plot_idx)
        plt.plot(res['T'], res['discard_Pr'], label=PROTOCOL_LABELS['discard'],
                marker='D', color='black', markersize=5)
        plt.plot(res['T'], res['dt_aa_Pr'], label=PROTOCOL_LABELS['dt_aa'],
                marker='o', alpha=0.7)
        plt.plot(res['T'], res['dt_al_Pr'], label=PROTOCOL_LABELS['dt_al'],
                marker='s', alpha=0.7)
        plt.plot(res['T'], res['dt_ll_Pr'], label=PROTOCOL_LABELS['dt_ll'],
                marker='^', alpha=0.7)
        plt.plot(res['T'], res['st_aa_Pr'], label=PROTOCOL_LABELS['st_aa'],
                marker='v', alpha=0.7)
        plt.plot(res['T'], res['st_al_Pr'], label=PROTOCOL_LABELS['st_al'],
                marker='<', alpha=0.7)
        plt.plot(res['T'], res['st_ll_Pr'], label=PROTOCOL_LABELS['st_ll'],
                marker='>', alpha=0.7)

        plt.title(f"λ={lam}/s, c={c}s", fontweight='bold')
        plt.xlabel("T (s)")
        plt.ylabel("Success probability")

        if c == 0.1:
            plt.xticks(np.arange(0, 0.021, 0.005))
        elif c == 1.0:
            plt.xticks(np.arange(0, 0.21, 0.05))
        elif c == 100.0:
            plt.xticks(np.arange(0, 21, 5))

        plt.grid(alpha=0.3)
        if plot_idx == 1:
            plt.legend(fontsize=11, ncol=2)
        plot_idx += 1

plt.tight_layout()
plt.savefig("figures_for_paper/physical_params_success_prob_vs_T.pdf", dpi=300)
plt.show()

print("\n" + "="*80)
print("SUMMARY OF PHYSICAL PARAMETER REGIMES")
print("="*80)
for key, res in results_physical.items():
    print(f"\n{key}:")
    for protocol in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']:
        max_Ic = np.max(res[f'{protocol}_Ic'])
        max_F = np.max(res[f'{protocol}_F'])
        mean_Ic = np.mean(res[f'{protocol}_Ic'])
        mean_Pr = np.mean(res[f'{protocol}_Pr'])
        print(f"  {PROTOCOL_LABELS[protocol]}: Max Ic={max_Ic:.6f}, Max F={max_F:.6f}, Mean Ic={mean_Ic:.6f}, Mean Pr={mean_Pr:.6f}")

print("\n" + "="*80)
print("GENERATING ADDITIONAL FIGURES")
print("="*80)

lambda_vals = np.linspace(0.1, 2.0, 20)
c_regimes = {'small': 0.5, 'medium': 10.0, 'large': 50.0}

results_by_c = {}
fidelities_by_c = {}
success_probs_by_c = {}

for c_name, c_val in c_regimes.items():
    print(f"\nProcessing c = {c_val} ({c_name})...")
    results_8protocols = {'discard': [], 'dt_aa': [], 'dt_al': [], 'dt_ll': [], 'st_aa': [], 'st_al': [], 'st_ll': []}
    results_4basic = {'dt_END': [], 'dt_ASAP': [], 'st_END': [], 'st_ASAP': []}
    std_8protocols = {'discard': [], 'dt_aa': [], 'dt_al': [], 'dt_ll': [], 'st_aa': [], 'st_al': [], 'st_ll': []}
    fidelities_8protocols = {'discard': [], 'dt_aa': [], 'dt_al': [], 'dt_ll': [], 'st_aa': [], 'st_al': [], 'st_ll': []}
    probs_8protocols = {'discard': [], 'dt_aa': [], 'dt_al': [], 'dt_ll': [], 'st_aa': [], 'st_al': [], 'st_ll': []}

    for lam in lambda_vals:
        np.random.seed(SEED)
        samples = {k: np.random.exponential(scale=1/lam, size=n_samples) for k in ['t_l1_1','t_l1_2','t_l2_1','t_l2_2']}
        T = 2.0 / lam

        mean, std, fid, pr = discard_oldest(n_samples, lam, c_val, T, samples)
        results_8protocols['discard'].append(mean)
        std_8protocols['discard'].append(std)
        fidelities_8protocols['discard'].append(fid)
        probs_8protocols['discard'].append(pr)

        mean, std, fid, pr = distill_then_swap(n_samples, lam, c_val, T, samples, 'ASAP', 'ASAP')
        results_8protocols['dt_aa'].append(mean)
        std_8protocols['dt_aa'].append(std)
        fidelities_8protocols['dt_aa'].append(fid)
        probs_8protocols['dt_aa'].append(pr)

        mean, std, fid, pr = distill_then_swap(n_samples, lam, c_val, T, samples, 'ASAP', 'ALAP')
        results_8protocols['dt_al'].append(mean)
        std_8protocols['dt_al'].append(std)
        fidelities_8protocols['dt_al'].append(fid)
        probs_8protocols['dt_al'].append(pr)

        mean, std, fid, pr = distill_then_swap(n_samples, lam, c_val, T, samples, 'ALAP', 'ALAP')
        results_8protocols['dt_ll'].append(mean)
        std_8protocols['dt_ll'].append(std)
        fidelities_8protocols['dt_ll'].append(fid)
        probs_8protocols['dt_ll'].append(pr)

        mean, std, fid, pr = swap_then_distill(n_samples, lam, c_val, T, samples, 'ASAP', 'ASAP')
        results_8protocols['st_aa'].append(mean)
        std_8protocols['st_aa'].append(std)
        fidelities_8protocols['st_aa'].append(fid)
        probs_8protocols['st_aa'].append(pr)

        mean, std, fid, pr = swap_then_distill(n_samples, lam, c_val, T, samples, 'ASAP', 'ALAP')
        results_8protocols['st_al'].append(mean)
        std_8protocols['st_al'].append(std)
        fidelities_8protocols['st_al'].append(fid)
        probs_8protocols['st_al'].append(pr)

        mean, std, fid, pr = swap_then_distill(n_samples, lam, c_val, T, samples, 'ALAP', 'ALAP')
        results_8protocols['st_ll'].append(mean)
        std_8protocols['st_ll'].append(std)
        fidelities_8protocols['st_ll'].append(fid)
        probs_8protocols['st_ll'].append(pr)

        results_4basic['dt_END'].append(distill_then_swap(n_samples, lam, c_val, T, samples, 'ALAP', 'ALAP')[0])
        results_4basic['dt_ASAP'].append(distill_then_swap(n_samples, lam, c_val, T, samples, 'ASAP', 'ASAP')[0])
        results_4basic['st_END'].append(swap_then_distill(n_samples, lam, c_val, T, samples, 'ALAP', 'ALAP')[0])
        results_4basic['st_ASAP'].append(swap_then_distill(n_samples, lam, c_val, T, samples, 'ASAP', 'ASAP')[0])

    results_by_c[c_name] = {**results_8protocols, **results_4basic}
    fidelities_by_c[c_name] = fidelities_8protocols
    success_probs_by_c[c_name] = probs_8protocols

c = c_regimes['medium']
results_8protocols = {k: results_by_c['medium'][k] for k in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']}
results_4basic = {k: results_by_c['medium'][k] for k in ['dt_END', 'dt_ASAP', 'st_END', 'st_ASAP']}
std_8protocols = {k: [] for k in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']}

T_vals = np.linspace(0.2, 2.0, 18)
lambda_fixed = 1.0
np.random.seed(SEED)
samples_fixed = {k: np.random.exponential(scale=1/lambda_fixed, size=n_samples) for k in ['t_l1_1','t_l1_2','t_l2_1','t_l2_2']}
Ic_dt_T, Ic_st_T = [], []
for T in T_vals:
    Ic_dt_T.append(distill_then_swap(n_samples, lambda_fixed, c, T, samples_fixed, 'ALAP', 'ALAP')[0])
    Ic_st_T.append(swap_then_distill(n_samples, lambda_fixed, c, T, samples_fixed, 'ALAP', 'ALAP')[0])

dist_fracs = np.linspace(0.1, 0.9, 15)
swap_fracs = np.linspace(0.1, 0.9, 15)
Ic_grid = np.zeros((len(dist_fracs), len(swap_fracs)))
F_grid = np.zeros_like(Ic_grid)
T_hm = 2.0/lambda_fixed
for i, df in enumerate(dist_fracs):
    for j, sf in enumerate(swap_fracs):
        t_dist, t_swap = df*T_hm, sf*T_hm
        Fvals = []
        for k in range(n_samples):
            l1 = sorted([samples_fixed['t_l1_1'][k], samples_fixed['t_l1_2'][k]])
            l2 = sorted([samples_fixed['t_l2_1'][k], samples_fixed['t_l2_2'][k]])
            if len([t for t in l1 if t < T_hm]) >= 2 and len([t for t in l2 if t < T_hm]) >= 2:
                F1p = isotropic_purification_pairwise(raw_fidelity(l1[0], t_dist, c), raw_fidelity(l1[1], t_dist, c))
                F2p = isotropic_purification_pairwise(raw_fidelity(l2[0], t_dist, c), raw_fidelity(l2[1], t_dist, c))
                F1 = compute_fidelity(F1p, max(t_swap-t_dist,0), c)
                F2 = compute_fidelity(F2p, max(t_swap-t_dist,0), c)
                Fsw = swapped_fidelity(F1, F2)
                Fvals.append(compute_fidelity(Fsw, max(T_hm-t_swap,0), c))
        if Fvals:
            Ic_grid[i,j] = np.mean(coherent_information_vectorized(np.array(Fvals)))
            F_grid[i,j] = np.mean(Fvals)

lam_hist = 1.0
c_hist = c
T_hist = 2.0 / lam_hist
n_samples_hist = 100000
np.random.seed(SEED)
samples_hist = {k: np.random.exponential(scale=1/lam_hist, size=n_samples_hist) for k in ['t_l1_1','t_l1_2','t_l2_1','t_l2_2']}
Fsw_ex, Ic_ex = swap_then_distill_distribution(n_samples_hist, lam_hist, c_hist, T_hist, samples_hist, 'ASAP', 'ASAP')
Fsw_discard, Ic_discard = discard_oldest_distribution(n_samples_hist, lam_hist, c_hist, T_hist, samples_hist)

F0_list = [0.45, 0.49, 0.51, 0.6, 0.8]
purif_threshold = {}
for F0 in F0_list:
    F = F0
    seq = [F0]
    for _ in range(10):
        F = isotropic_purification_pairwise(F, F)
        seq.append(F)
    purif_threshold[F0] = seq

def recurrence_yield(F0, n_raw=4000, rounds=5):
    arr = np.full(n_raw, F0)
    for _ in range(rounds):
        if len(arr) < 2:
            break
        idx = np.random.permutation(len(arr))
        if len(idx) % 2:
            idx = idx[:-1]
        p = idx.reshape(-1, 2)
        arr = isotropic_purification_pairwise(arr[p[:,0]], arr[p[:,1]])
    return len(arr)/n_raw

F0s_yield = np.linspace(0.52, 0.95, 10)
yields = [np.mean([recurrence_yield(f) for _ in range(5)]) for f in F0s_yield]

N_list = [2, 4, 8, 16, 32]
Ic_scaling_sim, Ic_scaling_analytic = [], []
lam_example, T_example = 1.0, 20.0
for seg in N_list:
    reps = []
    for _ in range(1500):
        Fs = [0.25 + 0.75*np.exp(-2*(T_example-np.random.exponential(1/lam_example))/c) for __ in range(seg)]
        Fsw = Fs[0]
        for x in Fs[1:]:
            Fsw = swapped_fidelity(Fsw, x)
        reps.append(Fsw)
    Ic_scaling_sim.append(np.mean(coherent_information_vectorized(np.array(reps))))
    baseline_sample = np.random.exponential(scale=1.0/lam_example, size=200000)
    T_total = 2.0*(seg/lam_example)
    T_per_link = np.maximum(0.0, (T_total/seg)-baseline_sample[:seg])
    F_link_mean = np.mean(raw_fidelity(baseline_sample[:seg], T_per_link, c))
    Ic_scaling_analytic.append(coherent_information_vectorized(np.array([analytic_repeated_swap(F_link_mean, seg)]))[0])

fig3 = plt.figure(figsize=(7,5))
plt.plot(T_vals, Ic_dt_T, label="DT-END", marker='o')
plt.plot(T_vals, Ic_st_T, label="ST-END", marker='s')
plt.xlabel("T (time units)")
plt.ylabel("Weighted coherent info")
plt.legend()
plt.grid()
plt.tight_layout()
plt.savefig("figures_for_paper/Ic_vs_T_both_protocols.pdf", dpi=300)
plt.show()

fig4 = plt.figure(figsize=(7,5))
plt.plot(lambda_vals, results_4basic['dt_END'], label="DT-END", marker='o')
plt.plot(lambda_vals, results_4basic['dt_ASAP'], label="DT-ASAP", marker='o', linestyle='--')
plt.plot(lambda_vals, results_4basic['st_END'], label="ST-END", marker='s')
plt.plot(lambda_vals, results_4basic['st_ASAP'], label="ST-ASAP", marker='s', linestyle='--')
plt.xlabel("λ (Rate, 1/time units)")
plt.ylabel("Weighted coherent info")
plt.grid()
plt.legend()
plt.tight_layout()
plt.savefig("figures_for_paper/Ic_vs_lambda_strategy_comparison.pdf", dpi=300)
plt.show()

fig5 = plt.figure(figsize=(10,4.5))
plt.subplot(1,2,1)
plt.title("Coherent Information")
plt.contourf(swap_fracs, dist_fracs, Ic_grid, 30, cmap='viridis')
plt.colorbar(label="$I_c$")
plt.xlabel("Swap fraction")
plt.ylabel("Distill fraction")
plt.subplot(1,2,2)
plt.title("Final Fidelity")
plt.contourf(swap_fracs, dist_fracs, F_grid, 30, cmap='plasma')
plt.colorbar(label="F")
plt.xlabel("Swap fraction")
plt.ylabel("Distill fraction")
plt.tight_layout()
plt.savefig("figures_for_paper/timing_heatmaps_Ic_and_Fidelity.pdf", dpi=300)
plt.show()

fig6 = plt.figure(figsize=(7,5))
plt.hist(Fsw_ex, bins=60, density=True, color='skyblue', edgecolor='black', alpha=0.7, label=PROTOCOL_LABELS['st_aa'])
plt.hist(Fsw_discard, bins=60, density=True, color='lightcoral', edgecolor='black', alpha=0.5, label=PROTOCOL_LABELS['discard'])
plt.xlabel("Final Fidelity", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.title(f"Fidelity Distribution (λ={lam_hist}, c={c_hist}, T={T_hist:.1f})", fontsize=13, fontweight='bold')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures_for_paper/fidelity_histogram_example.pdf", dpi=300)
plt.show()

fig7 = plt.figure(figsize=(7,5))
Ic_ex_pos = Ic_ex[Ic_ex > 0]
Ic_discard_pos = Ic_discard[Ic_discard > 0]
if len(Ic_ex_pos) > 0:
    plt.hist(Ic_ex_pos, bins=60, density=True, color='mediumseagreen', edgecolor='black', alpha=0.7, label=f'{PROTOCOL_LABELS["st_aa"]} ({len(Ic_ex_pos)} samples)')
if len(Ic_discard_pos) > 0:
    plt.hist(Ic_discard_pos, bins=60, density=True, color='orange', edgecolor='black', alpha=0.5, label=f'{PROTOCOL_LABELS["discard"]} ({len(Ic_discard_pos)} samples)')
plt.xlabel("Coherent Information", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.title(f"Coherent Information Distribution (Ic > 0)\n(λ={lam_hist}, c={c_hist}, T={T_hist:.1f})", fontsize=13, fontweight='bold')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures_for_paper/coherent_info_histogram_example.pdf", dpi=300)
plt.show()

fig8 = plt.figure(figsize=(6,4))
for F0 in F0_list:
    plt.plot(purif_threshold[F0], label=f"$F_0$={F0:.2f}", marker='o')
plt.axhline(0.5, color='k', ls='--', label='Threshold')
plt.legend()
plt.xlabel("Iteration")
plt.ylabel("Fidelity")
plt.title("Purification Threshold Behavior")
plt.grid()
plt.tight_layout()
plt.savefig("figures_for_paper/fig_purification_threshold.pdf", dpi=300)
plt.show()

fig9 = plt.figure(figsize=(6,4))
plt.plot(F0s_yield, yields, marker='o', color='green')
plt.xlabel("Initial Fidelity $F_0$")
plt.ylabel("Yield")
plt.title("Recurrence Purification Yield")
plt.grid()
plt.tight_layout()
plt.savefig("figures_for_paper/fig_recurrence_yield.pdf", dpi=300)
plt.show()

fig10 = plt.figure(figsize=(6,4))
plt.plot(N_list, Ic_scaling_sim, marker='o', label='Simulation')
plt.plot(N_list, Ic_scaling_analytic, marker='s', linestyle='--', label='Analytic')
plt.xscale('log', base=2)
plt.xlabel("Segments N")
plt.ylabel("Weighted coherent info")
plt.title("Repeater Scaling")
plt.grid(which='both', ls='--')
plt.legend()
plt.tight_layout()
plt.savefig("figures_for_paper/fig_repeater_scaling.pdf", dpi=300)
plt.show()

fig11 = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, results_8protocols['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color='black', markersize=7)
plt.plot(lambda_vals, results_8protocols['dt_aa'], label=PROTOCOL_LABELS['dt_aa'], marker='o', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['dt_al'], label=PROTOCOL_LABELS['dt_al'], marker='s', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['dt_ll'], label=PROTOCOL_LABELS['dt_ll'], marker='^', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['st_aa'], label=PROTOCOL_LABELS['st_aa'], marker='v', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['st_al'], label=PROTOCOL_LABELS['st_al'], marker='<', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, results_8protocols['st_ll'], label=PROTOCOL_LABELS['st_ll'], marker='>', linewidth=2, alpha=0.7)
plt.title("Seven Protocol Comparison", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Weighted coherent info", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', ncol=2)
plt.tight_layout()
plt.savefig("figures_for_paper/all_protocols_comparison.pdf", dpi=300)
plt.show()

fig_pr_lambda = plt.figure(figsize=(12, 6))
plt.plot(lambda_vals, success_probs_by_c['medium']['discard'], label=PROTOCOL_LABELS['discard'], marker='D', linewidth=2.5, color='black', markersize=7)
plt.plot(lambda_vals, success_probs_by_c['medium']['dt_aa'], label=PROTOCOL_LABELS['dt_aa'], marker='o', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_c['medium']['dt_al'], label=PROTOCOL_LABELS['dt_al'], marker='s', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_c['medium']['dt_ll'], label=PROTOCOL_LABELS['dt_ll'], marker='^', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_c['medium']['st_aa'], label=PROTOCOL_LABELS['st_aa'], marker='v', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_c['medium']['st_al'], label=PROTOCOL_LABELS['st_al'], marker='<', linewidth=2, alpha=0.7)
plt.plot(lambda_vals, success_probs_by_c['medium']['st_ll'], label=PROTOCOL_LABELS['st_ll'], marker='>', linewidth=2, alpha=0.7)
plt.title("Success Probability vs λ", fontsize=13, fontweight='bold')
plt.xlabel("λ (Rate, 1/time units)", fontsize=11)
plt.ylabel("Success probability", fontsize=11)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', ncol=2)
plt.tight_layout()
plt.savefig("figures_for_paper/success_prob_vs_lambda.pdf", dpi=300)
plt.show()

df_8protocols = pd.DataFrame({
    'lambda': lambda_vals,
    'Discard-Oldest_mean': results_8protocols['discard'],
    'D-ASAP-S-ASAP_mean': results_8protocols['dt_aa'],
    'D-ASAP-S-ALAP_mean': results_8protocols['dt_al'],
    'D-ALAP-S-ALAP_mean': results_8protocols['dt_ll'],
    'S-ASAP-D-ASAP_mean': results_8protocols['st_aa'],
    'S-ASAP-D-ALAP_mean': results_8protocols['st_al'],
    'S-ALAP-D-ALAP_mean': results_8protocols['st_ll']
})
df_8protocols['Data_Section'] = 'All_Protocols'
all_dataframes.append(df_8protocols)

df_regimes = pd.DataFrame({
    'lambda': lambda_vals,
    **{f'{c_name}_discard_Ic': results_by_c[c_name]['discard'] for c_name in c_regimes.keys()},
    **{f'{c_name}_discard_F': fidelities_by_c[c_name]['discard'] for c_name in c_regimes.keys()},
    **{f'{c_name}_discard_Pr': success_probs_by_c[c_name]['discard'] for c_name in c_regimes.keys()},
    **{f'{c_name}_st_aa_Ic': results_by_c[c_name]['st_aa'] for c_name in c_regimes.keys()},
    **{f'{c_name}_st_aa_F': fidelities_by_c[c_name]['st_aa'] for c_name in c_regimes.keys()},
    **{f'{c_name}_st_aa_Pr': success_probs_by_c[c_name]['st_aa'] for c_name in c_regimes.keys()},
    **{f'{c_name}_dt_ll_Ic': results_by_c[c_name]['dt_ll'] for c_name in c_regimes.keys()},
    **{f'{c_name}_dt_ll_F': fidelities_by_c[c_name]['dt_ll'] for c_name in c_regimes.keys()},
    **{f'{c_name}_dt_ll_Pr': success_probs_by_c[c_name]['dt_ll'] for c_name in c_regimes.keys()},
})
df_regimes['Data_Section'] = 'Parameter_Regimes'
all_dataframes.append(df_regimes)

stats_summary = {
    PROTOCOL_LABELS['discard']: {'mean': np.mean(results_8protocols['discard']), 'std': np.std(results_8protocols['discard']), 'max': np.max(results_8protocols['discard']), 'min': np.min(results_8protocols['discard'])},
    PROTOCOL_LABELS['dt_aa']: {'mean': np.mean(results_8protocols['dt_aa']), 'std': np.std(results_8protocols['dt_aa']), 'max': np.max(results_8protocols['dt_aa']), 'min': np.min(results_8protocols['dt_aa'])},
    PROTOCOL_LABELS['dt_al']: {'mean': np.mean(results_8protocols['dt_al']), 'std': np.std(results_8protocols['dt_al']), 'max': np.max(results_8protocols['dt_al']), 'min': np.min(results_8protocols['dt_al'])},
    PROTOCOL_LABELS['dt_ll']: {'mean': np.mean(results_8protocols['dt_ll']), 'std': np.std(results_8protocols['dt_ll']), 'max': np.max(results_8protocols['dt_ll']), 'min': np.min(results_8protocols['dt_ll'])},
    PROTOCOL_LABELS['st_aa']: {'mean': np.mean(results_8protocols['st_aa']), 'std': np.std(results_8protocols['st_aa']), 'max': np.max(results_8protocols['st_aa']), 'min': np.min(results_8protocols['st_aa'])},
    PROTOCOL_LABELS['st_al']: {'mean': np.mean(results_8protocols['st_al']), 'std': np.std(results_8protocols['st_al']), 'max': np.max(results_8protocols['st_al']), 'min': np.min(results_8protocols['st_al'])},
    PROTOCOL_LABELS['st_ll']: {'mean': np.mean(results_8protocols['st_ll']), 'std': np.std(results_8protocols['st_ll']), 'max': np.max(results_8protocols['st_ll']), 'min': np.min(results_8protocols['st_ll'])}
}

df_stats = pd.DataFrame(stats_summary).T
df_stats['Protocol'] = df_stats.index
df_stats['Data_Section'] = 'Protocol_Statistics'
all_dataframes.append(df_stats.reset_index(drop=True))

temporal_stats = {
    'DT-END': {'mean': np.mean(Ic_dt_T), 'std': np.std(Ic_dt_T), 'max': np.max(Ic_dt_T), 'min': np.min(Ic_dt_T)},
    'ST-END': {'mean': np.mean(Ic_st_T), 'std': np.std(Ic_st_T), 'max': np.max(Ic_st_T), 'min': np.min(Ic_st_T)}
}
df_temporal = pd.DataFrame(temporal_stats).T
df_temporal['Protocol'] = df_temporal.index
df_temporal['Data_Section'] = 'Temporal_Analysis'
all_dataframes.append(df_temporal.reset_index(drop=True))

fidelity_stats = {
    'Fsw_mean': np.mean(Fsw_ex), 'Fsw_std': np.std(Fsw_ex), 'Fsw_min': np.min(Fsw_ex), 'Fsw_max': np.max(Fsw_ex),
    'Ic_mean': np.mean(Ic_ex), 'Ic_std': np.std(Ic_ex), 'Ic_min': np.min(Ic_ex), 'Ic_max': np.max(Ic_ex)
}
df_fidelity = pd.DataFrame([fidelity_stats])
df_fidelity['Data_Section'] = 'Fidelity_Distribution'
all_dataframes.append(df_fidelity)

timing_stats = {
    'optimal_distill_frac': dist_fracs[np.unravel_index(Ic_grid.argmax(), Ic_grid.shape)[0]],
    'optimal_swap_frac': swap_fracs[np.unravel_index(Ic_grid.argmax(), Ic_grid.shape)[1]],
    'max_Ic_timing': np.max(Ic_grid),
    'max_F_timing': np.max(F_grid),
    'mean_Ic_timing': np.mean(Ic_grid[Ic_grid > 0]),
    'mean_F_timing': np.mean(F_grid[F_grid > 0])
}
df_timing = pd.DataFrame([timing_stats])
df_timing['Data_Section'] = 'Timing_Optimization'
all_dataframes.append(df_timing)

best_protocol = max(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
worst_protocol = min(stats_summary.keys(), key=lambda k: stats_summary[k]['mean'])
improvement_vs_discard = ((stats_summary[best_protocol]['mean'] - stats_summary[PROTOCOL_LABELS['discard']]['mean']) / stats_summary[PROTOCOL_LABELS['discard']]['mean'] * 100) if stats_summary[PROTOCOL_LABELS['discard']]['mean'] != 0 else float('inf')

comparison_metrics = {
    'best_protocol': best_protocol,
    'best_mean_Ic': stats_summary[best_protocol]['mean'],
    'best_max_Ic': stats_summary[best_protocol]['max'],
    'worst_protocol': worst_protocol,
    'worst_mean_Ic': stats_summary[worst_protocol]['mean'],
    'improvement_vs_discard_pct': improvement_vs_discard,
    'discard_mean': stats_summary[PROTOCOL_LABELS['discard']]['mean'],
    'dt_end_mean_temporal': temporal_stats['DT-END']['mean'],
    'st_end_mean_temporal': temporal_stats['ST-END']['mean'],
    'dt_end_max_temporal': temporal_stats['DT-END']['max'],
    'st_end_max_temporal': temporal_stats['ST-END']['max'],
    'temporal_improvement_pct': ((temporal_stats['ST-END']['mean'] - temporal_stats['DT-END']['mean']) / temporal_stats['DT-END']['mean'] * 100) if temporal_stats['DT-END']['mean'] != 0 else float('inf')
}
df_comparison = pd.DataFrame([comparison_metrics])
df_comparison['Data_Section'] = 'Key_Comparisons'
all_dataframes.append(df_comparison)

df_combined = pd.concat(all_dataframes, ignore_index=True, sort=False)
df_combined.to_csv("figures_for_paper/double_link_combined_data.csv", index=False)

print("\n" + "="*80)
print("FIGURE GENERATION COMPLETE")
print("="*80)
print(f"\nAll figures saved to: figures_for_paper/")
print(f"Total figures generated: 13")
print("\nFigure List:")
print("  1. physical_params_coherent_info_vs_T.pdf")
print("  2. physical_params_fidelity_vs_T.pdf")
print("  3. physical_params_success_prob_vs_T.pdf")
print("  4. Ic_vs_T_both_protocols.pdf")
print("  5. Ic_vs_lambda_strategy_comparison.pdf")
print("  6. timing_heatmaps_Ic_and_Fidelity.pdf")
print("  7. fidelity_histogram_example.pdf")
print("  8. coherent_info_histogram_example.pdf")
print("  9. fig_purification_threshold.pdf")
print(" 10. fig_recurrence_yield.pdf")
print(" 11. fig_repeater_scaling.pdf")
print(" 12. all_protocols_comparison.pdf")
print(" 13. success_prob_vs_lambda.pdf")
print("\n" + "="*80)
print("PARAMETER REGIME COMPARISON")
print("="*80)
for c_name, c_val in c_regimes.items():
    print(f"\nc = {c_val} ({c_name}):")
    print(f"  Best protocol (Ic): {max(['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll'], key=lambda p: np.mean(results_by_c[c_name][p]))}")
    print(f"  Mean fidelity range: [{np.min([np.mean(fidelities_by_c[c_name][p]) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]):.4f}, {np.max([np.mean(fidelities_by_c[c_name][p]) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]):.4f}]")
    print(f"  Mean success prob range: [{np.min([np.mean(success_probs_by_c[c_name][p]) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]):.4f}, {np.max([np.mean(success_probs_by_c[c_name][p]) for p in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]):.4f}]")
print("\n" + "="*80)
print("KEY STATISTICS SUMMARY (c = {})".format(c))
print("="*80)
print(f"\nBest Protocol: {best_protocol}")
print(f"  Mean Ic: {stats_summary[best_protocol]['mean']:.6f}")
print(f"  Std Dev: {stats_summary[best_protocol]['std']:.6f}")
print(f"  Max Ic: {stats_summary[best_protocol]['max']:.6f}")
print(f"  Min Ic: {stats_summary[best_protocol]['min']:.6f}")
print(f"\nWorst Protocol: {worst_protocol}")
print(f"  Mean Ic: {stats_summary[worst_protocol]['mean']:.6f}")
print(f"\n{PROTOCOL_LABELS['discard']} Baseline:")
print(f"  Mean Ic: {stats_summary[PROTOCOL_LABELS['discard']]['mean']:.6f}")
print(f"  Mean Fidelity: {np.mean(fidelities_by_c['medium']['discard']):.6f}")
print(f"  Mean Success Prob: {np.mean(success_probs_by_c['medium']['discard']):.6f}")
print(f"\nPerformance Improvement:")
print(f"  Best vs Discard-Oldest: {improvement_vs_discard:+.2f}%")
print(f"\nTemporal Analysis (DT-END vs ST-END):")
print(f"  DT-END Mean: {temporal_stats['DT-END']['mean']:.6f} (Max: {temporal_stats['DT-END']['max']:.6f})")
print(f"  ST-END Mean: {temporal_stats['ST-END']['mean']:.6f} (Max: {temporal_stats['ST-END']['max']:.6f})")
print(f"  ST-END improvement: {comparison_metrics['temporal_improvement_pct']:+.2f}%")
print(f"\nTiming Optimization:")
print(f"  Optimal Distill Fraction: {timing_stats['optimal_distill_frac']:.3f}")
print(f"  Optimal Swap Fraction: {timing_stats['optimal_swap_frac']:.3f}")
print(f"  Max Ic at Optimal Timing: {timing_stats['max_Ic_timing']:.6f}")
print(f"\nFidelity Distribution Statistics:")
print(f"  Mean Fidelity: {fidelity_stats['Fsw_mean']:.4f} ± {fidelity_stats['Fsw_std']:.4f}")
print(f"  Range: [{fidelity_stats['Fsw_min']:.4f}, {fidelity_stats['Fsw_max']:.4f}]")
print(f"  Mean Ic: {fidelity_stats['Ic_mean']:.4f} ± {fidelity_stats['Ic_std']:.4f}")
print("\n" + "="*80)
print("ALL 7 PROTOCOLS PERFORMANCE TABLE")
print("="*80)
print(f"{'Protocol':<20} {'Mean Ic':>12} {'Std Dev':>12} {'Max Ic':>12} {'Min Ic':>12}")
print("-"*80)
for protocol in [PROTOCOL_LABELS[k] for k in ['discard', 'dt_aa', 'dt_al', 'dt_ll', 'st_aa', 'st_al', 'st_ll']]:
    s = stats_summary[protocol]
    print(f"{protocol:<20} {s['mean']:>12.6f} {s['std']:>12.6f} {s['max']:>12.6f} {s['min']:>12.6f}")
print("="*80)
print("\nAll data saved to single CSV file:")
print("  - figures_for_paper/double_link_combined_data.csv")
print("    Contains sections: Physical_Params (6 regimes), All_Protocols,")
print("    Parameter_Regimes, Protocol_Statistics, Temporal_Analysis,")
print("    Fidelity_Distribution, Timing_Optimization, Key_Comparisons")
print("="*80)